// Search tags for every remixable screen in the app library, so the Playground's screen search finds
// screens by what they are and what they're for ("timer", "calendar", "productivity"), not only by
// their titles. Keyed by app slug, one list per step of the app's remix, in step order. Hand-kept:
// when a remix gains, loses or reorders a screen (lib/apps/library.ts, the pattern's steps), update
// its line here too. Lowercase; plural and singular forms both match (search is by word start).
//
// Tag a screen with: what it's for (the domain), what kind of screen it is, and the notable UI on it.

export const SCREEN_TAGS: Record<string, string[][]> = {
  "gentler-streak": [
    ["fitness", "health", "activity", "dashboard", "home", "today", "chart", "trend", "graph", "mascot", "wellness", "workout"],
    ["fitness", "health", "steps", "counter", "stats", "chart", "comparison", "number", "walking", "tracker"],
    ["health", "recovery", "body", "stats", "metrics", "tiles", "vitals", "heart rate", "wellness"],
    ["sleep", "health", "night", "timeline", "stages", "chart", "rest", "tracker"],
    ["history", "fitness", "calendar", "week", "month", "year", "tabs", "stats", "progress"],
  ],
  "how-we-feel": [
    ["mood", "feelings", "emotions", "mental health", "check-in", "picker", "bubbles", "full screen", "colours", "wellness", "journal", "log"],
    ["mood", "journal", "log", "history", "feed", "cards", "contour", "shapes", "mental health", "list"],
    ["mood", "calendar", "month", "shapes", "tabs", "stats", "insights", "chart", "bars", "history", "tracker"],
    ["mental health", "wellness", "tools", "exercises", "cards", "flip card", "tiles", "grid", "self-care", "library"],
    ["social", "friends", "sharing", "community", "feed", "cards", "reactions", "hearts", "toast", "mood"],
    ["profile", "photo", "avatar", "crop", "cropper", "image", "editor", "sheet", "pinch", "zoom"],
  ],
  stoic: [
    ["journal", "wellness", "home", "dashboard", "morning", "routine", "checklist", "habits", "productivity", "self-care", "greeting"],
    ["journal", "evening", "night", "routine", "wind down", "mascot", "wellness", "self-care", "reflection"],
    ["journal", "writing", "editor", "composer", "form", "sheet", "prompt", "note", "text input", "entry"],
    ["insights", "stats", "mood", "chart", "analytics", "week", "month", "tabs", "journal", "trends"],
    ["breathing", "meditation", "mindfulness", "timer", "ring", "calm", "relax", "wellness", "animation"],
    ["guided", "courses", "programs", "library", "list", "progress", "lessons", "learning", "self-care"],
  ],
  tiimo: [
    ["productivity", "planner", "schedule", "today", "tasks", "to-do", "checklist", "day", "routine", "week", "calendar", "adhd"],
    ["productivity", "focus", "timer", "pomodoro", "countdown", "ring", "concentration", "sheet", "sounds", "deep work"],
    ["productivity", "brain dump", "tasks", "chat", "assistant", "ai", "input", "mascot", "notes", "planning"],
  ],
  lungy: [
    ["breathing", "meditation", "wellness", "exercise", "detail", "preview", "full bleed", "favourite", "mindfulness", "calm", "health"],
    ["breathing", "coach", "session", "full screen", "immersive", "guided", "animation", "rounds", "meditation", "orbs"],
    ["breathing", "flower", "bloom", "petals", "full screen", "animation", "interactive", "session", "gesture", "meditation"],
    ["breathing", "pillows", "shapes", "full screen", "animation", "session", "guided", "rhythm", "calm", "meditation"],
    ["breathing", "tide", "waves", "water", "full screen", "animation", "session", "progress", "exhale", "meditation", "calm"],
    ["summary", "results", "stats", "completion", "success", "mascot", "chart", "session", "breathing"],
  ],
  timepage: [
    ["calendar", "week", "agenda", "schedule", "events", "planner", "productivity", "date picker"],
    ["calendar", "event", "details", "map", "location", "directions", "sheet", "flip card", "travel time"],
    ["calendar", "day", "today", "agenda", "dashboard", "weather", "to-do", "tasks", "productivity", "planner"],
    ["weather", "forecast", "chart", "graph", "temperature", "tabs", "scrub", "rain", "wind"],
    ["calendar", "day", "hours", "timeline", "schedule", "week", "month", "tabs", "productivity"],
    ["calendar", "month", "grid", "overview", "planner", "schedule", "add button", "menu"],
    ["calendar", "event", "new", "create", "add", "form", "address", "location", "autocomplete", "search", "sheet"],
  ],
  storygraph: [
    ["books", "reading", "library", "shelves", "list", "tabs", "tracker", "collection"],
    ["books", "reading", "recommendations", "discover", "for you", "covers", "carousel", "browse"],
    ["books", "reading", "stats", "year", "insights", "chart", "bars", "counter", "analytics"],
    ["books", "reading", "goal", "habit", "streak", "progress", "mascot", "slider", "tracker"],
    ["books", "social", "friends", "feed", "activity", "updates", "empty state", "community"],
    ["books", "reading", "challenges", "goals", "progress", "ring", "achievements"],
  ],
  mela: [
    ["recipes", "food", "cooking", "library", "collections", "list", "tabs", "browse", "home"],
    ["recipe", "food", "cooking", "details", "ingredients", "photo", "stats", "article"],
    ["cooking", "recipe", "steps", "timer", "kitchen", "focus", "instructions", "guided"],
    ["cooking", "recipe", "servings", "converter", "units", "sheet", "slider", "settings"],
    ["meal plan", "food", "week", "planner", "calendar", "schedule", "swipe", "list"],
    ["shopping list", "groceries", "checklist", "to-do", "tasks", "list", "counter", "tabs"],
  ],
  sunlitt: [
    ["weather", "sun", "sunrise", "sunset", "daylight", "chart", "arc", "time", "outdoors"],
    ["map", "location", "picker", "pin", "address", "place", "spot", "drag", "sheet", "outdoors"],
    ["sun", "map", "city", "shadows", "location", "daylight", "photography", "outdoors"],
    ["sun", "terrain", "hills", "shadows", "map", "daylight", "outdoors", "hiking"],
    ["sun", "sky", "altitude", "compass", "daylight", "astronomy", "stats"],
    ["sun", "daylight", "times", "sunrise", "sunset", "reminders", "notifications", "sheet", "tabs", "list", "schedule"],
  ],
  daylio: [
    ["mood", "check-in", "journal", "diary", "picker", "mascot", "today", "log", "mental health"],
    ["mood", "activities", "tags", "toggles", "icons", "picker", "journal", "log", "habits"],
    ["journal", "note", "writing", "gratitude", "form", "text input", "diary", "entry"],
    ["journal", "entries", "diary", "history", "feed", "list", "timeline", "mood"],
    ["mood", "stats", "month", "chart", "line", "scrub", "gauge", "ring", "count", "faces", "insights", "analytics"],
    ["mood", "year", "calendar", "grid", "dots", "history", "stats", "overview"],
  ],
  flighty: [
    ["travel", "flights", "trips", "list", "map", "routes", "tracker", "home", "cards", "airline"],
    ["travel", "flight", "details", "status", "countdown", "progress", "stats", "airport", "timeline"],
    ["travel", "flight", "delay", "status", "weather", "timeline", "alerts", "counter"],
    ["travel", "social", "friends", "sharing", "tabs", "flights", "empty state"],
    ["travel", "flight", "search", "add", "sheet", "form", "input", "tracker"],
  ],
  "pocket-casts": [
    ["podcasts", "audio", "library", "grid", "covers", "tabs", "mini player", "media", "downloads"],
    ["podcasts", "audio", "player", "now playing", "controls", "scrubber", "media", "music", "sleep timer"],
    ["podcasts", "audio", "settings", "speed", "stepper", "slider", "sheet", "controls", "playback"],
    ["podcasts", "playlist", "collection", "covers", "list", "shuffle", "music", "media"],
    ["podcasts", "queue", "up next", "list", "counter", "media", "music", "hold to confirm"],
  ],
  pennies: [
    ["finance", "budget", "money", "dashboard", "home", "balance", "spending", "envelopes", "list", "counter"],
    ["finance", "budget", "details", "balance", "spending", "transactions", "ring", "progress", "list"],
    ["finance", "expense", "keypad", "number pad", "input", "add", "sheet", "money", "calculator"],
    ["finance", "history", "transactions", "spending", "tabs", "pages", "empty state", "list", "summary"],
    ["finance", "budget", "settings", "picker", "options", "sheet", "schedule"],
    ["finance", "transfer", "money", "budget", "sheet", "blocks", "move"],
  ],
  planta: [
    ["plants", "home", "rooms", "collection", "collage", "illustration", "gardening", "tasks", "tabs", "list", "reminders"],
    ["plants", "details", "care", "carousel", "chips", "rings", "tasks", "schedule", "gardening", "profile"],
    ["plants", "camera", "scan", "identify", "photo", "modes", "sheet", "ai", "recognition"],
    ["plants", "health", "diagnosis", "check-up", "hero", "tiles", "grid", "empty state", "gardening"],
    ["plants", "light", "meter", "sensor", "camera", "window", "gauge", "measure", "tool"],
    ["plants", "social", "community", "groups", "feed", "posts", "tabs", "photos", "reactions"],
  ],
  vocabulary: [
    ["learning", "education", "words", "language", "flashcards", "cards", "pager", "daily goal", "home"],
    ["learning", "quiz", "practice", "game", "multiple choice", "mascot", "education", "test"],
    ["learning", "topics", "categories", "browse", "blocks", "skeleton", "loading", "sheet", "education"],
    ["learning", "words", "vocabulary", "list", "a to z", "alphabet", "index", "sections", "favorites", "liked"],
    ["learning", "add", "form", "input", "text input", "sheet", "words", "create"],
    ["learning", "streak", "goal", "habit", "progress", "week", "education", "motivation"],
  ],
  habitify: [
    ["habits", "productivity", "today", "tracker", "checklist", "rings", "routine", "timer", "goals", "home", "to-do", "tour", "onboarding", "coach marks", "first run"],
    ["habits", "productivity", "stats", "consistency", "score", "calendar", "grid", "tabs", "analytics", "streak"],
    ["habits", "integrations", "sources", "sync", "health", "error", "notice", "tiles", "settings", "connect"],
    ["habits", "productivity", "details", "heatmap", "calendar", "stats", "history", "streak", "scrub"],
    ["habits", "productivity", "new", "create", "form", "sheet", "timer", "stepper", "add", "goal", "signature", "promise", "sign"],
  ],
  tricount: [
    ["finance", "expenses", "split", "bills", "group", "friends", "list", "counter", "money", "travel", "home"],
    ["finance", "balances", "split", "settle up", "debts", "money", "friends", "sheet", "summary"],
    ["photos", "gallery", "collage", "group", "trip", "memories", "media", "grid", "select", "multi-select"],
    ["offline", "sync", "error", "status", "list", "finance", "connection", "banner", "retry"],
    ["finance", "expense", "add", "form", "amount", "input", "sheet", "split", "payer", "money", "receipts", "attachments", "photos"],
    ["finance", "currency", "converter", "exchange", "search", "list", "travel", "money"],
  ],
  waterllama: [
    ["health", "water", "hydration", "tracker", "habits", "today", "home", "drinks", "log", "progress"],
    ["widgets", "home screen", "customize", "settings", "preview", "counter", "water"],
    ["streak", "calendar", "month", "history", "ring", "progress", "habits", "log", "water"],
    ["challenges", "goals", "achievements", "gamification", "tabs", "tiles", "mascot", "empty state"],
    ["summary", "success", "goal", "completion", "celebration", "mascot", "week", "water"],
    ["share", "social", "card", "sheet", "export", "success", "loading"],
  ],
  tripsy: [
    ["travel", "trip", "itinerary", "planner", "schedule", "day by day", "checklist", "home", "dashboard", "countdown", "tabs"],
    ["travel", "flight", "route", "map", "details", "gate", "times", "airport", "stats"],
    ["travel", "alerts", "notifications", "settings", "toggles", "switches", "list", "flight"],
    ["travel", "places", "map", "locations", "pins", "distance", "tabs", "saved", "empty state", "explore"],
    ["travel", "social", "friends", "places", "avatars", "map", "invite", "sharing", "collaboration", "list"],
    ["chat", "messages", "group", "friends", "conversation", "travel", "live", "feed", "social", "sheet"],
    ["travel", "finance", "spending", "budget", "expenses", "categories", "chart", "donut", "ring", "sheet", "summary", "counter"],
  ],
  sofa: [
    ["entertainment", "collections", "lists", "backlog", "library", "movies", "books", "games", "covers", "home"],
    ["entertainment", "tv", "shows", "books", "games", "in progress", "tabs", "tracker", "watchlist"],
    ["entertainment", "search", "discover", "browse", "covers", "shelves", "movies", "books", "games"],
    ["articles", "reading list", "read later", "links", "bookmarks", "saved", "web", "cards", "list"],
    ["podcasts", "audio", "queue", "now playing", "player", "media", "list"],
    ["entertainment", "countdown", "releases", "upcoming", "dates", "timer", "empty state", "calendar"],
    ["entertainment", "stats", "year", "insights", "chart", "bars", "counter", "analytics", "recap"],
  ],
};
