// Agenda Day: one day of a scrolling week agenda. A date rail on the left (weekday over the date on
// the screen's ground, the picked day lifted into a signal tile) and the day's events on the card
// surface to the right, each behind a coloured capsule; an empty day can say so. The "theme" surface
// follows light and dark; "ground" puts rail and events on the screen's own background, split by
// hairlines; "classic" keeps a black rail on pale rows. Stack several with no spacing and
// the rail runs unbroken down the screen; they share one selection, so tapping a day moves the tile
// there and opens it.
import type { SwiftPieceDefinition } from "../../core/schema.js";
import { call, num } from "../../core/swift.js";
import { bool, link, number, opts, select, text } from "../shared.js";
import { data, records, swiftStrs, swiftTint, tint } from "./data-kit.js";
import { linkAction } from "./nav-action.js";

const s = (p: Record<string, unknown>, k: string) => String(p[k] ?? "");
const n = (p: Record<string, unknown>, k: string) => Number(p[k] ?? 0);

/** "Title | time | colour; …" → events. */
export const agendaEvents = (value: unknown) => records(value, 6).map(([title = "", time = "", color = "blue"]) => ({ title, time, color }));

const SWIFT = [
  "private struct AgendaDay: View {",
  "    let weekday: String",
  "    let date: Int",
  "    var titles: [String] = []",
  "    var times: [String] = []",
  "    var colors: [Color] = []",
  "    var empty = \"\"",
  "    var sideLabel = \"\"",
  "    var sideColor: Color = .red",
  "    var classic = false",
  "    var ground = false",
  "    var shaded = false",
  "    var height: CGFloat = 120",
  "    @Binding var selection: Int",
  "    var action: (() -> Void)? = nil",
  "    @Environment(\\.colorScheme) private var scheme",
  "    @Environment(\\.accessibilityReduceMotion) private var reduceMotion",
  "    @State private var shown = false",
  "",
  "    private let signal = Color(red: 1, green: 0, blue: 0)",
  "    private var dark: Bool { !classic && scheme == .dark }",
  "    /// The rail sits on the screen's ground; the events on the card surface (a shade darker every other day).",
  "    private var rail: Color {",
  "        if classic { return .black }",
  "        if ground { return .clear }",
  "        return dark ? Color(red: 0.027, green: 0.027, blue: 0.031) : Color(red: 0.953, green: 0.949, blue: 0.933)",
  "    }",
  "    private var surface: Color {",
  "        if classic { return shaded ? Color(white: 0.96) : Color(white: 0.985) }",
  "        if ground { return .clear }",
  "        if dark { return shaded ? Color(red: 0.063, green: 0.063, blue: 0.071) : Color(red: 0.078, green: 0.078, blue: 0.086) }",
  "        return shaded ? Color(red: 0.98, green: 0.98, blue: 0.973) : .white",
  "    }",
  "    private var ink: Color { classic ? .black : (dark ? .white : Color(red: 0.078, green: 0.078, blue: 0.078)) }",
  "",
  "    var body: some View {",
  "        Button {",
  "            withAnimation(reduceMotion ? .easeOut(duration: 0.2) : .snappy(duration: 0.3)) { selection = date }",
  "            action?()",
  "        } label: {",
  "            row",
  "        }",
  "        .buttonStyle(AgendaDayPress())",
  "        .sensoryFeedback(.selection, trigger: selection) { _, new in new == date }",
  "        .onAppear { shown = true }",
  "    }",
  "",
  "    private var row: some View {",
  "        HStack(spacing: 0) {",
  "            ZStack {",
  "                rail",
  "                if selection == date {",
  "                    RoundedRectangle(cornerRadius: 12, style: .continuous).fill(classic ? .white : signal).frame(width: 48, height: 72)",
  "                        .transition(reduceMotion ? .opacity : .scale(scale: 0.95).combined(with: .opacity))",
  "                }",
  "                VStack(spacing: 0) {",
  "                    Text(weekday).font(.subheadline)",
  "                    Text(\"\\(date)\").font(.title2.weight(.bold)).monospacedDigit()",
  "                }",
  "                .foregroundStyle(selection == date ? (classic ? Color.black : Color.white) : (classic ? Color.white : ink))",
  "                if !sideLabel.isEmpty {",
  "                    Text(sideLabel)",
  "                        .font(.caption.weight(.bold))",
  "                        .tracking(4)",
  "                        .foregroundStyle(sideColor)",
  "                        .fixedSize()",
  "                        .rotationEffect(.degrees(-90))",
  "                        .frame(maxWidth: .infinity, maxHeight: .infinity, alignment: .leading)",
  "                        .offset(x: -30)",
  "                }",
  "            }",
  "            .frame(width: 76)",
  "            VStack(alignment: .leading, spacing: 16) {",
  "                if titles.isEmpty && !empty.isEmpty {",
  "                    Text(empty).font(.subheadline).foregroundStyle(ink.opacity(0.45))",
  "                }",
  "                ForEach(titles.indices, id: \\.self) { i in",
  "                    HStack(alignment: .top, spacing: 12) {",
  "                        Capsule().fill(colors[i % max(colors.count, 1)]).frame(width: 8, height: times[i].isEmpty ? 12 : 28)",
  "                        VStack(alignment: .leading, spacing: 2) {",
  "                            Text(titles[i]).font(.headline).lineLimit(1)",
  "                            if !times[i].isEmpty {",
  "                                Text(times[i]).font(.footnote).monospacedDigit().opacity(0.6).lineLimit(1)",
  "                            }",
  "                        }",
  "                    }",
  "                    .opacity(shown ? 1 : 0)",
  "                    .scaleEffect(shown || reduceMotion ? 1 : 0.95, anchor: .leading)",
  "                    .animation(.easeOut(duration: reduceMotion ? 0.2 : 0.28).delay(Double(min(i, 7)) * 0.04), value: shown)",
  "                }",
  "            }",
  "            .foregroundStyle(ink)",
  "            .padding(.horizontal, 12)",
  "            .frame(maxWidth: .infinity, maxHeight: .infinity, alignment: .leading)",
  "            .background(surface)",
  "            .overlay(alignment: .bottom) { Rectangle().fill(ink.opacity(ground ? 0.08 : 0.06)).frame(height: 1) }",
  "        }",
  "        .frame(height: height)",
  "        .contentShape(.rect)",
  "    }",
  "}",
  "",
  "/// A row under a finger: a quick highlight, not a scale.",
  "private struct AgendaDayPress: ButtonStyle {",
  "    func makeBody(configuration: Configuration) -> some View {",
  "        configuration.label",
  "            .overlay { Color.primary.opacity(configuration.isPressed ? 0.06 : 0).allowsHitTesting(false) }",
  "            .animation(.easeOut(duration: configuration.isPressed ? 0.1 : 0.2), value: configuration.isPressed)",
  "    }",
  "}",
];

export const agendaDay: SwiftPieceDefinition = {
  id: "agenda-day",
  name: "Agenda Day",
  category: "pieces",
  description: "One day of a week agenda: a date rail and the day's events behind coloured capsules, in light and dark. Stack days with no spacing; they share one selection that moves between them.",
  availability: "free",
  preview: { component: "agenda-day", chunk: "app-pieces" },
  icon: "calendar",
  concepts: ["state", "binding", "hstack"],
  anatomy: [
    { part: "Rail", props: ["weekday", "date", "selected", "sideLabel", "sideTint"] },
    { part: "Events", props: ["events"] },
    { part: "Row", props: ["surface", "shaded", "height"] },
    { part: "Interaction", props: ["link"] },
  ],
  interactions: ["tap", "select", "push", "spring", "haptic"],
  variants: [
    { id: "busy", label: "Two events", props: {} },
    { id: "free", label: "Free day", props: { events: "", empty: "Nothing planned", weekday: "THU", date: 15, sideLabel: "OCTOBER" } },
    { id: "ground", label: "One ground", props: { surface: "ground" } },
    { id: "light", label: "Classic", props: { surface: "light" } },
  ],
  states: [
    { id: "picked", label: "Picked", props: { selected: true } },
    { id: "shaded", label: "Shaded", props: { shaded: true } },
  ],
  properties: [
    text("weekday", "Weekday", "WED"),
    number("date", "Date", 14, 1, 31),
    data("events", "Events", "Standup | 9:30–9:45 AM | azure; Pottery class | 7–9 PM | ember", { hint: "Title | time | colour, separated by semicolons. Time is optional." }),
    text("empty", "When empty", "", { hint: "A quiet line for a day with no events, e.g. Nothing planned." }),
    bool("selected", "Picked", false, { hint: "The day the shared selection starts on." }),
    text("sideLabel", "Side label", "", { hint: "Vertical text down the rail's edge, e.g. the month." }),
    tint("sideTint", "Side label colour", "signal"),
    select("surface", "Surface", "dark", opts(["dark", "Theme (light and dark)"], ["ground", "One ground (hairlines)"], ["light", "Classic (black rail)"]), { hint: "Theme puts the rail on the screen's ground and the events on the card surface. One ground puts both on the screen's own background, split by hairlines. Both follow light and dark and lift the picked day in signal red." }),
    bool("shaded", "Shaded row", false),
    number("height", "Height", 120, 70, 220),
    link(),
  ],
  swift: {
    imports: [],
    emit(p, ctx) {
      ctx.declare("AgendaDay", SWIFT);
      const events = agendaEvents(s(p, "events"));
      const sel = ctx.shared("agendaDay", "Int", "0", false);
      if (p.selected === true) ctx.shared("agendaDay", "Int", num(n(p, "date")), true);
      const act = linkAction(ctx, p.link);
      return {
        lines: call("AgendaDay", [
          ["weekday", ctx.str(s(p, "weekday"))],
          ["date", num(n(p, "date"))],
          events.length > 0 && ["titles", swiftStrs(events.map((e) => e.title), ctx.str)],
          events.length > 0 && ["times", swiftStrs(events.map((e) => e.time), ctx.str)],
          events.length > 0 && ["colors", `[${events.map((e) => swiftTint(e.color, "blue")).join(", ")}]`],
          events.length === 0 && s(p, "empty").trim() && ["empty", ctx.str(s(p, "empty").trim())],
          s(p, "sideLabel").trim() && ["sideLabel", ctx.str(s(p, "sideLabel").trim())],
          s(p, "sideLabel").trim() && ["sideColor", swiftTint(s(p, "sideTint"), "signal")],
          s(p, "surface") === "light" && ["classic", "true"],
          s(p, "surface") === "ground" && ["ground", "true"],
          p.shaded === true && ["shaded", "true"],
          n(p, "height") !== 120 && ["height", num(n(p, "height"))],
          ["selection", `$${sel}`],
          act && ["action", `{ ${act} }`],
        ]),
      };
    },
  },
};
