// Balance Panel: a full-bleed colour panel that is the whole screen of a budget. What's left, huge,
// with a tap to switch between the month and today; a ring of the days left in the period below;
// and a bar of round buttons to add (the accent), move and review spending. The panel eases in from
// 0.95 and the ring sweeps round as it appears; the amount rolls when it flips; every button dips
// to 0.97 and taps back with a haptic. The card surface follows light and dark.
import type { Props, SwiftPieceDefinition } from "../../core/schema.js";
import { INDENT, modifiers, num, str } from "../../core/swift.js";
import { link, number, opts, select, text } from "../shared.js";
import { BLOCK_COLORS, blockColor } from "./color-block-list.js";
import { construct, linkAction, rgb } from "./emit-link-action.js";

const s = (p: Props, k: string) => String(p[k] ?? "");
const n = (p: Props, k: string) => Number(p[k] ?? 0);
const dbl = (v: number) => (Number.isInteger(v) ? `${v}.0` : num(v));
const I = (d: number) => INDENT.repeat(d);

const STRUCT = (): string[] => [
  "/// A budget as one colour panel: what's left, the days left in the period, and its actions.",
  "private struct BalancePanel: View {",
  `${I(1)}var title = ""`,
  `${I(1)}let amount: Double`,
  `${I(1)}var caption = ""`,
  `${I(1)}var altAmount: Double? = nil`,
  `${I(1)}var altCaption = ""`,
  `${I(1)}var daysLeft = 22`,
  `${I(1)}var daysInPeriod = 31`,
  `${I(1)}var ringCaption = "days left"`,
  `${I(1)}let color: Color`,
  `${I(1)}var height: CGFloat = 640`,
  `${I(1)}var dark = false`,
  `${I(1)}var onSettings: () -> Void = {}`,
  `${I(1)}var onTransfer: () -> Void = {}`,
  `${I(1)}var onAdd: () -> Void = {}`,
  `${I(1)}var onList: () -> Void = {}`,
  `${I(1)}@State private var showsAlt = false`,
  `${I(1)}@State private var shown = false`,
  `${I(1)}@State private var taps = 0`,
  `${I(1)}@Environment(\\.accessibilityReduceMotion) private var reduceMotion`,
  `${I(1)}@Environment(\\.colorScheme) private var scheme`,
  "",
  `${I(1)}private var current: Double { showsAlt ? (altAmount ?? amount) : amount }`,
  `${I(1)}/// The card surfaces (top, bottom) when the panel isn't a colour block, per appearance.`,
  `${I(1)}private var top: Color { scheme == .dark ? Color(red: 0.078, green: 0.078, blue: 0.086) : .white }`,
  `${I(1)}private var bottom: Color { scheme == .dark ? Color(red: 0.11, green: 0.11, blue: 0.12) : Color(red: 0.925, green: 0.922, blue: 0.902) }`,
  "",
  `${I(1)}var body: some View {`,
  `${I(2)}VStack(spacing: 0) {`,
  `${I(3)}VStack(spacing: 4) {`,
  `${I(4)}HStack {`,
  `${I(5)}Button { taps += 1; onSettings() } label: { Image(systemName: "gearshape.fill") }`,
  `${I(5)}Spacer()`,
  `${I(5)}HStack(spacing: 6) {`,
  `${I(6)}if dark { Circle().fill(color).frame(width: 8, height: 8) }`,
  `${I(6)}Text(title).font(.subheadline.weight(.semibold))`,
  `${I(5)}}`,
  `${I(5)}Spacer()`,
  `${I(5)}Button(action: flip) { Image(systemName: "arrow.clockwise") }`,
  `${I(4)}}`,
  `${I(4)}Spacer()`,
  `${I(4)}Button(action: flip) {`,
  `${I(5)}VStack(spacing: 4) {`,
  `${I(6)}Text(current, format: .currency(code: "USD"))`,
  `${I(7)}.font(.system(size: 54, weight: .semibold))`,
  `${I(7)}.monospacedDigit()`,
  `${I(7)}.contentTransition(.numericText(value: current))`,
  `${I(6)}Text(showsAlt ? altCaption : caption).font(.footnote)`,
  `${I(5)}}`,
  `${I(4)}}`,
  `${I(4)}Spacer()`,
  `${I(3)}}`,
  `${I(3)}.padding(20)`,
  `${I(3)}.frame(maxWidth: .infinity, maxHeight: .infinity)`,
  `${I(3)}.background(dark ? top : color)`,
  `${I(3)}VStack {`,
  `${I(4)}Spacer()`,
  `${I(4)}ZStack {`,
  `${I(5)}Circle().stroke(dark ? color.opacity(0.25) : .white.opacity(0.35), lineWidth: 4)`,
  `${I(5)}Circle()`,
  `${I(6)}.trim(from: 0, to: shown || reduceMotion ? CGFloat(daysLeft) / CGFloat(max(daysInPeriod, 1)) : 0)`,
  `${I(6)}.stroke(dark ? color : .white, style: StrokeStyle(lineWidth: 4, lineCap: .round))`,
  `${I(6)}.rotationEffect(.degrees(-90))`,
  `${I(5)}VStack(spacing: 0) {`,
  `${I(6)}Text("\\(daysLeft)").font(.title.weight(.semibold)).monospacedDigit()`,
  `${I(6)}Text(ringCaption).font(.caption2)`,
  `${I(5)}}`,
  `${I(4)}}`,
  `${I(4)}.frame(width: 104, height: 104)`,
  `${I(4)}Spacer()`,
  `${I(4)}HStack {`,
  `${I(5)}Button { taps += 1; onTransfer() } label: { Image(systemName: "arrow.left.arrow.right") }`,
  `${I(5)}Spacer()`,
  `${I(5)}Button { taps += 1; onAdd() } label: {`,
  `${I(6)}Image(systemName: "plus")`,
  `${I(7)}.font(.title2.weight(.semibold))`,
  `${I(7)}.frame(width: 58, height: 58)`,
  `${I(7)}.foregroundStyle(dark ? Color.white : Color.black.opacity(0.82))`,
  `${I(7)}.background(dark ? Color.accentColor : .white.opacity(0.3), in: .circle)`,
  `${I(5)}}`,
  `${I(5)}.accessibilityLabel("Add")`,
  `${I(5)}Spacer()`,
  `${I(5)}Button { taps += 1; onList() } label: { Image(systemName: "list.bullet") }`,
  `${I(4)}}`,
  `${I(4)}.padding(.horizontal, 28)`,
  `${I(3)}}`,
  `${I(3)}.padding(.bottom, 20)`,
  `${I(3)}.frame(maxWidth: .infinity, maxHeight: .infinity)`,
  `${I(3)}.background(dark ? bottom : color.mix(with: .black, by: 0.1))`,
  `${I(2)}}`,
  `${I(2)}.buttonStyle(BalancePanelPress())`,
  `${I(2)}.foregroundStyle(dark ? Color.primary : Color.black.opacity(0.82))`,
  `${I(2)}.clipShape(.rect(cornerRadius: dark ? 24 : 0, style: .continuous))`,
  `${I(2)}.scaleEffect(shown || reduceMotion ? 1 : 0.95)`,
  `${I(2)}.opacity(shown ? 1 : 0)`,
  `${I(2)}.frame(minHeight: height, maxHeight: .infinity)`,
  `${I(2)}.sensoryFeedback(.selection, trigger: showsAlt)`,
  `${I(2)}.sensoryFeedback(.impact(weight: .medium), trigger: taps)`,
  `${I(2)}.onAppear {`,
  `${I(3)}withAnimation(.easeOut(duration: reduceMotion ? 0.2 : 0.3)) { shown = true }`,
  `${I(2)}}`,
  `${I(1)}}`,
  "",
  `${I(1)}private func flip() {`,
  `${I(2)}guard altAmount != nil else { return }`,
  `${I(2)}withAnimation(reduceMotion ? .easeOut(duration: 0.2) : .snappy(duration: 0.25)) { showsAlt.toggle() }`,
  `${I(1)}}`,
  "}",
  "",
  "private struct BalancePanelPress: ButtonStyle {",
  `${I(1)}func makeBody(configuration: Configuration) -> some View {`,
  `${I(2)}configuration.label`,
  `${I(3)}.contentShape(.rect)`,
  `${I(3)}.opacity(configuration.isPressed ? 0.7 : 1)`,
  `${I(3)}.scaleEffect(configuration.isPressed ? 0.97 : 1)`,
  `${I(3)}.animation(.easeOut(duration: 0.12), value: configuration.isPressed)`,
  `${I(1)}}`,
  "}",
];

const colorOpts = opts(...Object.keys(BLOCK_COLORS).map((k): [string, string] => [k, k[0].toUpperCase() + k.slice(1)]));

export const balancePanel: SwiftPieceDefinition = {
  id: "balance-panel",
  name: "Balance Panel",
  category: "pieces",
  description: "A budget as one full-bleed colour panel: what's left, huge, that taps between the month and today, a ring of the days left, and round buttons to add, move and review.",
  availability: "free",
  preview: { component: "balance-panel", chunk: "app-pieces" },
  icon: "dollarsign.circle",
  concepts: ["zstack", "state", "animation"],
  interactions: ["tap", "haptic", "push", "sheet"],
  anatomy: [
    { part: "Balance", props: ["title", "amount", "caption", "altAmount", "altCaption"] },
    { part: "Days ring", props: ["daysLeft", "daysInPeriod", "ringCaption"] },
    { part: "Panel", props: ["fill", "surface", "height", "bleed"] },
    { part: "Actions", props: ["settingsLink", "transferLink", "addLink", "listLink"] },
  ],
  properties: [
    text("title", "Title", "Going out", { maxLength: 30 }),
    number("amount", "Amount left", 318.6, -99999, 999999, 0.01),
    text("caption", "Caption", "left this month", { maxLength: 30 }),
    number("altAmount", "Tap to show", 12.8, -99999, 999999, 0.01, { hint: "A second amount a tap switches to." }),
    text("altCaption", "Its caption", "left today", { maxLength: 30 }),
    number("daysLeft", "Days left", 22, 0, 366),
    number("daysInPeriod", "Days in period", 30, 1, 366),
    text("ringCaption", "Ring caption", "days left", { maxLength: 20 }),
    select("fill", "Colour", "sky", colorOpts),
    select("surface", "Surface", "dark", opts(["dark", "Card, colour accents"], ["block", "Full colour block"])),
    number("height", "Height", 640, 400, 900, 1, { group: "layout", hint: "Its smallest height; it grows to fill a screen that doesn't scroll." }),
    number("bleed", "Bleed", 0, 0, 32, 1, { group: "layout", hint: "Reaches past the screen's padding by this much." }),
    link("settingsLink", "Settings opens"),
    link("transferLink", "Transfer opens"),
    link("addLink", "Add opens"),
    link("listLink", "List opens"),
  ],
  variants: [
    { id: "sky", label: "Month left", props: { fill: "sky" } },
    { id: "sage", label: "Colour block", props: { fill: "sage", surface: "block", title: "Groceries", amount: 212.4, altAmount: 9.65 } },
    { id: "blush", label: "Overspent", props: { fill: "blush", title: "Takeaway", amount: -18.5, altAmount: -2.1, caption: "over this month", altCaption: "over today" } },
  ],
  states: [{ id: "last-day", label: "Last day", props: { daysLeft: 1 } }],
  swift: {
    imports: [],
    emit(p, ctx) {
      ctx.declare("BalancePanel", STRUCT());
      const title = s(p, "title").trim();
      const acts = ([["settingsLink", "onSettings"], ["transferLink", "onTransfer"], ["addLink", "onAdd"], ["listLink", "onList"]] as const)
        .map(([prop, label]) => {
          const a = linkAction(ctx, p[prop]);
          return a ? `${label}: ${a}` : null;
        });
      const lines = construct("BalancePanel", [
        title && `title: ${str(title)}`,
        `amount: ${dbl(n(p, "amount"))}`,
        s(p, "caption").trim() && `caption: ${str(s(p, "caption").trim())}`,
        n(p, "altAmount") !== 0 && `altAmount: ${dbl(n(p, "altAmount"))}`,
        n(p, "altAmount") !== 0 && `altCaption: ${str(s(p, "altCaption"))}`,
        n(p, "daysLeft") !== 22 && `daysLeft: ${num(n(p, "daysLeft"))}`,
        n(p, "daysInPeriod") !== 31 && `daysInPeriod: ${num(n(p, "daysInPeriod"))}`,
        s(p, "ringCaption") !== "days left" && `ringCaption: ${str(s(p, "ringCaption"))}`,
        `color: ${rgb(blockColor(s(p, "fill")))}`,
        n(p, "height") !== 640 && `height: ${num(n(p, "height"))}`,
        s(p, "surface") !== "block" && "dark: true",
        ...acts,
      ]);
      const bleed = n(p, "bleed");
      return { lines: modifiers(lines, [bleed > 0 && `padding(.horizontal, -${num(bleed)})`]) };
    },
  },
};
