// Camera Viewfinder: a full-screen camera view with framing corners, a hint card and either a
// shutter or a continue button. With a readout it becomes a meter: drag across the view (pointing
// the camera) and the big reading steps through its levels with a tick each, optionally over a
// scale of every level with the current one in signal red. The hint card sits at the top or bottom;
// with modes, a strip along the shutter bar switches between them and each brings its own hint.
import type { Props, SwiftPieceDefinition } from "../../core/schema.js";
import { INDENT, list, modifiers, num, str } from "../../core/swift.js";
import { ARTS } from "../native.js";
import { bool, link, number, opts, select, text } from "../shared.js";
import { arrayArg, construct, linkAction, rgb } from "./emit-link-action.js";
import { artworkGround, swiftArtwork, withArtwork } from "./artwork.js";

const s = (p: Props, k: string) => String(p[k] ?? "");
const n = (p: Props, k: string) => Number(p[k] ?? 0);
const I = (d: number) => INDENT.repeat(d);

/** Camera modes (e.g. Leaf, Whole plant, Flower) and each one's hint: "Title | text" or just the text. */
export function cameraModes(p: Props): { modes: string[]; hints: Array<{ title: string; text: string }>; start: number } {
  const modes = list(p.modes, 5);
  const raw = String(p.modeHints ?? "").split(";").map((x) => x.trim());
  const hints = modes.map((m, i) => {
    const [a = "", b] = (raw[i] ?? "").split("|").map((x) => x.trim());
    return b === undefined ? { title: m, text: a } : { title: a || m, text: b };
  });
  return { modes, hints, start: Math.max(0, Math.min(modes.length - 1, Math.round(Number(p.mode ?? 0)) || 0)) };
}

/** The levels a meter steps through, and which one it starts on (the readout, if it is one). */
export function meterLevels(p: Props): { levels: string[]; start: number } {
  const readout = s(p, "readout").trim();
  const levels = list(p.levels, 8);
  if (!readout) return { levels: [], start: 0 };
  const at = levels.indexOf(readout);
  if (at >= 0) return { levels, start: at };
  return { levels: [readout, ...levels], start: 0 };
}

const STRUCT = (): string[] => [
  "/// A camera view: framing corners, an optional meter reading you steer by dragging, a hint and a shutter or button.",
  "private struct CameraViewfinder: View {",
  `${I(1)}enum Control { case shutter, button(String) }`,
  `${I(1)}let scene: [Color]`,
  `${I(1)}/// A drawing of what the camera sees, in place of the soft stand-in shapes.`,
  `${I(1)}var picture: AnyView? = nil`,
  `${I(1)}var levels: [String] = []`,
  `${I(1)}var detail = ""`,
  `${I(1)}var hintTitle = ""`,
  `${I(1)}var hint = ""`,
  `${I(1)}var control: Control = .shutter`,
  `${I(1)}var scale = false`,
  `${I(1)}var hintOnTop = false`,
  `${I(1)}var height: CGFloat = 640`,
  `${I(1)}/// Modes along the shutter bar; each brings its own hint.`,
  `${I(1)}var modes: [String] = []`,
  `${I(1)}var modeTitles: [String] = []`,
  `${I(1)}var modeHints: [String] = []`,
  `${I(1)}var onCapture: () -> Void = {}`,
  `${I(1)}@State var level = 0`,
  `${I(1)}@State var mode = 0`,
  `${I(1)}@State private var shown = false`,
  `${I(1)}@Environment(\\.accessibilityReduceMotion) private var reduceMotion`,
  `${I(1)}@State private var flash = false`,
  `${I(1)}@State private var shots = 0`,
  `${I(1)}@State private var anchor: Int?`,
  "",
  `${I(1)}var body: some View {`,
  `${I(2)}ZStack {`,
  `${I(3)}LinearGradient(colors: scene, startPoint: .topLeading, endPoint: .bottomTrailing)`,
  `${I(3)}if let picture {`,
  `${I(4)}// The scene, a touch soft like a live preview, darkened at the top and foot for the overlays.`,
  `${I(4)}picture.blur(radius: 0.8)`,
  `${I(4)}LinearGradient(colors: [.black.opacity(0.38), .clear, .clear, .black.opacity(0.5)], startPoint: .top, endPoint: .bottom)`,
  `${I(4)}// A meter's reading sits on a soft shade, so it reads over a bright scene.`,
  `${I(4)}if !levels.isEmpty { RadialGradient(colors: [.black.opacity(0.32), .clear], center: .center, startRadius: 0, endRadius: 230) }`,
  `${I(3)}} else {`,
  `${I(4)}// Soft, out-of-focus shapes standing in for the live image.`,
  `${I(4)}Circle().fill(.black.opacity(0.22)).frame(width: 280).blur(radius: 50).offset(x: -90, y: -140)`,
  `${I(4)}Circle().fill(.white.opacity(0.25)).frame(width: 200).blur(radius: 45).offset(x: 110, y: -40)`,
  `${I(4)}Circle().fill(.black.opacity(0.18)).frame(width: 240).blur(radius: 50).offset(x: 60, y: 200)`,
  `${I(3)}}`,
  `${I(3)}ViewfinderCorners()`,
  `${I(4)}.stroke(.white, style: StrokeStyle(lineWidth: 3, lineCap: .round))`,
  `${I(4)}.padding(.horizontal, 36)`,
  `${I(4)}.padding(.top, hintOnTop ? 150 : 90)`,
  `${I(4)}.padding(.bottom, 90 + (modes.isEmpty ? 0 : 60) + (!hintOnTop && !(hintTitle.isEmpty && hint.isEmpty) ? 120 : 0))`,
  `${I(4)}.scaleEffect(shown || reduceMotion ? 1 : 0.95)`,
  `${I(4)}.opacity(shown ? 1 : 0)`,
  `${I(3)}if !levels.isEmpty {`,
  `${I(4)}VStack(spacing: 4) {`,
  `${I(5)}Text(levels[level])`,
  `${I(6)}.font(.system(size: 44, weight: .medium))`,
  `${I(6)}.contentTransition(.interpolate)`,
  `${I(5)}if !detail.isEmpty { Text(detail).font(.footnote) }`,
  `${I(5)}if scale && levels.count > 1 {`,
  `${I(6)}HStack(spacing: 6) {`,
  `${I(7)}ForEach(levels.indices, id: \\.self) { i in`,
  `${I(8)}Capsule()`,
  `${I(9)}.fill(i == level ? Color(red: 1, green: 0, blue: 0) : .white.opacity(0.35))`,
  `${I(9)}.frame(width: i == level ? 24 : 8, height: 8)`,
  `${I(7)}}`,
  `${I(6)}}`,
  `${I(6)}.padding(.top, 12)`,
  `${I(5)}}`,
  `${I(4)}}`,
  `${I(4)}.foregroundStyle(.white)`,
  `${I(4)}.shadow(color: .black.opacity(picture == nil ? 0.3 : 0.5), radius: 8)`,
  `${I(3)}}`,
  `${I(3)}VStack(spacing: 14) {`,
  `${I(4)}if hintOnTop { hintCard.padding(.top, 24) }`,
  `${I(4)}Spacer()`,
  `${I(4)}if !hintOnTop { hintCard }`,
  `${I(4)}controls`,
  `${I(3)}}`,
  `${I(3)}Color.white.opacity(flash ? 0.85 : 0).allowsHitTesting(false)`,
  `${I(2)}}`,
  `${I(2)}.frame(minHeight: height, maxHeight: .infinity)`,
  `${I(2)}.clipped()`,
  `${I(2)}.contentShape(.rect)`,
  `${I(2)}.gesture(meter, including: levels.count > 1 ? .all : .subviews)`,
  `${I(2)}.sensoryFeedback(.selection, trigger: level)`,
  `${I(2)}.sensoryFeedback(.selection, trigger: mode)`,
  `${I(2)}.onAppear { withAnimation(.easeOut(duration: reduceMotion ? 0.2 : 0.28)) { shown = true } }`,
  `${I(2)}.sensoryFeedback(.impact(weight: .medium), trigger: shots)`,
  `${I(1)}}`,
  "",
  `${I(1)}@ViewBuilder private var hintCard: some View {`,
  `${I(2)}let title = modes.isEmpty ? hintTitle : (mode < modeTitles.count ? modeTitles[mode] : modes[mode])`,
  `${I(2)}let text = modes.isEmpty ? hint : (mode < modeHints.count && !modeHints[mode].isEmpty ? modeHints[mode] : hint)`,
  `${I(2)}if !title.isEmpty || !text.isEmpty {`,
  `${I(3)}VStack(alignment: .leading, spacing: 4) {`,
  `${I(4)}Text(title).font(.subheadline.weight(.semibold))`,
  `${I(4)}Text(text).font(.caption).opacity(0.8)`,
  `${I(3)}}`,
  `${I(3)}.id(mode)`,
  `${I(3)}.transition(.opacity)`,
  `${I(3)}.foregroundStyle(.white)`,
  `${I(3)}.frame(maxWidth: .infinity, alignment: .leading)`,
  `${I(3)}.padding(16)`,
  `${I(3)}.background(.black.opacity(0.35), in: .rect(cornerRadius: 18))`,
  `${I(3)}.padding(.horizontal, 20)`,
  `${I(2)}}`,
  `${I(1)}}`,
  "",
  `${I(1)}@ViewBuilder private var modeStrip: some View {`,
  `${I(2)}if !modes.isEmpty {`,
  `${I(3)}HStack(spacing: 24) {`,
  `${I(4)}ForEach(modes.indices, id: \\.self) { i in`,
  `${I(5)}Button {`,
  `${I(6)}withAnimation(.easeOut(duration: 0.2)) { mode = i }`,
  `${I(5)}} label: {`,
  `${I(6)}Text(modes[i])`,
  `${I(7)}.font(.subheadline.weight(.semibold))`,
  `${I(7)}.foregroundStyle(i == mode ? Color(red: 1, green: 0, blue: 0) : .white.opacity(0.6))`,
  `${I(7)}.frame(minHeight: 44)`,
  `${I(5)}}`,
  `${I(5)}.buttonStyle(.plain)`,
  `${I(5)}.accessibilityAddTraits(i == mode ? .isSelected : [])`,
  `${I(4)}}`,
  `${I(3)}}`,
  `${I(3)}.frame(maxWidth: .infinity)`,
  `${I(3)}.contentShape(.rect)`,
  `${I(3)}.gesture(DragGesture(minimumDistance: 20).onEnded { g in`,
  `${I(4)}let step = g.translation.width < 0 ? 1 : -1`,
  `${I(4)}withAnimation(.easeOut(duration: 0.2)) { mode = min(max(mode + step, 0), modes.count - 1) }`,
  `${I(3)}})`,
  `${I(2)}}`,
  `${I(1)}}`,
  "",
  `${I(1)}@ViewBuilder private var controls: some View {`,
  `${I(2)}switch control {`,
  `${I(2)}case .shutter:`,
  `${I(3)}VStack(spacing: 8) {`,
  `${I(3)}modeStrip`,
  `${I(3)}ZStack {`,
  `${I(4)}Button(action: capture) {`,
  `${I(5)}Circle()`,
  `${I(6)}.strokeBorder(.white, lineWidth: 4)`,
  `${I(6)}.frame(width: 72, height: 72)`,
  `${I(4)}}`,
  `${I(4)}.buttonStyle(ShutterPress())`,
  `${I(4)}HStack {`,
  `${I(5)}Spacer()`,
  `${I(5)}Image(systemName: "photo.on.rectangle")`,
  `${I(6)}.font(.title3)`,
  `${I(6)}.foregroundStyle(.white)`,
  `${I(4)}}`,
  `${I(3)}}`,
  `${I(3)}}`,
  `${I(3)}.padding(.horizontal, 28)`,
  `${I(3)}.padding(.vertical, 16)`,
  `${I(3)}.frame(maxWidth: .infinity)`,
  `${I(3)}// Over a drawn scene the bar goes nearly black, as a camera's does, so the modes stay legible.`,
  `${I(3)}.background(.black.opacity(picture == nil ? 0.45 : 0.78))`,
  `${I(2)}case .button(let title):`,
  `${I(3)}modeStrip`,
  `${I(3)}Button(title, action: capture)`,
  `${I(4)}.buttonStyle(.borderedProminent)`,
  `${I(4)}.controlSize(.large)`,
  `${I(4)}.buttonBorderShape(.capsule)`,
  `${I(4)}.padding(.horizontal, 20)`,
  `${I(4)}.padding(.bottom, 24)`,
  `${I(2)}}`,
  `${I(1)}}`,
  "",
  `${I(1)}private var meter: some Gesture {`,
  `${I(2)}DragGesture(minimumDistance: 8)`,
  `${I(3)}.onChanged { value in`,
  `${I(4)}let start = anchor ?? level`,
  `${I(4)}anchor = start`,
  `${I(4)}let steps = Int((value.translation.width / 70).rounded())`,
  `${I(4)}let next = min(max(start + steps, 0), levels.count - 1)`,
  `${I(4)}if next != level { withAnimation(.snappy) { level = next } }`,
  `${I(3)}}`,
  `${I(3)}.onEnded { _ in anchor = nil }`,
  `${I(1)}}`,
  "",
  `${I(1)}private func capture() {`,
  `${I(2)}shots += 1`,
  `${I(2)}withAnimation(.easeOut(duration: 0.08)) { flash = true }`,
  `${I(2)}withAnimation(.easeIn(duration: 0.35).delay(0.08)) { flash = false }`,
  `${I(2)}onCapture()`,
  `${I(1)}}`,
  "}",
  "",
  "/// The shutter: its inner disc dips under a finger, like the Camera app's.",
  "private struct ShutterPress: ButtonStyle {",
  `${I(1)}func makeBody(configuration: Configuration) -> some View {`,
  `${I(2)}configuration.label`,
  `${I(3)}.background(Circle().fill(.white.opacity(0.9)).padding(7).scaleEffect(configuration.isPressed ? 0.9 : 1))`,
  `${I(3)}.animation(.easeOut(duration: configuration.isPressed ? 0.1 : 0.2), value: configuration.isPressed)`,
  `${I(1)}}`,
  "}",
  "",
  "/// Four corner brackets, the framing marks of a camera view.",
  "private struct ViewfinderCorners: Shape {",
  `${I(1)}func path(in rect: CGRect) -> Path {`,
  `${I(2)}let arm: CGFloat = 26`,
  `${I(2)}var path = Path()`,
  `${I(2)}for (x, y, dx, dy) in [(rect.minX, rect.minY, arm, arm), (rect.maxX, rect.minY, -arm, arm), (rect.minX, rect.maxY, arm, -arm), (rect.maxX, rect.maxY, -arm, -arm)] {`,
  `${I(3)}path.move(to: CGPoint(x: x, y: y + dy))`,
  `${I(3)}path.addLine(to: CGPoint(x: x, y: y))`,
  `${I(3)}path.addLine(to: CGPoint(x: x + dx, y: y))`,
  `${I(2)}}`,
  `${I(2)}return path`,
  `${I(1)}}`,
  "}",
];

const artOpts = withArtwork(opts(...Object.entries(ARTS).map(([id, a]): [string, string] => [id, a.label])));

export const cameraViewfinder: SwiftPieceDefinition = {
  id: "camera-viewfinder",
  name: "Camera Viewfinder",
  category: "pieces",
  description: "A full-screen camera view with framing corners, a hint card and a shutter or button. Give it a readout and it becomes a meter: drag across the view and the reading steps through its levels.",
  availability: "free",
  preview: { component: "camera-viewfinder", chunk: "app-pieces" },
  icon: "camera",
  concepts: ["zstack", "gesture", "state"],
  interactions: ["tap", "drag", "haptic", "push"],
  anatomy: [
    { part: "Scene", props: ["art", "height", "bleed"] },
    { part: "Meter", props: ["readout", "detail", "levels", "scale"] },
    { part: "Hint", props: ["hintTitle", "hint", "hintAt"] },
    { part: "Control", props: ["control", "buttonTitle", "link"] },
  ],
  properties: [
    select("art", "Scene", "graphite", artOpts, { hint: "Stands in for the live camera image." }),
    text("readout", "Reading", "", { maxLength: 24, hint: "A big reading over the view. Leave empty for a plain camera." }),
    text("detail", "Reading detail", "", { maxLength: 40, when: { prop: "readout", notEquals: [""] } }),
    text("levels", "Levels", "Dim, Bright shade, Filtered sun, Direct sun", { maxLength: 120, hint: "What dragging steps through.", when: { prop: "readout", notEquals: [""] } }),
    bool("scale", "Level scale", false, { hint: "A row of every level under the reading, the current one in signal red.", when: { prop: "readout", notEquals: [""] } }),
    text("hintTitle", "Hint title", "Frame it", { maxLength: 40 }),
    text("hint", "Hint", "Get the whole subject inside the corners, then take the photo.", { maxLength: 120 }),
    select("hintAt", "Hint position", "bottom", opts(["bottom", "Bottom"], ["top", "Top"])),
    text("modes", "Modes", "", { maxLength: 80, hint: "Modes along the shutter bar, e.g. Leaf, Whole plant, Flower. Tap or swipe to switch; each brings its own hint." }),
    text("modeHints", "Mode hints", "", { maxLength: 400, hint: "One hint per mode, separated by semicolons: the text, or Title | text.", when: { prop: "modes", notEquals: [""] } }),
    number("mode", "Starting mode", 0, 0, 4, 1, { when: { prop: "modes", notEquals: [""] } }),
    select("control", "Control", "shutter", opts(["shutter", "Shutter"], ["button", "Button"])),
    text("buttonTitle", "Button title", "Next", { maxLength: 24, when: { prop: "control", equals: ["button"] } }),
    number("height", "Height", 640, 320, 900, 1, { group: "layout", hint: "Its smallest height; it grows to fill a screen that doesn't scroll." }),
    number("bleed", "Bleed", 0, 0, 32, 1, { group: "layout" }),
    link("link", "Capture opens"),
  ],
  variants: [
    { id: "identify", label: "Identify", props: { art: "graphite", hintTitle: "Frame it", hint: "Get the whole subject inside the corners, then take the photo.", hintAt: "top", modes: "Leaf, Whole plant, Flower", modeHints: "One leaf, flat and sharp, filling the corners.; Leaves, stem and pot inside the corners.; The open flower in the middle, petals in focus.", mode: 1 } },
    { id: "meter", label: "Light meter", props: { art: "graphite", readout: "Bright shade", detail: "Window faces north", hintTitle: "Light check", hint: "Hold the phone where it will stand, screen to the window.", control: "button", buttonTitle: "Save spot", scale: true } },
    { id: "scan", label: "Document", props: { art: "graphite", hintTitle: "Receipt", hint: "Hold steady until the edges line up.", height: 480 } },
  ],
  states: [{ id: "bare", label: "No hint", props: { hintTitle: "", hint: "" } }],
  swift: {
    imports: [],
    emit(p, ctx) {
      ctx.declare("CameraViewfinder", STRUCT());
      const picture = swiftArtwork(ctx, s(p, "art"));
      const stops = picture ? [artworkGround(s(p, "art")), artworkGround(s(p, "art"))] : (ARTS[s(p, "art")] ?? ARTS.graphite).stops;
      const { levels, start } = meterLevels(p);
      const cm = cameraModes(p);
      const action = linkAction(ctx, p.link);
      const button = s(p, "control") === "button";
      const lines = construct("CameraViewfinder", [
        `scene: [${stops.map(rgb).join(", ")}]`,
        picture && `picture: AnyView(${picture})`,
        levels.length > 0 && arrayArg("levels", levels.map(str)),
        levels.length > 0 && s(p, "detail").trim() && `detail: ${str(s(p, "detail").trim())}`,
        s(p, "hintTitle").trim() && `hintTitle: ${str(s(p, "hintTitle").trim())}`,
        s(p, "hint").trim() && `hint: ${str(s(p, "hint").trim())}`,
        button && `control: .button(${str(s(p, "buttonTitle") || "Next")})`,
        levels.length > 1 && p.scale === true && "scale: true",
        s(p, "hintAt") === "top" && "hintOnTop: true",
        n(p, "height") !== 640 && `height: ${num(n(p, "height"))}`,
        cm.modes.length > 0 && arrayArg("modes", cm.modes.map(str)),
        cm.modes.length > 0 && arrayArg("modeTitles", cm.hints.map((h) => str(h.title))),
        cm.modes.length > 0 && arrayArg("modeHints", cm.hints.map((h) => str(h.text))),
        action && `onCapture: ${action}`,
        start > 0 && `level: ${start}`,
        cm.modes.length > 0 && cm.start > 0 && `mode: ${cm.start}`,
      ]);
      const bleed = n(p, "bleed");
      return { lines: modifiers(lines, [bleed > 0 && `padding(.horizontal, -${num(bleed)})`]) };
    },
  },
};
