// Color Block List: full-bleed flat colour blocks, one per item, each a title and a value. Rows you
// tap to open and swipe left to reveal edit and delete, or tiles side by side. The envelope look of
// a budget list, a pair of accounts to move money between, a board of balances.
import type { Props, SwiftPieceDefinition } from "../../core/schema.js";
import { INDENT, list, modifiers, num, str } from "../../core/swift.js";
import { bool, link, number, opts, select, text } from "../shared.js";
import { arrayArg, construct, linkAction, rgb } from "./emit-link-action.js";
import { own } from "../../core/own.js";

const s = (p: Props, k: string) => String(p[k] ?? "");
const n = (p: Props, k: string) => Number(p[k] ?? 0);

/** Flat block colours, bright enough to carry dark text. */
export const BLOCK_COLORS: Record<string, string> = {
  // The Swift Pieces house blocks and sweep.
  sky: "#9CC2FF", sage: "#A9DCB7", blush: "#FF8FB8", butter: "#FFD976", lilac: "#CDB8FF", sand: "#E9D5B3", ember: "#FF7A3C", azure: "#4D8DFF",
  // Older names, kept so saved builds still read.
  mint: "#84E8A6", coral: "#E9695A", peach: "#FFB38A", slate: "#AFC0CF",
};
export const blockColor = (id: string) => own(BLOCK_COLORS, id) ?? BLOCK_COLORS.sky;

const ITEMS = "Groceries: $182.40, Going out: $64.10, Transport: $38.75, Gifts: $120.00, Home: $246.90";

export type Block = { eyebrow: string; title: string; value: string; color: string };

/** "Title: value" items with a colour and an eyebrow each, both cycling. */
export function parseBlocks(p: Props): Block[] {
  const items = list(p.items, 8);
  const colors = list(p.colors, 8).filter((c) => BLOCK_COLORS[c]);
  const eyebrows = list(p.eyebrows, 8);
  return (items.length ? items : ["Item"]).map((item, i) => {
    const at = item.lastIndexOf(":");
    return {
      title: (at > 0 ? item.slice(0, at) : item).trim(),
      value: at > 0 ? item.slice(at + 1).trim() : "",
      color: colors.length ? colors[i % colors.length] : Object.keys(BLOCK_COLORS)[i % 6],
      eyebrow: eyebrows[i] ?? "",
    };
  });
}

const STRUCTS = (): string[] => [
  "private struct ColorBlock: Identifiable {",
  `${INDENT}let id: Int`,
  `${INDENT}var eyebrow = ""`,
  `${INDENT}let title: String`,
  `${INDENT}let value: String`,
  `${INDENT}let color: Color`,
  "}",
  "",
  "/// Flat colour blocks: rows that open on tap and swipe left for edit and delete, or tiles side by side.",
  "private struct ColorBlockList: View {",
  `${INDENT}enum Layout { case list, tiles }`,
  `${INDENT}@State var blocks: [ColorBlock]`,
  `${INDENT}var layout: Layout = .list`,
  `${INDENT}var height: CGFloat = 64`,
  `${INDENT}var header = ""`,
  `${INDENT}var headerValue = ""`,
  `${INDENT}var swipeActions = true`,
  `${INDENT}var gap: CGFloat = 0`,
  `${INDENT}var radius: CGFloat = 0`,
  `${INDENT}var selectable = false`,
  `${INDENT}var onSelect: () -> Void = {}`,
  `${INDENT}@State private var taps = 0`,
  `${INDENT}@State private var picked: Set<Int> = []`,
  `${INDENT}@State private var appeared = false`,
  `${INDENT}@Environment(\\.accessibilityReduceMotion) private var reduceMotion`,
  "",
  `${INDENT}var body: some View {`,
  `${INDENT}${INDENT}VStack(spacing: 0) {`,
  `${INDENT}${INDENT}${INDENT}if !header.isEmpty {`,
  `${INDENT}${INDENT}${INDENT}${INDENT}HStack {`,
  `${INDENT}${INDENT}${INDENT}${INDENT}${INDENT}Text(header)`,
  `${INDENT}${INDENT}${INDENT}${INDENT}${INDENT}Spacer()`,
  `${INDENT}${INDENT}${INDENT}${INDENT}${INDENT}Text(headerValue)`,
  `${INDENT}${INDENT}${INDENT}${INDENT}}`,
  `${INDENT}${INDENT}${INDENT}${INDENT}.font(.caption)`,
  `${INDENT}${INDENT}${INDENT}${INDENT}.foregroundStyle(.secondary)`,
  `${INDENT}${INDENT}${INDENT}${INDENT}.padding(.horizontal, 16)`,
  `${INDENT}${INDENT}${INDENT}${INDENT}.padding(.vertical, 8)`,
  `${INDENT}${INDENT}${INDENT}${INDENT}.background(Color(.secondarySystemBackground))`,
  `${INDENT}${INDENT}${INDENT}}`,
  `${INDENT}${INDENT}${INDENT}if layout == .tiles {`,
  `${INDENT}${INDENT}${INDENT}${INDENT}HStack(spacing: gap) {`,
  `${INDENT}${INDENT}${INDENT}${INDENT}${INDENT}ForEach(blocks) { block in`,
  `${INDENT}${INDENT}${INDENT}${INDENT}${INDENT}${INDENT}ColorBlockTile(block: block, selectable: selectable, picked: picked.contains(block.id)) {`,
  `${INDENT}${INDENT}${INDENT}${INDENT}${INDENT}${INDENT}${INDENT}if selectable {`,
  `${INDENT}${INDENT}${INDENT}${INDENT}${INDENT}${INDENT}${INDENT}${INDENT}withAnimation(.easeOut(duration: 0.15)) { if picked.contains(block.id) { picked.remove(block.id) } else { picked.insert(block.id) } }`,
  `${INDENT}${INDENT}${INDENT}${INDENT}${INDENT}${INDENT}${INDENT}} else { taps += 1; onSelect() }`,
  `${INDENT}${INDENT}${INDENT}${INDENT}${INDENT}${INDENT}}`,
  `${INDENT}${INDENT}${INDENT}${INDENT}${INDENT}${INDENT}${INDENT}.clipShape(.rect(cornerRadius: radius))`,
  `${INDENT}${INDENT}${INDENT}${INDENT}${INDENT}${INDENT}${INDENT}.modifier(BlockEntrance(shown: appeared, index: block.id, still: reduceMotion))`,
  `${INDENT}${INDENT}${INDENT}${INDENT}${INDENT}}`,
  `${INDENT}${INDENT}${INDENT}${INDENT}}`,
  `${INDENT}${INDENT}${INDENT}${INDENT}.frame(height: height)`,
  `${INDENT}${INDENT}${INDENT}} else {`,
  `${INDENT}${INDENT}${INDENT}${INDENT}VStack(spacing: gap) {`,
  `${INDENT}${INDENT}${INDENT}${INDENT}ForEach(blocks) { block in`,
  `${INDENT}${INDENT}${INDENT}${INDENT}${INDENT}ColorBlockRow(block: block, height: height, swipeActions: swipeActions) {`,
  `${INDENT}${INDENT}${INDENT}${INDENT}${INDENT}${INDENT}taps += 1`,
  `${INDENT}${INDENT}${INDENT}${INDENT}${INDENT}${INDENT}onSelect()`,
  `${INDENT}${INDENT}${INDENT}${INDENT}${INDENT}} onDelete: {`,
  `${INDENT}${INDENT}${INDENT}${INDENT}${INDENT}${INDENT}withAnimation(.snappy) { blocks.removeAll { $0.id == block.id } }`,
  `${INDENT}${INDENT}${INDENT}${INDENT}${INDENT}}`,
  `${INDENT}${INDENT}${INDENT}${INDENT}${INDENT}.clipShape(.rect(cornerRadius: radius))`,
  `${INDENT}${INDENT}${INDENT}${INDENT}${INDENT}.modifier(BlockEntrance(shown: appeared, index: block.id, still: reduceMotion))`,
  `${INDENT}${INDENT}${INDENT}${INDENT}${INDENT}.transition(.move(edge: .leading).combined(with: .opacity))`,
  `${INDENT}${INDENT}${INDENT}${INDENT}}`,
  `${INDENT}${INDENT}${INDENT}${INDENT}}`,
  `${INDENT}${INDENT}${INDENT}}`,
  `${INDENT}${INDENT}}`,
  `${INDENT}${INDENT}.onAppear { appeared = true }`,
  `${INDENT}${INDENT}.sensoryFeedback(.impact(weight: .light), trigger: taps)`,
  `${INDENT}${INDENT}.sensoryFeedback(.warning, trigger: blocks.count)`,
  `${INDENT}${INDENT}.sensoryFeedback(.selection, trigger: picked)`,
  `${INDENT}}`,
  "}",
  "",
  "/// Blocks ease in from 0.95 with a fade, 40 ms apart (capped at 8), as the list appears.",
  "private struct BlockEntrance: ViewModifier {",
  `${INDENT}let shown: Bool`,
  `${INDENT}let index: Int`,
  `${INDENT}let still: Bool`,
  `${INDENT}func body(content: Content) -> some View {`,
  `${INDENT}${INDENT}content`,
  `${INDENT}${INDENT}${INDENT}.opacity(shown ? 1 : 0)`,
  `${INDENT}${INDENT}${INDENT}.scaleEffect(shown || still ? 1 : 0.95)`,
  `${INDENT}${INDENT}${INDENT}.animation(.easeOut(duration: still ? 0.2 : 0.3).delay(still ? 0 : Double(min(index, 7)) * 0.04), value: shown)`,
  `${INDENT}}`,
  "}",
  "",
  "private struct ColorBlockTile: View {",
  `${INDENT}let block: ColorBlock`,
  `${INDENT}var selectable = false`,
  `${INDENT}var picked = false`,
  `${INDENT}let onTap: () -> Void`,
  "",
  `${INDENT}var body: some View {`,
  `${INDENT}${INDENT}Button(action: onTap) {`,
  `${INDENT}${INDENT}${INDENT}VStack(alignment: .leading, spacing: 2) {`,
  `${INDENT}${INDENT}${INDENT}${INDENT}HStack(alignment: .top) {`,
  `${INDENT}${INDENT}${INDENT}${INDENT}${INDENT}if !block.eyebrow.isEmpty {`,
  `${INDENT}${INDENT}${INDENT}${INDENT}${INDENT}${INDENT}Text(block.eyebrow).font(.caption).opacity(0.7)`,
  `${INDENT}${INDENT}${INDENT}${INDENT}${INDENT}}`,
  `${INDENT}${INDENT}${INDENT}${INDENT}${INDENT}Spacer(minLength: 0)`,
  `${INDENT}${INDENT}${INDENT}${INDENT}${INDENT}if selectable {`,
  `${INDENT}${INDENT}${INDENT}${INDENT}${INDENT}${INDENT}Image(systemName: picked ? "checkmark.circle.fill" : "plus.circle.fill")`,
  `${INDENT}${INDENT}${INDENT}${INDENT}${INDENT}${INDENT}${INDENT}.font(.title3)`,
  `${INDENT}${INDENT}${INDENT}${INDENT}${INDENT}${INDENT}${INDENT}.contentTransition(.symbolEffect(.replace))`,
  `${INDENT}${INDENT}${INDENT}${INDENT}${INDENT}}`,
  `${INDENT}${INDENT}${INDENT}${INDENT}}`,
  `${INDENT}${INDENT}${INDENT}${INDENT}Spacer(minLength: 0)`,
  `${INDENT}${INDENT}${INDENT}${INDENT}Text(block.value).font(.title2.weight(.medium)).monospacedDigit()`,
  `${INDENT}${INDENT}${INDENT}${INDENT}Text(block.title).font(.caption2).opacity(0.7)`,
  `${INDENT}${INDENT}${INDENT}}`,
  `${INDENT}${INDENT}${INDENT}.foregroundStyle(.black.opacity(0.82))`,
  `${INDENT}${INDENT}${INDENT}.padding(20)`,
  `${INDENT}${INDENT}${INDENT}.frame(maxWidth: .infinity, maxHeight: .infinity, alignment: .leading)`,
  `${INDENT}${INDENT}${INDENT}.background {`,
  `${INDENT}${INDENT}${INDENT}${INDENT}VStack(spacing: 0) {`,
  `${INDENT}${INDENT}${INDENT}${INDENT}${INDENT}block.color.mix(with: .white, by: 0.14)`,
  `${INDENT}${INDENT}${INDENT}${INDENT}${INDENT}block.color`,
  `${INDENT}${INDENT}${INDENT}${INDENT}}`,
  `${INDENT}${INDENT}${INDENT}}`,
  `${INDENT}${INDENT}}`,
  `${INDENT}${INDENT}.buttonStyle(ColorBlockPress())`,
  `${INDENT}${INDENT}.accessibilityAddTraits(picked ? .isSelected : [])`,
  `${INDENT}}`,
  "}",
  "",
  "/// Rows answer a press with a highlight, not a scale.",
  "private struct ColorBlockRowPress: ButtonStyle {",
  `${INDENT}func makeBody(configuration: Configuration) -> some View {`,
  `${INDENT}${INDENT}configuration.label`,
  `${INDENT}${INDENT}${INDENT}.overlay(Color.black.opacity(configuration.isPressed ? 0.08 : 0).allowsHitTesting(false))`,
  `${INDENT}${INDENT}${INDENT}.animation(.easeOut(duration: 0.12), value: configuration.isPressed)`,
  `${INDENT}}`,
  "}",
  "",
  "private struct ColorBlockPress: ButtonStyle {",
  `${INDENT}func makeBody(configuration: Configuration) -> some View {`,
  `${INDENT}${INDENT}configuration.label`,
  `${INDENT}${INDENT}${INDENT}.scaleEffect(configuration.isPressed ? 0.97 : 1)`,
  `${INDENT}${INDENT}${INDENT}.animation(.easeOut(duration: 0.12), value: configuration.isPressed)`,
  `${INDENT}}`,
  "}",
  "",
  "private struct ColorBlockRow: View {",
  `${INDENT}let block: ColorBlock`,
  `${INDENT}let height: CGFloat`,
  `${INDENT}let swipeActions: Bool`,
  `${INDENT}let onSelect: () -> Void`,
  `${INDENT}let onDelete: () -> Void`,
  `${INDENT}@State private var offset: CGFloat = 0`,
  `${INDENT}@State private var revealed = false`,
  `${INDENT}private let reveal: CGFloat = 132`,
  "",
  `${INDENT}var body: some View {`,
  `${INDENT}${INDENT}ZStack(alignment: .trailing) {`,
  `${INDENT}${INDENT}${INDENT}if swipeActions {`,
  `${INDENT}${INDENT}${INDENT}${INDENT}HStack(spacing: 0) {`,
  `${INDENT}${INDENT}${INDENT}${INDENT}${INDENT}Button { settle(open: false) } label: {`,
  `${INDENT}${INDENT}${INDENT}${INDENT}${INDENT}${INDENT}Image(systemName: "pencil").frame(width: reveal / 2, height: height)`,
  `${INDENT}${INDENT}${INDENT}${INDENT}${INDENT}}`,
  `${INDENT}${INDENT}${INDENT}${INDENT}${INDENT}Button(role: .destructive, action: onDelete) {`,
  `${INDENT}${INDENT}${INDENT}${INDENT}${INDENT}${INDENT}Image(systemName: "trash").frame(width: reveal / 2, height: height)`,
  `${INDENT}${INDENT}${INDENT}${INDENT}${INDENT}}`,
  `${INDENT}${INDENT}${INDENT}${INDENT}}`,
  `${INDENT}${INDENT}${INDENT}${INDENT}.font(.title3)`,
  `${INDENT}${INDENT}${INDENT}${INDENT}.foregroundStyle(.primary)`,
  `${INDENT}${INDENT}${INDENT}}`,
  `${INDENT}${INDENT}${INDENT}Button { revealed ? settle(open: false) : onSelect() } label: {`,
  `${INDENT}${INDENT}${INDENT}${INDENT}HStack(spacing: 12) {`,
  `${INDENT}${INDENT}${INDENT}${INDENT}${INDENT}VStack(alignment: .leading, spacing: 2) {`,
  `${INDENT}${INDENT}${INDENT}${INDENT}${INDENT}${INDENT}if !block.eyebrow.isEmpty {`,
  `${INDENT}${INDENT}${INDENT}${INDENT}${INDENT}${INDENT}${INDENT}Text(block.eyebrow).font(.caption2).opacity(0.7)`,
  `${INDENT}${INDENT}${INDENT}${INDENT}${INDENT}${INDENT}}`,
  `${INDENT}${INDENT}${INDENT}${INDENT}${INDENT}${INDENT}Text(block.title).font(.subheadline.weight(.semibold))`,
  `${INDENT}${INDENT}${INDENT}${INDENT}${INDENT}}`,
  `${INDENT}${INDENT}${INDENT}${INDENT}${INDENT}Spacer()`,
  `${INDENT}${INDENT}${INDENT}${INDENT}${INDENT}Text(block.value).font(.title3).monospacedDigit()`,
  `${INDENT}${INDENT}${INDENT}${INDENT}}`,
  `${INDENT}${INDENT}${INDENT}${INDENT}.foregroundStyle(.black.opacity(0.82))`,
  `${INDENT}${INDENT}${INDENT}${INDENT}.padding(.horizontal, 20)`,
  `${INDENT}${INDENT}${INDENT}${INDENT}.frame(maxWidth: .infinity, maxHeight: .infinity)`,
  `${INDENT}${INDENT}${INDENT}${INDENT}.background(block.color)`,
  `${INDENT}${INDENT}${INDENT}${INDENT}.contentShape(.rect)`,
  `${INDENT}${INDENT}${INDENT}}`,
  `${INDENT}${INDENT}${INDENT}.buttonStyle(ColorBlockRowPress())`,
  `${INDENT}${INDENT}${INDENT}.offset(x: offset)`,
  `${INDENT}${INDENT}${INDENT}.simultaneousGesture(swipe, including: swipeActions ? .all : .subviews)`,
  `${INDENT}${INDENT}}`,
  `${INDENT}${INDENT}.frame(height: height)`,
  `${INDENT}${INDENT}.background(Color(.systemBackground))`,
  `${INDENT}${INDENT}.clipped()`,
  `${INDENT}${INDENT}.sensoryFeedback(.selection, trigger: revealed)`,
  `${INDENT}}`,
  "",
  `${INDENT}private var swipe: some Gesture {`,
  `${INDENT}${INDENT}DragGesture(minimumDistance: 12)`,
  `${INDENT}${INDENT}${INDENT}.onChanged { value in`,
  `${INDENT}${INDENT}${INDENT}${INDENT}let start: CGFloat = revealed ? -reveal : 0`,
  `${INDENT}${INDENT}${INDENT}${INDENT}offset = min(0, start + value.translation.width)`,
  `${INDENT}${INDENT}${INDENT}}`,
  `${INDENT}${INDENT}${INDENT}.onEnded { value in`,
  `${INDENT}${INDENT}${INDENT}${INDENT}settle(open: offset + value.predictedEndTranslation.width - value.translation.width < -reveal / 2)`,
  `${INDENT}${INDENT}${INDENT}}`,
  `${INDENT}}`,
  "",
  `${INDENT}private func settle(open: Bool) {`,
  `${INDENT}${INDENT}withAnimation(.snappy) {`,
  `${INDENT}${INDENT}${INDENT}revealed = open`,
  `${INDENT}${INDENT}${INDENT}offset = open ? -reveal : 0`,
  `${INDENT}${INDENT}}`,
  `${INDENT}}`,
  "}",
];

export const colorBlockList: SwiftPieceDefinition = {
  id: "color-block-list",
  name: "Color Block List",
  category: "pieces",
  description: "Full-width flat colour blocks, a title and a value on each. Tap a row to open it, swipe it left for edit and delete, or lay the blocks side by side as tiles.",
  availability: "free",
  preview: { component: "color-block-list", chunk: "app-pieces" },
  icon: "rectangle.stack",
  concepts: ["foreach", "gesture", "state", "spring"],
  interactions: ["tap", "swipe", "haptic", "push"],
  anatomy: [
    { part: "Blocks", props: ["items", "colors", "eyebrows"] },
    { part: "Header", props: ["header", "headerValue"] },
    { part: "Layout", props: ["layout", "height", "gap", "radius", "bleed"] },
    { part: "Interaction", props: ["swipeActions", "link"] },
  ],
  properties: [
    text("items", "Blocks", ITEMS, { maxLength: 320, hint: "Title: value, separated by commas." }),
    text("colors", "Colours", "sage, sky, blush, butter, lilac", { maxLength: 120, hint: "sky, sage, blush, butter, lilac, sand, ember or azure, in turn." }),
    text("eyebrows", "Eyebrows", "", { maxLength: 120, hint: "A small line above each title, in turn." }),
    text("header", "Header", "", { maxLength: 40 }),
    text("headerValue", "Header value", "", { maxLength: 24, when: { prop: "header", notEquals: [""] } }),
    select("layout", "Layout", "list", opts(["list", "Rows"], ["tiles", "Tiles side by side"]), { group: "layout" }),
    number("height", "Block height", 64, 44, 260, 1, { group: "layout" }),
    number("gap", "Gap", 0, 0, 16, 1, { group: "layout", hint: "Space between blocks. 0 keeps them edge to edge." }),
    number("radius", "Corners", 0, 0, 28, 1, { group: "layout", hint: "Rounds each block, for a stack of cards." }),
    number("bleed", "Bleed", 0, 0, 32, 1, { group: "layout", hint: "Reaches past the screen's padding by this much, for edge-to-edge blocks." }),
    bool("swipeActions", "Swipe for actions", true, { group: "interaction", when: { prop: "layout", equals: ["list"] } }),
    bool("selectable", "Tap to pick", false, { group: "interaction", when: { prop: "layout", equals: ["tiles"] }, hint: "Tiles toggle a check (join, choose) instead of opening." }),
    link("link", "Tapping a block opens"),
  ],
  variants: [
    { id: "budgets", label: "Budgets", props: { items: ITEMS, colors: "sage, sky, blush, butter, lilac", header: "All budgets", headerValue: "$652.15" } },
    { id: "transfer", label: "From and to", props: { items: "Going out: $64.10, Groceries: $182.40", colors: "sky, blush", eyebrows: "From, To", height: 150, swipeActions: false } },
    { id: "tiles", label: "Two tiles", props: { items: "Left today: $12.80, Left this month: $318.60", colors: "sage, sky", layout: "tiles", height: 150 } },
  ],
  states: [
    { id: "one", label: "One block", props: { items: "Savings: $1,860.00", colors: "lilac" } },
    { id: "cards", label: "Rounded cards", props: { gap: 8, radius: 18 } },
    { id: "pick", label: "Tap to pick", props: { items: "7 days: Morning glass, 14 days: No soda", colors: "sky, sage", layout: "tiles", height: 128, gap: 12, radius: 16, selectable: true } },
  ],
  swift: {
    imports: [],
    emit(p, ctx) {
      ctx.declare("ColorBlockList", STRUCTS());
      const blocks = parseBlocks(p).map((b, i) => {
        const args = [`id: ${i}`, b.eyebrow && `eyebrow: ${str(b.eyebrow)}`, `title: ${str(b.title)}`, `value: ${str(b.value)}`, `color: ${rgb(blockColor(b.color))}`].filter(Boolean);
        return `ColorBlock(${args.join(", ")})`;
      });
      const action = linkAction(ctx, p.link);
      const header = s(p, "header").trim();
      const lines = construct("ColorBlockList", [
        arrayArg("blocks", blocks),
        s(p, "layout") === "tiles" && "layout: .tiles",
        n(p, "height") !== 64 && `height: ${num(n(p, "height"))}`,
        header && `header: ${str(header)}`,
        header && s(p, "headerValue").trim() && `headerValue: ${str(s(p, "headerValue").trim())}`,
        p.swipeActions === false && s(p, "layout") !== "tiles" && "swipeActions: false",
        n(p, "gap") > 0 && `gap: ${num(n(p, "gap"))}`,
        n(p, "radius") > 0 && `radius: ${num(n(p, "radius"))}`,
        p.selectable === true && s(p, "layout") === "tiles" && "selectable: true",
        action && !(p.selectable === true && s(p, "layout") === "tiles") && `onSelect: ${action}`,
      ]);
      const bleed = n(p, "bleed");
      return { lines: modifiers(lines, [bleed > 0 && `padding(.horizontal, -${num(bleed)})`]) };
    },
  },
};
