// Compare Line: this period's line against a reference (a typical day, last month, a second
// measure), with labelled guide lines, an optional legend and an optional bar strip under it with
// its own average rule. Drag across to read both series at once; the rule runs through the bars too.
import type { SwiftPieceDefinition } from "../../core/schema.js";
import { call, num } from "../../core/swift.js";
import { bool, number, opts, select, text } from "../shared.js";
import { data, numbers, swiftNums, swiftStrs, swiftTint, tint } from "./data-kit.js";

const s = (p: Record<string, unknown>, k: string) => String(p[k] ?? "");
const n = (p: Record<string, unknown>, k: string) => Number(p[k] ?? 0);

/** 6684 → "6.7K", 32 → "32". */
export const compact = (v: number) => (Math.abs(v) >= 1000 ? `${Math.round(v / 100) / 10}K` : String(Math.round(v * 10) / 10));

const SWIFT = [
  "private struct CompareLine: View {",
  "    let current: [Double]",
  "    var reference: [Double] = []",
  "    var names = [\"Now\", \"Before\"]",
  "    var labels: [String] = []",
  "    var marks: [Double] = []",
  "    var bars: [Double] = []",
  "    var barReference: [Double] = []",
  "    var average: Double?",
  "    var averageLabel = \"\"",
  "    var tint: Color = Color(red: 1, green: 0.478, blue: 0.235)",
  "    var referenceTint: Color = .gray",
  "    var smooth = true",
  "    var legend = false",
  "    /// False fits the value axis to the data instead of starting it at zero.",
  "    var fromZero = true",
  "    var height: CGFloat = 180",
  "    @State private var selected: Int?",
  "    @State private var appeared = false",
  "    @Environment(\\.accessibilityReduceMotion) private var reduceMotion",
  "",
  "    var body: some View {",
  "        VStack(alignment: .leading, spacing: 10) {",
  "            Text(readout)",
  "                .font(.footnote.weight(.semibold))",
  "                .foregroundStyle(.secondary)",
  "                .contentTransition(.numericText())",
  "            Chart {",
  "                ForEach(marks, id: \\.self) { m in",
  "                    RuleMark(y: .value(\"Mark\", m))",
  "                        .foregroundStyle(.secondary.opacity(0.4))",
  "                        .lineStyle(StrokeStyle(lineWidth: 1, dash: [3, 4]))",
  "                        .annotation(position: .trailing, alignment: .leading) {",
  "                            Text(Self.compact(m)).font(.caption).foregroundStyle(.secondary)",
  "                        }",
  "                }",
  "                ForEach(reference.indices, id: \\.self) { i in",
  "                    LineMark(x: .value(\"Day\", i), y: .value(\"Value\", reference[i]), series: .value(\"Series\", names[1]))",
  "                        .foregroundStyle(referenceTint)",
  "                        .interpolationMethod(smooth ? .monotone : .linear)",
  "                        .lineStyle(StrokeStyle(lineWidth: 2.5, lineCap: .round))",
  "                }",
  "                ForEach(current.indices, id: \\.self) { i in",
  "                    LineMark(x: .value(\"Day\", i), y: .value(\"Value\", current[i]), series: .value(\"Series\", names[0]))",
  "                        .foregroundStyle(tint)",
  "                        .interpolationMethod(smooth ? .monotone : .linear)",
  "                        .lineStyle(StrokeStyle(lineWidth: 3, lineCap: .round))",
  "                }",
  "                if let i = selected, current.indices.contains(i) {",
  "                    RuleMark(x: .value(\"Day\", i))",
  "                        .foregroundStyle(.secondary)",
  "                    PointMark(x: .value(\"Day\", i), y: .value(\"Value\", current[i]))",
  "                        .foregroundStyle(tint)",
  "                        .symbolSize(90)",
  "                }",
  "            }",
  "            .chartXSelection(value: $selected)",
  "            .chartXScale(domain: 0...max(current.count, reference.count, bars.count, 2) - 1)",
  "            .chartYScale(domain: .automatic(includesZero: fromZero))",
  "            .chartYAxis(.hidden)",
  "            .chartXAxis {",
  "                AxisMarks(values: bars.isEmpty ? Array(labels.indices) : []) { value in",
  "                    if let i = value.as(Int.self), !labels[i].isEmpty {",
  "                        AxisValueLabel(labels[i])",
  "                    }",
  "                }",
  "            }",
  "            .frame(height: height)",
  "            .mask {",
  "                Rectangle().padding(-40)",
  "                    .scaleEffect(x: appeared || reduceMotion ? 1 : 0.001, anchor: .leading)",
  "                    .animation(.timingCurve(0.22, 1, 0.36, 1, duration: 0.3), value: appeared)",
  "            }",
  "            if !bars.isEmpty {",
  "                Chart {",
  "                    ForEach(bars.indices, id: \\.self) { i in",
  "                        if i < barReference.count {",
  "                            BarMark(x: .value(\"Day\", Double(i) + 0.22), y: .value(\"Before\", barReference[i]), width: 4)",
  "                                .foregroundStyle(referenceTint.opacity(0.6))",
  "                        }",
  "                        BarMark(x: .value(\"Day\", Double(i) - 0.22), y: .value(\"Value\", bars[i]), width: 4)",
  "                            .foregroundStyle(selected == nil || selected == i ? tint : tint.opacity(0.35))",
  "                    }",
  "                    if let average {",
  "                        RuleMark(y: .value(\"Average\", average))",
  "                            .foregroundStyle(tint)",
  "                            .annotation(position: .trailing, alignment: .leading) {",
  "                                Text(averageLabel).font(.caption.weight(.semibold)).foregroundStyle(tint)",
  "                            }",
  "                    }",
  "                    if let i = selected {",
  "                        RuleMark(x: .value(\"Day\", Double(i)))",
  "                            .foregroundStyle(.secondary)",
  "                    }",
  "                }",
  "                .chartXSelection(value: Binding(get: { selected.map(Double.init) }, set: { selected = $0.map { Int($0.rounded()) } }))",
  "                .chartXScale(domain: -0.5...Double(max(current.count, bars.count, 2)) - 0.5)",
  "                .chartYAxis(.hidden)",
  "                .chartXAxis {",
  "                    AxisMarks(values: Array(labels.indices).map(Double.init)) { value in",
  "                        if let d = value.as(Double.self), labels.indices.contains(Int(d)), !labels[Int(d)].isEmpty {",
  "                            AxisValueLabel(labels[Int(d)])",
  "                        }",
  "                    }",
  "                }",
  "                .frame(height: height * 0.8)",
  "                .mask {",
  "                    Rectangle().padding(-40)",
  "                        .scaleEffect(x: appeared || reduceMotion ? 1 : 0.001, anchor: .leading)",
  "                        .animation(.timingCurve(0.22, 1, 0.36, 1, duration: 0.3), value: appeared)",
  "                }",
  "            }",
  "            if legend {",
  "                HStack(spacing: 16) {",
  "                    Label(names[0], systemImage: \"circle.fill\").foregroundStyle(tint)",
  "                    if !reference.isEmpty {",
  "                        Label(names[1], systemImage: \"circle.fill\").foregroundStyle(referenceTint)",
  "                    }",
  "                }",
  "                .font(.caption)",
  "                .frame(maxWidth: .infinity)",
  "            }",
  "        }",
  "        .opacity(appeared ? 1 : 0)",
  "        .animation(.easeOut(duration: 0.2), value: appeared)",
  "        .sensoryFeedback(.selection, trigger: selected)",
  "        .onAppear { appeared = true }",
  "    }",
  "",
  "    private var readout: String {",
  "        guard let i = selected else { return \"Drag across the chart\" }",
  "        var parts: [String] = []",
  "        if current.indices.contains(i) { parts.append(\"\\(names[0]) \\(Self.compact(current[i]))\") }",
  "        if reference.indices.contains(i) { parts.append(\"\\(names[1]) \\(Self.compact(reference[i]))\") }",
  "        return parts.joined(separator: \"  ·  \")",
  "    }",
  "",
  "    static func compact(_ v: Double) -> String {",
  "        abs(v) >= 1000 ? \"\\((v / 100).rounded() / 10)K\" : \"\\((v * 10).rounded() / 10)\".replacingOccurrences(of: \".0\", with: \"\")",
  "    }",
  "}",
];

export const compareLine: SwiftPieceDefinition = {
  id: "compare-line",
  name: "Compare Line",
  category: "pieces",
  description: "This period's line against a reference line, with labelled guides, an optional legend and an optional bar strip with an average rule. Drag to read both.",
  availability: "free",
  preview: { component: "compare-line", chunk: "app-pieces" },
  icon: "chart.line.uptrend.xyaxis",
  concepts: ["state", "gesture", "framework"],
  anatomy: [
    { part: "Lines", props: ["current", "reference", "names", "curve"] },
    { part: "Guides", props: ["marks", "labels"] },
    { part: "Bars", props: ["bars", "barReference", "average", "averageLabel"] },
    { part: "Colour", props: ["tint", "referenceTint"] },
    { part: "Legend", props: ["legend", "height", "fromZero"] },
  ],
  interactions: ["scrub", "haptic"],
  variants: [
    { id: "day", label: "Today vs typical", props: {} },
    { id: "month", label: "Month with bars", props: { current: "2, 3, 3, 5, 7, 8, 8, 9, 11, 12, 12, 14, 15, 16, 17, 18, 19, 21, 22, 25, 27, 28, 29", reference: "1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 12, 13, 14, 15, 16, 17, 18, 19, 21, 22, 24, 25, 25, 26, 26, 27", bars: "140, 60, 30, 110, 150, 0, 110, 60, 130, 0, 40, 170, 180, 0, 60, 0, 110, 0, 50, 190, 30, 140, 40", barReference: "60, 80, 20, 0, 70, 0, 0, 80, 70, 0, 0, 0, 0, 0, 40, 40, 0, 0, 70, 0, 120, 30, 20", average: 93, averageLabel: "01:33", labels: "1, , , , 5, , , , , 10, , , , , 15, , , , , 20, , Today", marks: "8, 16, 24, 32" } },
    { id: "two", label: "Two measures", props: { curve: "linear", legend: true, tint: "azure", referenceTint: "ember", names: "Pages read, Minutes listened" } },
  ],
  states: [{ id: "tall", label: "Tall", props: { height: 260 } }],
  properties: [
    data("current", "Line", "0, 0, 0, 0, 0, 20, 60, 120, 260, 480, 900, 1500, 3400, 5600, 7900, 8700, 9100, 9900, 10400, 10800, 11000, 11100, 11175", { hint: "This period, oldest first." }),
    data("reference", "Reference line", "0, 0, 0, 0, 0, 10, 40, 100, 200, 380, 700, 1300, 2200, 3100, 4200, 5000, 5600, 6000, 6300, 6500, 6600, 6650, 6684", { hint: "Empty for one line." }),
    text("names", "Series names", "Today, Typical"),
    data("labels", "Axis labels", "", { hint: "One per point; leave gaps blank." }),
    data("marks", "Guide lines", "5000, 10000", { hint: "Values to draw dashed, labelled guides at." }),
    data("bars", "Bars", "", { hint: "Optional strip under the line: one bar per point." }),
    data("barReference", "Reference bars", "", { when: { prop: "bars", notEquals: [""] } }),
    number("average", "Average rule", 0, 0, 1000000, 1, { when: { prop: "bars", notEquals: [""] }, hint: "0 hides it." }),
    text("averageLabel", "Average label", "", { when: { prop: "bars", notEquals: [""] } }),
    tint("tint", "Line colour", "ember"),
    tint("referenceTint", "Reference colour", "gray"),
    select("curve", "Curve", "smooth", opts(["smooth", "Smooth"], ["linear", "Jagged"])),
    bool("legend", "Legend", false),
    bool("fromZero", "Start at zero", true, { hint: "Off fits the line to its values, for small changes like a pulse." }),
    number("height", "Height", 180, 100, 320),
  ],
  swift: {
    imports: ["Charts"],
    emit(p, ctx) {
      ctx.import("Charts");
      ctx.declare("CompareLine", SWIFT);
      const names = s(p, "names").split(",").map((x) => x.trim());
      const labels = s(p, "labels").split(",").map((l) => l.trim());
      const reference = numbers(s(p, "reference"));
      const bars = numbers(s(p, "bars"));
      const marks = numbers(s(p, "marks"));
      const average = n(p, "average");
      return {
        lines: call("CompareLine", [
          ["current", swiftNums(numbers(s(p, "current")))],
          reference.length > 0 && ["reference", swiftNums(reference)],
          ["names", swiftStrs([names[0] || "Now", names[1] || "Before"], ctx.str)],
          labels.some(Boolean) && ["labels", swiftStrs(labels, ctx.str)],
          marks.length > 0 && ["marks", swiftNums(marks)],
          bars.length > 0 && ["bars", swiftNums(bars)],
          bars.length > 0 && numbers(s(p, "barReference")).length > 0 && ["barReference", swiftNums(numbers(s(p, "barReference")))],
          bars.length > 0 && average > 0 && ["average", num(average)],
          bars.length > 0 && average > 0 && s(p, "averageLabel").trim() && ["averageLabel", ctx.str(s(p, "averageLabel").trim())],
          ["tint", swiftTint(s(p, "tint"), "ember")],
          s(p, "referenceTint") !== "gray" && ["referenceTint", swiftTint(s(p, "referenceTint"), "gray")],
          s(p, "curve") === "linear" && ["smooth", "false"],
          p.legend === true && ["legend", "true"],
          p.fromZero === false && ["fromZero", "false"],
          n(p, "height") !== 180 && ["height", num(n(p, "height"))],
        ]),
      };
    },
  },
};
