// Focus Ring: a gentle task timer. A thick rounded arc shows the time left around a soft disc
// holding the task's symbol, the minutes and seconds sit large underneath, with "+5" to add time
// and a capsule to pause or resume. The arc eases down each second; each control taps back.
import type { SwiftPieceDefinition } from "../../core/schema.js";
import { call, num } from "../../core/swift.js";
import { bool, icon, number } from "../shared.js";
import { swiftTint, tint } from "./data-kit.js";

const s = (p: Record<string, unknown>, k: string) => String(p[k] ?? "");
const n = (p: Record<string, unknown>, k: string) => Number(p[k] ?? 0);

const SWIFT = [
  "private struct FocusRing: View {",
  "    var total: Double = 900",
  "    var symbol = \"bag\"",
  "    var tint: Color = Color(red: 1, green: 0, blue: 0)",
  "    var disc: Color = Color(red: 1, green: 0.478, blue: 0.235)",
  "    var extra: Double = 300",
  "    var size: CGFloat = 260",
  "    @State var remaining: Double = 290",
  "    @State var running = true",
  "    @Environment(\\.accessibilityReduceMotion) private var reduceMotion",
  "    @State private var shown = false",
  "",
  "    var body: some View {",
  "        VStack(spacing: 24) {",
  "            ZStack {",
  "                Circle().fill(tint.opacity(0.1))",
  "                Circle().fill(disc.opacity(0.14)).padding(size * 0.14)",
  "                Image(systemName: symbol)",
  "                    .font(.system(size: size * 0.2))",
  "                    .foregroundStyle(disc)",
  "                Circle()",
  "                    .trim(from: 0, to: shown || reduceMotion ? min(remaining / total, 1) : 0)",
  "                    .stroke(tint, style: StrokeStyle(lineWidth: size * 0.12, lineCap: .round))",
  "                    .rotationEffect(.degrees(-90))",
  "                    .padding(size * 0.06)",
  "                    .animation(.easeInOut(duration: 0.6), value: remaining)",
  "            }",
  "            .frame(width: size, height: size)",
  "            .opacity(shown ? 1 : 0)",
  "            .scaleEffect(shown || reduceMotion ? 1 : 0.95)",
  "            Text(Duration.seconds(remaining), format: .time(pattern: .minuteSecond))",
  "                .font(.system(size: 52, weight: .semibold))",
  "                .monospacedDigit()",
  "                .contentTransition(.numericText(countsDown: true))",
  "            HStack(spacing: 24) {",
  "                Button {",
  "                    withAnimation(.snappy(duration: 0.3)) { remaining = min(remaining + extra, total) }",
  "                } label: {",
  "                    Text(\"+\\(Int(extra / 60))\")",
  "                        .font(.title3)",
  "                        .frame(minWidth: 44, minHeight: 44)",
  "                }",
  "                .buttonStyle(FocusRingPress())",
  "                Button {",
  "                    running.toggle()",
  "                } label: {",
  "                    Image(systemName: running ? \"pause.fill\" : \"play.fill\")",
  "                        .font(.title3)",
  "                        .foregroundStyle(.white)",
  "                        .frame(width: 88, height: 48)",
  "                        .background(Color(red: 1, green: 0, blue: 0), in: .capsule)",
  "                        .contentTransition(.symbolEffect(.replace))",
  "                }",
  "                .buttonStyle(FocusRingPress())",
  "            }",
  "        }",
  "        .frame(maxWidth: .infinity)",
  "        .sensoryFeedback(.impact(weight: .medium), trigger: running)",
  "        .sensoryFeedback(.increase, trigger: remaining) { old, new in new > old }",
  "        .onAppear { withAnimation(.easeOut(duration: reduceMotion ? 0.2 : 0.5)) { shown = true } }",
  "        .task(id: running) {",
  "            while running && remaining > 0 {",
  "                try? await Task.sleep(for: .seconds(1))",
  "                guard running else { break }",
  "                withAnimation { remaining = max(remaining - 1, 0) }",
  "            }",
  "        }",
  "    }",
  "}",
  "",
  "private struct FocusRingPress: ButtonStyle {",
  "    func makeBody(configuration: Configuration) -> some View {",
  "        configuration.label",
  "            .scaleEffect(configuration.isPressed ? 0.97 : 1)",
  "            .opacity(configuration.isPressed ? 0.85 : 1)",
  "            .animation(.easeOut(duration: configuration.isPressed ? 0.12 : 0.2), value: configuration.isPressed)",
  "    }",
  "}",
];

export const focusRing: SwiftPieceDefinition = {
  id: "focus-ring",
  name: "Focus Ring",
  category: "pieces",
  description: "A gentle task timer: a thick rounded arc of time left around a soft disc with the task's symbol, big minutes and seconds, +5 and a pause capsule.",
  availability: "free",
  preview: { component: "focus-ring", chunk: "app-pieces" },
  icon: "timer",
  concepts: ["state", "async", "animation"],
  anatomy: [
    { part: "Time", props: ["total", "remaining", "running"] },
    { part: "Disc", props: ["symbol", "disc"] },
    { part: "Arc", props: ["tint", "size"] },
    { part: "Controls", props: ["extra"] },
  ],
  interactions: ["tap", "toggle", "spring", "haptic"],
  variants: [
    { id: "chores", label: "Chore", props: { symbol: "bag", tint: "signal", disc: "ember" } },
    { id: "study", label: "Study", props: { symbol: "book", tint: "azure", disc: "blush", total: 1500, remaining: 1320 } },
  ],
  states: [
    { id: "running", label: "Running", props: { running: true } },
    { id: "paused", label: "Paused", props: { running: false } },
  ],
  properties: [
    number("total", "Length (seconds)", 900, 60, 7200, 60),
    number("remaining", "Time left (seconds)", 290, 0, 7200, 5),
    bool("running", "Running", true),
    number("extra", "Add (seconds)", 300, 60, 900, 60),
    icon("symbol", "Symbol", "bag"),
    tint("tint", "Arc colour", "signal"),
    tint("disc", "Disc colour", "ember"),
    number("size", "Size", 260, 160, 320),
  ],
  swift: {
    imports: [],
    emit(p, ctx) {
      ctx.declare("FocusRing", SWIFT);
      return {
        lines: call("FocusRing", [
          n(p, "total") !== 900 && ["total", num(n(p, "total"))],
          ["symbol", ctx.str(ctx.symbol(s(p, "symbol") || "bag"))],
          ["tint", swiftTint(s(p, "tint"), "signal")],
          ["disc", swiftTint(s(p, "disc"), "ember")],
          n(p, "extra") !== 300 && ["extra", num(n(p, "extra"))],
          n(p, "size") !== 260 && ["size", num(n(p, "size"))],
          ["remaining", num(n(p, "remaining"))],
          p.running === false && ["running", "false"],
        ]),
      };
    },
  },
};
