// Media Row: one item of a library list (a recipe, an episode, an article) with its picture on the
// left, a title, a meta line and a short description. Tap opens it; the trailing control plays it,
// reorders it or adds it; an optional swipe removes it from a queue.
import type { Props, SwiftPieceDefinition } from "../../core/schema.js";
import { call, num } from "../../core/swift.js";
import { inkOn } from "../../core/looks.js";
import { ARTS } from "../native.js";
import { artworkGround, swiftArtwork, withArtwork } from "./artwork.js";
import { bool, icon, link, number, opts, select, text } from "../shared.js";
import { swiftHex } from "./data-kit.js";
import { linkAction } from "./emit-link-action.js";

const s = (p: Props, k: string) => String(p[k] ?? "");
const n = (p: Props, k: string) => Number(p[k] ?? 0);
const b = (p: Props, k: string) => p[k] === true;

/** Trailing controls and the SF Symbols they draw (the second is the toggled state). */
export const MEDIA_TRAILING: Record<string, { label: string; symbol: string; on?: string }> = {
  none: { label: "None", symbol: "" },
  chevron: { label: "Chevron", symbol: "chevron.right" },
  play: { label: "Play", symbol: "play.circle", on: "pause.circle.fill" },
  drag: { label: "Reorder handle", symbol: "line.3.horizontal" },
  add: { label: "Add", symbol: "plus", on: "checkmark" },
  more: { label: "More", symbol: "ellipsis" },
};

/** Meta line symbols (SF Symbol name → label). */
export const MEDIA_META: Record<string, string> = { none: "None", clock: "Clock", calendar: "Calendar", tag: "Tag", "checkmark.circle": "Played" };

const VIEW = [
  "private struct MediaRow: View {",
  "    let title: String",
  "    var eyebrow = \"\"",
  "    var meta = \"\"",
  "    var metaSymbol = \"\"",
  "    var detail = \"\"",
  "    /// The picture: a solid house fill (or a gradient stand-in for a photo) with an optional word or symbol on it.",
  "    var art: [Color] = [.orange, .red]",
  "    var ink: Color = .white",
  "    var word = \"\"",
  "    var symbol = \"\"",
  "    /// A drawing in place of the word or symbol (a plant on its pastel).",
  "    var picture: AnyView? = nil",
  "    var size: CGFloat = 64",
  "    var circle = false",
  "    var serif = false",
  "    /// 0...1 played, drawn as a thin bar under the meta line; nil hides it.",
  "    var progress: Double? = nil",
  "    var trailing = \"\"",
  "    var trailingOn = \"\"",
  "    var swipeToRemove = false",
  "    /// In a list that draws its own surface: the row stays clear while it slides.",
  "    var listed = false",
  "    var action: () -> Void = {}",
  "    /// What the trailing control opens (a player, a sheet); nil toggles it in place.",
  "    var trailingAction: (() -> Void)? = nil",
  "",
  "    @State private var isOn = false",
  "    @State private var offset: CGFloat = 0",
  "    @State private var removed = false",
  "    @State private var shown = false",
  "    @State private var tapped = 0",
  "    @Environment(\\.accessibilityReduceMotion) private var reduceMotion",
  "",
  "    var body: some View {",
  "        if !removed {",
  "            ZStack(alignment: .trailing) {",
  "                if swipeToRemove {",
  "                    Image(systemName: \"trash.fill\")",
  "                        .foregroundStyle(.white)",
  "                        .frame(width: max(0, -offset), alignment: .center)",
  "                        .frame(maxHeight: .infinity)",
  "                        .background(.red)",
  "                        .opacity(offset < 0 ? 1 : 0)",
  "                }",
  "                content",
  "                    .background(offset < 0 && !listed ? AnyShapeStyle(.background) : AnyShapeStyle(.clear))",
  "                    .offset(x: offset)",
  "                    .gesture(swipeToRemove ? swipe : nil)",
  "            }",
  "            .transition(.move(edge: .leading).combined(with: .opacity))",
  "            .opacity(shown ? 1 : 0)",
  "            .scaleEffect(shown || reduceMotion ? 1 : 0.95)",
  "            .onAppear { withAnimation(.easeOut(duration: 0.28)) { shown = true } }",
  "            .sensoryFeedback(.impact(weight: .medium), trigger: removed)",
  "            .sensoryFeedback(.impact(weight: .light), trigger: tapped)",
  "        }",
  "    }",
  "",
  "    private var content: some View {",
  "        HStack(alignment: detail.isEmpty ? .center : .top, spacing: 12) {",
  "            Button { tapped += 1; action() } label: {",
  "                HStack(alignment: detail.isEmpty ? .center : .top, spacing: 12) {",
  "                    thumbnail",
  "                    texts",
  "                    Spacer(minLength: 0)",
  "                }",
  "                .contentShape(Rectangle())",
  "            }",
  "            .buttonStyle(MediaRowHighlightStyle())",
  "            if !trailing.isEmpty {",
  "                Button {",
  "                    if let trailingAction { tapped += 1; trailingAction() } else { withAnimation(.snappy(duration: 0.25)) { isOn.toggle() } }",
  "                } label: {",
  "                    Image(systemName: isOn && !trailingOn.isEmpty ? trailingOn : trailing)",
  "                        .font(.title3)",
  "                        .contentTransition(.symbolEffect(.replace))",
  "                        .frame(width: 44, height: 44)",
  "                        .contentShape(Rectangle())",
  "                }",
  "                .buttonStyle(MediaRowPressStyle())",
  "                .foregroundStyle(trailing == \"line.3.horizontal\" || trailing == \"chevron.right\" ? AnyShapeStyle(.tertiary) : AnyShapeStyle(.tint))",
  "                .sensoryFeedback(.selection, trigger: isOn)",
  "            }",
  "        }",
  "        .padding(.vertical, 8)",
  "    }",
  "",
  "    private var texts: some View {",
  "        VStack(alignment: .leading, spacing: 2) {",
  "            if !eyebrow.isEmpty {",
  "                Text(eyebrow.uppercased())",
  "                    .font(.caption2.weight(.semibold))",
  "                    .foregroundStyle(.secondary)",
  "            }",
  "            Text(title)",
  "                .font(serif ? .system(.body, design: .serif).weight(.medium) : .subheadline.weight(.medium))",
  "                .foregroundStyle(.primary)",
  "                .multilineTextAlignment(.leading)",
  "                .lineLimit(2)",
  "            if !meta.isEmpty {",
  "                HStack(spacing: 4) {",
  "                    if !metaSymbol.isEmpty { Image(systemName: metaSymbol) }",
  "                    Text(meta)",
  "                }",
  "                .font(.caption)",
  "                .foregroundStyle(.secondary)",
  "            }",
  "            if let progress {",
  "                ProgressView(value: shown ? progress : 0)",
  "                    .animation(reduceMotion ? nil : .easeOut(duration: 0.3).delay(0.1), value: shown)",
  "                    .frame(width: 48)",
  "                    .tint(.accentColor)",
  "                    .padding(.top, 2)",
  "            }",
  "            if !detail.isEmpty {",
  "                Text(detail)",
  "                    .font(.subheadline)",
  "                    .foregroundStyle(.secondary)",
  "                    .multilineTextAlignment(.leading)",
  "                    .lineLimit(2)",
  "            }",
  "        }",
  "    }",
  "",
  "    private var thumbnail: some View {",
  "        let shape = RoundedRectangle(cornerRadius: circle ? size / 2 : size * 0.12, style: .continuous)",
  "        return LinearGradient(colors: art, startPoint: .topLeading, endPoint: .bottomTrailing)",
  "            .overlay {",
  "                if let picture {",
  "                    picture.padding(size * 0.08)",
  "                } else if !word.isEmpty {",
  "                    Text(word)",
  "                        .font(.system(size: min(size * 0.22, size * 0.84 / (CGFloat(word.split(separator: \" \").map(\\.count).max() ?? 1) * 0.66)), weight: .heavy))",
  "                        .foregroundStyle(ink)",
  "                        .multilineTextAlignment(.center)",
  "                        .lineLimit(max(1, word.split(separator: \" \").count))",
  "                        .minimumScaleFactor(0.5)",
  "                        .padding(size * 0.08)",
  "                } else if !symbol.isEmpty {",
  "                    Image(systemName: symbol)",
  "                        .font(.system(size: size * 0.36, weight: .semibold))",
  "                        .foregroundStyle(ink)",
  "                }",
  "            }",
  "            .frame(width: size, height: size)",
  "            .clipShape(shape)",
  "    }",
  "",
  "    private var swipe: some Gesture {",
  "        DragGesture(minimumDistance: 12)",
  "            .onChanged { offset = min(0, $0.translation.width) }",
  "            .onEnded { value in",
  "                let flung = value.predictedEndTranslation.width < -220",
  "                withAnimation(.interpolatingSpring(stiffness: 300, damping: 30, initialVelocity: Double(-value.velocity.width / 400))) {",
  "                    if value.translation.width < -140 || flung { removed = true } else { offset = 0 }",
  "                }",
  "            }",
  "    }",
  "}",
  "",
  "/// Rows answer a press with a highlight, not a scale.",
  "private struct MediaRowHighlightStyle: ButtonStyle {",
  "    func makeBody(configuration: Configuration) -> some View {",
  "        configuration.label",
  "            .background(",
  "                RoundedRectangle(cornerRadius: 12, style: .continuous)",
  "                    .fill(Color.primary.opacity(configuration.isPressed ? 0.06 : 0))",
  "                    .padding(-6)",
  "            )",
  "            .animation(.easeOut(duration: 0.12), value: configuration.isPressed)",
  "    }",
  "}",
  "",
  "private struct MediaRowPressStyle: ButtonStyle {",
  "    func makeBody(configuration: Configuration) -> some View {",
  "        configuration.label",
  "            .scaleEffect(configuration.isPressed ? 0.97 : 1)",
  "            .opacity(configuration.isPressed ? 0.7 : 1)",
  "            .animation(.easeOut(duration: 0.12), value: configuration.isPressed)",
  "    }",
  "}",
];

/** The house fills that are one flat colour (a picture stand-in with no gradient). */
export const SOLID_ARTS = new Set(["red", "ember", "blush", "azure", "sky", "butter", "sage", "lilac", "sand", "ink"]);
/** The ink (near-black or white) that reads on an art's fill. */
export const artInk = (id: string) => inkOn((ARTS[id] ?? ARTS.ocean).stops[1]);

const artOptions = withArtwork(opts(...Object.entries(ARTS).map(([id, a]): [string, string] => [id, a.label])));

export const mediaRow: SwiftPieceDefinition = {
  id: "media-row",
  name: "Media Row",
  category: "pieces",
  description: "A list item with its picture: title, meta line and a short description, with a play, reorder or add control and an optional swipe to remove.",
  availability: "free",
  preview: { component: "media-row", chunk: "app-pieces" },
  // It pads itself 8 top and bottom; a list adds 4. In a list it stays clear while it slides.
  list: { bare: { listed: true }, pad: 4 },
  icon: "list.bullet",
  concepts: ["state", "gesture", "spring"],
  anatomy: [
    { part: "Picture", props: ["art", "word", "symbol", "thumbSize", "thumbShape"] },
    { part: "Text", props: ["eyebrow", "title", "titleDesign", "meta", "metaIcon", "detail", "progress"] },
    { part: "Trailing control", props: ["trailing"] },
    { part: "Interaction", props: ["swipe", "link", "trailingLink"] },
  ],
  interactions: ["tap", "swipe", "toggle", "haptic"],
  variants: [
    { id: "recipe", label: "Recipe", props: { art: "butter", word: "", eyebrow: "", title: "Chickpea curry", titleDesign: "serif", meta: "40 min · Mains", metaIcon: "clock", detail: "Quick and filling: chickpeas, cauliflower and kale in a mild coconut sauce.", trailing: "none", thumbSize: 76, swipe: false } },
    { id: "episode", label: "Episode", props: { art: "azure", word: "Night Desk", eyebrow: "12 May", title: "Why cities hum after midnight", titleDesign: "default", meta: "56 min", metaIcon: "none", detail: "", trailing: "drag", thumbSize: 52, swipe: true } },
    { id: "playable", label: "Playable", props: { art: "ember", word: "Long Form", eyebrow: "Friday", title: "A week inside a lighthouse", meta: "47 min", metaIcon: "none", detail: "", trailing: "play", thumbSize: 52 } },
  ],
  states: [
    { id: "played", label: "Part played", props: { progress: 60, meta: "15 min left" } },
    { id: "plain", label: "No picture word", props: { word: "" } },
  ],
  properties: [
    select("art", "Picture", "azure", artOptions, { group: "color" }),
    text("word", "Picture word", "Night Desk", { maxLength: 24, hint: "Set on the picture like cover art. Leave empty for a plain picture." }),
    icon("symbol", "Picture symbol", "none", { hint: "Shown on the picture when it has no word." }),
    number("thumbSize", "Picture size", 64, 36, 110, 2, { group: "layout" }),
    select("thumbShape", "Picture shape", "rounded", opts(["rounded", "Rounded"], ["circle", "Circle"]), { group: "shape" }),
    text("eyebrow", "Eyebrow", "12 May", { maxLength: 40, hint: "Small uppercase line above the title (a date, a show). Leave empty for none." }),
    text("title", "Title", "Why cities hum after midnight", { maxLength: 80 }),
    select("titleDesign", "Title font", "default", opts(["default", "System"], ["serif", "Serif"]), { group: "typography" }),
    text("meta", "Meta line", "56 min", { maxLength: 60 }),
    select("metaIcon", "Meta symbol", "none", opts(...Object.entries(MEDIA_META))),
    text("detail", "Description", "", { maxLength: 160, hint: "Two lines at most. Leave empty for a compact row." }),
    number("progress", "Played", 0, 0, 100, 5, { group: "state", hint: "0 hides the bar." }),
    select("trailing", "Trailing control", "drag", opts(...Object.entries(MEDIA_TRAILING).map(([id, t]): [string, string] => [id, t.label]))),
    bool("swipe", "Swipe to remove", true, { group: "interaction" }),
    link("link", "On tap"),
    link("trailingLink", "Trailing control opens", { hint: "Leave empty to toggle it in place (play and pause, add and added)." }),
  ],
  swift: {
    imports: [],
    emit(p, ctx) {
      ctx.declare("MediaRow", VIEW);
      const picture = swiftArtwork(ctx, s(p, "art"));
      const stops = picture ? [artworkGround(s(p, "art"))] : (ARTS[s(p, "art")] ?? ARTS.ocean).stops;
      const t = MEDIA_TRAILING[s(p, "trailing")] ?? MEDIA_TRAILING.none;
      const meta = s(p, "metaIcon");
      const action = linkAction(ctx, p.link);
      const trailingAction = t.symbol ? linkAction(ctx, p.trailingLink) : null;
      const ink = artInk(s(p, "art"));
      const sym = s(p, "symbol");
      return {
        lines: call("MediaRow", [
          ["title", ctx.str(s(p, "title"))],
          s(p, "eyebrow").trim() && ["eyebrow", ctx.str(s(p, "eyebrow").trim())],
          s(p, "meta").trim() && ["meta", ctx.str(s(p, "meta").trim())],
          meta !== "none" && ["metaSymbol", ctx.str(meta)],
          s(p, "detail").trim() && ["detail", ctx.str(s(p, "detail").trim())],
          ["art", `[${(stops.length === 1 ? [stops[0], stops[0]] : stops).map((c) => swiftHex(c)).join(", ")}]`],
          ink !== "#ffffff" && ["ink", swiftHex(ink)],
          s(p, "word").trim() && ["word", ctx.str(s(p, "word").trim())],
          !s(p, "word").trim() && sym && sym !== "none" && ["symbol", ctx.str(ctx.symbol(sym))],
          picture && ["picture", `AnyView(${picture})`],
          n(p, "thumbSize") !== 64 && ["size", num(n(p, "thumbSize"))],
          s(p, "thumbShape") === "circle" && ["circle", "true"],
          s(p, "titleDesign") === "serif" && ["serif", "true"],
          n(p, "progress") > 0 && ["progress", num(n(p, "progress") / 100)],
          t.symbol && ["trailing", ctx.str(t.symbol)],
          t.on && ["trailingOn", ctx.str(t.on)],
          b(p, "swipe") && ["swipeToRemove", "true"],
          b(p, "swipe") && p.listed === true && ["listed", "true"],
          action && ["action", action],
          trailingAction && ["trailingAction", trailingAction],
        ]),
      };
    },
  },
};
