// Playback Controls: what's playing and the controls for it. Full is a player's lower half (title,
// show, a scrubber with elapsed and remaining time, skip back, play and skip forward); mini is the
// bar that rides above the tab bar and opens the full player. Time runs while it plays.
import type { Props, SwiftPieceDefinition } from "../../core/schema.js";
import { call, num } from "../../core/swift.js";
import { bool, link, number, opts, select, text } from "../shared.js";
import { swiftHex } from "./data-kit.js";
import { linkAction } from "./emit-link-action.js";
import { coverStyle } from "./cover-grid.js";

const s = (p: Props, k: string) => String(p[k] ?? "");
const n = (p: Props, k: string) => Number(p[k] ?? 0);
const b = (p: Props, k: string) => p[k] === true;

export const SKIPS = ["5", "10", "15", "30", "45", "60"];

/** 3725 → "1:02:05", 95 → "1:35". */
export function clock(total: number): string {
  const t = Math.max(0, Math.round(total));
  const h = Math.floor(t / 3600);
  const m = Math.floor((t % 3600) / 60);
  const sec = t % 60;
  return h ? `${h}:${String(m).padStart(2, "0")}:${String(sec).padStart(2, "0")}` : `${m}:${String(sec).padStart(2, "0")}`;
}

const VIEW = [
  "private struct PlaybackControls: View {",
  "    let title: String",
  "    var show = \"\"",
  "    var art: Color = .gray",
  "    var duration: Double = 3600",
  "    @State var elapsed: Double = 0",
  "    @State var playing = false",
  "    var skipBack: Double = 10",
  "    var skipForward: Double = 30",
  "    var mini = false",
  "    var tint: Color = .accentColor",
  "    var onOpen: () -> Void = {}",
  "    @State private var backTaps = 0",
  "    @State private var forwardTaps = 0",
  "    @State private var opened = 0",
  "    @State private var shown = false",
  "    @Environment(\\.accessibilityReduceMotion) private var reduceMotion",
  "",
  "    var body: some View {",
  "        Group {",
  "            if mini { miniBar } else { full }",
  "        }",
  "        .task(id: playing) {",
  "            while playing, !Task.isCancelled {",
  "                try? await Task.sleep(for: .seconds(1))",
  "                if playing { elapsed = min(duration, elapsed + 1) }",
  "            }",
  "        }",
  "        .sensoryFeedback(.impact(weight: .medium), trigger: playing)",
  "        .onAppear { withAnimation(.easeOut(duration: 0.28)) { shown = true } }",
  "    }",
  "",
  "    private var full: some View {",
  "        VStack(alignment: .leading, spacing: 18) {",
  "            VStack(alignment: .leading, spacing: 4) {",
  "                Text(title).font(.title2.weight(.bold)).lineLimit(2)",
  "                if !show.isEmpty { Text(show).font(.subheadline).foregroundStyle(.secondary) }",
  "            }",
  "            VStack(spacing: 6) {",
  "                Slider(value: $elapsed, in: 0...duration).tint(tint)",
  "                HStack {",
  "                    Text(Duration.seconds(elapsed).formatted(.time(pattern: .minuteSecond)))",
  "                    Spacer()",
  "                    Text(\"-\" + Duration.seconds(duration - elapsed).formatted(.time(pattern: .hourMinuteSecond)))",
  "                }",
  "                .font(.caption.monospacedDigit())",
  "                .contentTransition(.numericText())",
  "                .foregroundStyle(.secondary)",
  "            }",
  "            HStack {",
  "                skip(back: true, size: 30)",
  "                Spacer()",
  "                Button { playing.toggle() } label: {",
  "                    Image(systemName: playing ? \"pause.fill\" : \"play.fill\")",
  "                        .font(.system(size: 30, weight: .bold))",
  "                        .contentTransition(.symbolEffect(.replace))",
  "                        .foregroundStyle(.white)",
  "                        .frame(width: 80, height: 80)",
  "                        .background(tint, in: Circle())",
  "                        .scaleEffect(shown || reduceMotion ? 1 : 0.95)",
  "                        .opacity(shown ? 1 : 0)",
  "                }",
  "                .buttonStyle(PlaybackPressStyle())",
  "                .accessibilityLabel(playing ? \"Pause\" : \"Play\")",
  "                Spacer()",
  "                skip(back: false, size: 30)",
  "            }",
  "            .padding(.horizontal, 12)",
  "        }",
  "    }",
  "",
  "    private var miniBar: some View {",
  "        HStack(spacing: 8) {",
  "            Button { opened += 1; onOpen() } label: {",
  "                HStack(spacing: 12) {",
  "                    RoundedRectangle(cornerRadius: 8, style: .continuous).fill(art).frame(width: 40, height: 40)",
  "                    VStack(alignment: .leading, spacing: 4) {",
  "                        Text(title).font(.subheadline.weight(.medium)).lineLimit(1)",
  "                        HStack(spacing: 6) {",
  "                            ProgressView(value: elapsed, total: duration).frame(width: 44).tint(tint)",
  "                            Text(\"-\" + Duration.seconds(duration - elapsed).formatted(.time(pattern: .hourMinuteSecond)))",
  "                                .font(.caption2.monospacedDigit())",
  "                                .foregroundStyle(.secondary)",
  "                        }",
  "                    }",
  "                    Spacer(minLength: 4)",
  "                }",
  "                .contentShape(Rectangle())",
  "            }",
  "            .buttonStyle(PlaybackPressStyle())",
  "            .foregroundStyle(.primary)",
  "            skip(back: true, size: 18)",
  "            Button { playing.toggle() } label: {",
  "                Image(systemName: playing ? \"pause.fill\" : \"play.fill\")",
  "                    .font(.system(size: 14, weight: .bold))",
  "                    .foregroundStyle(.white)",
  "                    .frame(width: 32, height: 32)",
  "                    .background(tint, in: Circle())",
  "                    .scaleEffect(shown || reduceMotion ? 1 : 0.95)",
  "                    .frame(width: 44, height: 44)",
  "                    .contentShape(Circle())",
  "            }",
  "            .buttonStyle(PlaybackPressStyle())",
  "            skip(back: false, size: 18)",
  "        }",
  "        .padding(.leading, 12)",
  "        .padding(.trailing, 8)",
  "        .padding(.vertical, 4)",
  "        .background(.regularMaterial, in: Capsule())",
  "        .sensoryFeedback(.impact(weight: .light), trigger: opened)",
  "    }",
  "",
  "    private func skip(back: Bool, size: CGFloat) -> some View {",
  "        let seconds = back ? skipBack : skipForward",
  "        return Button {",
  "            if back { backTaps += 1 } else { forwardTaps += 1 }",
  "            withAnimation(.snappy) { elapsed = min(duration, max(0, elapsed + (back ? -seconds : seconds))) }",
  "        } label: {",
  "            Image(systemName: back ? \"gobackward.\\(Int(seconds))\" : \"goforward.\\(Int(seconds))\")",
  "                .font(.system(size: size, weight: .medium))",
  "                .symbolEffect(.bounce, value: back ? backTaps : forwardTaps)",
  "                .frame(minWidth: 44, minHeight: 44)",
  "                .contentShape(Rectangle())",
  "        }",
  "        .buttonStyle(PlaybackPressStyle())",
  "        .sensoryFeedback(.selection, trigger: elapsed) { old, new in abs(new - old) >= 5 }",
  "    }",
  "}",
  "",
  "private struct PlaybackPressStyle: ButtonStyle {",
  "    func makeBody(configuration: Configuration) -> some View {",
  "        configuration.label",
  "            .scaleEffect(configuration.isPressed ? 0.97 : 1)",
  "            .opacity(configuration.isPressed ? 0.8 : 1)",
  "            .animation(.easeOut(duration: 0.12), value: configuration.isPressed)",
  "    }",
  "}",
];

export const playbackControls: SwiftPieceDefinition = {
  id: "playback-controls",
  name: "Playback Controls",
  category: "pieces",
  description: "Now playing: a scrubber with elapsed and remaining time, skip back, play and skip forward. The mini bar rides above the tab bar and opens the player.",
  availability: "free",
  preview: { component: "playback-controls", chunk: "app-pieces" },
  icon: "play.fill",
  concepts: ["state", "binding", "gesture"],
  anatomy: [
    { part: "Now playing", props: ["title", "show", "art"] },
    { part: "Scrubber", props: ["duration", "elapsed"] },
    { part: "Transport", props: ["playing", "skipBack", "skipForward"] },
    { part: "Style", props: ["style", "tint"] },
    { part: "Interaction", props: ["link"] },
  ],
  interactions: ["tap", "scrub", "toggle", "haptic"],
  variants: [
    { id: "full", label: "Player", props: { style: "full", title: "What a quiet city sounds like", show: "Slow Build · Weekly", duration: 1600, elapsed: 305, playing: true } },
    { id: "mini", label: "Mini player", props: { style: "mini", title: "Ep. 12: Salt, smoke and slow mornings", show: "", duration: 5400, elapsed: 1124, playing: false } },
  ],
  states: [
    { id: "paused", label: "Paused", props: { playing: false } },
    { id: "start", label: "Not started", props: { elapsed: 0, playing: false } },
  ],
  properties: [
    text("title", "Title", "What a quiet city sounds like", { maxLength: 80 }),
    text("show", "Show", "Slow Build · Weekly", { maxLength: 60, hint: "Under the title in the full player." }),
    number("art", "Artwork style", 5, 0, 11, 1, { group: "color", hint: "The cover colour for the mini bar's thumbnail." }),
    select("style", "Style", "full", opts(["full", "Full player"], ["mini", "Mini bar"])),
    number("duration", "Length (s)", 1600, 60, 14400, 30, { group: "state" }),
    number("elapsed", "Played (s)", 305, 0, 14400, 5, { group: "state" }),
    bool("playing", "Playing", true, { group: "state" }),
    select("skipBack", "Skip back", "10", opts(...SKIPS.map((x): [string, string] => [x, `${x} s`]))),
    select("skipForward", "Skip forward", "30", opts(...SKIPS.map((x): [string, string] => [x, `${x} s`]))),
    select("tint", "Tint", "accent", opts(["accent", "Accent"], ["red", "Red"], ["teal", "Teal"], ["white", "White"]), { group: "color" }),
    link("link", "Tap the mini bar", { when: { prop: "style", equals: ["mini"] } }),
  ],
  swift: {
    imports: [],
    emit(p, ctx) {
      ctx.declare("PlaybackControls", VIEW);
      const dur = Math.max(60, n(p, "duration"));
      const el = Math.min(dur, Math.max(0, n(p, "elapsed")));
      const tint = s(p, "tint");
      const mini = s(p, "style") === "mini";
      const action = mini ? linkAction(ctx, p.link) : null;
      return {
        lines: call("PlaybackControls", [
          ["title", ctx.str(s(p, "title"))],
          !mini && s(p, "show").trim() && ["show", ctx.str(s(p, "show").trim())],
          mini && ["art", swiftHex(coverStyle("pieces", Math.round(n(p, "art"))).bg)],
          ["duration", num(dur)],
          el > 0 && ["elapsed", num(el)],
          b(p, "playing") && ["playing", "true"],
          s(p, "skipBack") !== "10" && ["skipBack", num(Number(s(p, "skipBack")))],
          s(p, "skipForward") !== "30" && ["skipForward", num(Number(s(p, "skipForward")))],
          mini && ["mini", "true"],
          tint !== "accent" && ["tint", ctx.color(tint)],
          action && ["onOpen", action],
        ]),
      };
    },
  },
};
