// Quiz Choices: a definition on a card and the words it could be. Pick one: the right answer fills
// sage with a tick and a success tap, a wrong one shakes red with an error tap, and a panel rises
// with the answer used in a sentence and a button to move on.
import type { Props, SwiftPieceDefinition } from "../../core/schema.js";
import { INDENT, list, num, str } from "../../core/swift.js";
import { bool, link, number, text } from "../shared.js";
import { arrayArg, construct, linkAction } from "./emit-link-action.js";

const s = (p: Props, k: string) => String(p[k] ?? "");
const n = (p: Props, k: string) => Number(p[k] ?? 0);
const I = (d: number) => INDENT.repeat(d);

export function quizOptions(p: Props): { options: string[]; correct: number } {
  const options = list(p.options, 5);
  const opts = options.length ? options : ["Answer"];
  return { options: opts, correct: Math.min(opts.length - 1, Math.max(0, Math.round(n(p, "correct")))) };
}

const STRUCT = (): string[] => [
  "/// A prompt, the answers it could be, and a panel that rises with the right one in a sentence.",
  "private struct QuizChoices: View {",
  `${I(1)}let prompt: String`,
  `${I(1)}let options: [String]`,
  `${I(1)}let correct: Int`,
  `${I(1)}var example = ""`,
  `${I(1)}var nextTitle = "Next"`,
  `${I(1)}var onNext: (() -> Void)? = nil`,
  `${I(1)}@State var picked: Int? = nil`,
  `${I(1)}@State private var shown = false`,
  `${I(1)}@State private var nexts = 0`,
  `${I(1)}@Environment(\\.accessibilityReduceMotion) private var reduceMotion`,
  "",
  `${I(1)}var body: some View {`,
  `${I(2)}VStack(spacing: 12) {`,
  `${I(3)}Text(prompt)`,
  `${I(4)}.multilineTextAlignment(.center)`,
  `${I(4)}.padding(20)`,
  `${I(4)}.frame(maxWidth: .infinity, minHeight: 120)`,
  `${I(4)}.font(.title3.weight(.semibold))`,
  `${I(4)}.background(.fill.tertiary, in: .rect(cornerRadius: 24, style: .continuous))`,
  `${I(4)}.padding(.bottom, 4)`,
  `${I(3)}ForEach(options.indices, id: \\.self) { index in`,
  `${I(4)}Button { withAnimation(.easeOut(duration: 0.25)) { picked = index } } label: {`,
  `${I(5)}Text(options[index])`,
  `${I(6)}.font(.headline)`,
  `${I(6)}.frame(maxWidth: .infinity)`,
  `${I(6)}.padding(.vertical, 16)`,
  `${I(6)}.overlay(alignment: .leading) {`,
  `${I(7)}if picked != nil && index == correct { Image(systemName: "checkmark").padding(.leading, 18) }`,
  `${I(6)}}`,
  `${I(6)}.background(fill(index), in: .rect(cornerRadius: 16, style: .continuous))`,
  `${I(6)}.contentShape(.rect)`,
  `${I(4)}}`,
  `${I(4)}.buttonStyle(QuizPressStyle())`,
  `${I(4)}.opacity(shown ? 1 : 0)`,
  `${I(4)}.scaleEffect(shown || reduceMotion ? 1 : 0.95)`,
  `${I(4)}.animation(.easeOut(duration: 0.28).delay(Double(min(index, 8)) * 0.04), value: shown)`,
  `${I(4)}.keyframeAnimator(initialValue: 0.0, trigger: picked == index && index != correct) { view, x in`,
  `${I(5)}view.offset(x: x)`,
  `${I(4)}} keyframes: { _ in`,
  `${I(5)}KeyframeTrack {`,
  `${I(6)}LinearKeyframe(-8.0, duration: 0.06)`,
  `${I(6)}LinearKeyframe(7.0, duration: 0.06)`,
  `${I(6)}LinearKeyframe(-5.0, duration: 0.06)`,
  `${I(6)}LinearKeyframe(3.0, duration: 0.06)`,
  `${I(6)}LinearKeyframe(0.0, duration: 0.06)`,
  `${I(5)}}`,
  `${I(4)}}`,
  `${I(3)}}`,
  `${I(3)}Spacer(minLength: 0)`,
  `${I(3)}if let picked {`,
  `${I(4)}result(right: picked == correct)`,
  `${I(5)}.transition(reduceMotion ? .opacity : .offset(y: 16).combined(with: .opacity))`,
  `${I(3)}}`,
  `${I(2)}}`,
  `${I(2)}.onAppear { shown = true }`,
  `${I(2)}.sensoryFeedback(.impact(weight: .light), trigger: nexts)`,
  `${I(2)}.sensoryFeedback(trigger: picked) { _, new in`,
  `${I(3)}guard let new else { return nil }`,
  `${I(3)}return new == correct ? .success : .error`,
  `${I(2)}}`,
  `${I(1)}}`,
  "",
  `${I(1)}private func fill(_ index: Int) -> Color {`,
  `${I(2)}let idle = Color.primary.opacity(0.08)`,
  `${I(2)}guard let picked else { return idle }`,
  `${I(2)}if index == correct { return Color(red: 0.663, green: 0.863, blue: 0.718).opacity(0.5) }`,
  `${I(2)}return index == picked ? Color(red: 1.0, green: 0, blue: 0).opacity(0.4) : idle`,
  `${I(1)}}`,
  "",
  `${I(1)}private func result(right: Bool) -> some View {`,
  `${I(2)}VStack(alignment: .leading, spacing: 8) {`,
  `${I(3)}HStack(spacing: 8) {`,
  `${I(4)}Image(systemName: right ? "checkmark.circle.fill" : "xmark.circle.fill")`,
  `${I(5)}.foregroundStyle(right ? Color(red: 0.663, green: 0.863, blue: 0.718) : Color(red: 1.0, green: 0, blue: 0))`,
  `${I(4)}Text(right ? "Correct" : "Not quite")`,
  `${I(3)}}`,
  `${I(3)}.font(.headline)`,
  `${I(3)}Text(options[correct]).font(.subheadline.weight(.semibold))`,
  `${I(3)}if !example.isEmpty {`,
  `${I(4)}Text(example).font(.footnote).foregroundStyle(.secondary)`,
  `${I(3)}}`,
  `${I(3)}Button {`,
  `${I(4)}nexts += 1`,
  `${I(4)}if let onNext { onNext() } else { withAnimation(.snappy) { picked = nil } }`,
  `${I(3)}} label: {`,
  `${I(4)}Text(nextTitle)`,
  `${I(5)}.font(.headline)`,
  `${I(5)}.frame(maxWidth: .infinity)`,
  `${I(5)}.frame(height: 48)`,
  `${I(5)}.foregroundStyle(.white)`,
  `${I(5)}.background(Color.accentColor, in: .capsule)`,
  `${I(3)}}`,
  `${I(3)}.buttonStyle(QuizPressStyle())`,
  `${I(3)}.padding(.top, 4)`,
  `${I(2)}}`,
  `${I(2)}.padding(20)`,
  `${I(2)}.frame(maxWidth: .infinity, alignment: .leading)`,
  `${I(2)}.background(.fill.tertiary, in: .rect(cornerRadius: 24, style: .continuous))`,
  `${I(1)}}`,
  "}",
  "",
  "private struct QuizPressStyle: ButtonStyle {",
  `${I(1)}func makeBody(configuration: Configuration) -> some View {`,
  `${I(2)}configuration.label`,
  `${I(3)}.scaleEffect(configuration.isPressed ? 0.97 : 1)`,
  `${I(3)}.animation(.easeOut(duration: 0.12), value: configuration.isPressed)`,
  `${I(1)}}`,
  "}",
];

export const quizChoices: SwiftPieceDefinition = {
  id: "quiz-choices",
  name: "Quiz Choices",
  category: "pieces",
  description: "A prompt on a card and the answers it could be. The right pick fills sage with a success tap, a wrong one shakes red, and a panel rises with the answer in a sentence and a button to move on.",
  availability: "free",
  preview: { component: "quiz-choices", chunk: "app-pieces" },
  icon: "checkmark.circle.fill",
  concepts: ["state", "foreach", "animation"],
  interactions: ["tap", "select", "haptic", "push"],
  anatomy: [
    { part: "Prompt", props: ["prompt"] },
    { part: "Answers", props: ["options", "correct"] },
    { part: "Result", props: ["example", "nextTitle", "link"] },
    { part: "State", props: ["answered"] },
  ],
  properties: [
    text("prompt", "Prompt", "Willing to give more than is needed; generous", { maxLength: 140 }),
    text("options", "Answers", "munificent, taciturn, brusque", { maxLength: 120 }),
    number("correct", "Right answer", 0, 0, 4, 1, { hint: "Which answer is right, from 0." }),
    text("example", "In a sentence", "A munificent neighbour paid for the new benches in the park.", { maxLength: 140 }),
    text("nextTitle", "Button", "Next word", { maxLength: 24 }),
    bool("answered", "Starts answered", false, { group: "state" }),
    link("link", "Button opens", { hint: "Leave empty to try again." }),
  ],
  variants: [
    { id: "words", label: "Words", props: {} },
    { id: "capitals", label: "Capitals", props: { prompt: "The capital of Norway", options: "Bergen, Oslo, Trondheim", correct: 1, example: "Oslo sits at the head of the Oslofjord.", nextTitle: "Next question" } },
    { id: "answered", label: "Answered", props: { answered: true } },
  ],
  states: [{ id: "answered", label: "Answered", props: { answered: true } }],
  swift: {
    imports: [],
    emit(p, ctx) {
      ctx.declare("QuizChoices", STRUCT());
      const { options, correct } = quizOptions(p);
      const action = linkAction(ctx, p.link);
      return {
        lines: construct("QuizChoices", [
          `prompt: ${str(s(p, "prompt"))}`,
          arrayArg("options", options.map(str)),
          `correct: ${num(correct)}`,
          s(p, "example").trim() && `example: ${str(s(p, "example").trim())}`,
          s(p, "nextTitle") !== "Next" && `nextTitle: ${str(s(p, "nextTitle"))}`,
          action && `onNext: ${action}`,
          p.answered === true && `picked: ${num(correct)}`,
        ]),
      };
    },
  },
};
