// Route Row: one trip in a list of trips (a flight, a train, a ferry): its number, where it goes,
// the departure and arrival with their times, and the state that matters now ("Landing in 3h 30m").
// A leading column shows how soon it is, that it's in the air, or who is on it. Tap to open it.
// Two styles: a plain list row, and a card on the raised surface where the two ends sit at either
// side of a track that fills to show how far along the trip is.
import type { Props, SwiftPieceDefinition } from "../../core/schema.js";
import { call, num } from "../../core/swift.js";
import { link, number, opts, select, text } from "../shared.js";
import { swiftHex } from "./data-kit.js";
import { linkAction } from "./emit-link-action.js";

const s = (p: Props, k: string) => String(p[k] ?? "");

/** What each state says, and the colour of its status value: calm ink when things are fine, signal
 *  red only when running late (the one accent marks what needs you), secondary when not yet live. */
export const ROUTE_STATES: Record<string, { label: string; color: string }> = {
  ontime: { label: "On time", color: "primary" },
  early: { label: "Early", color: "primary" },
  late: { label: "Late", color: "#FF0000" },
  scheduled: { label: "Scheduled", color: "secondary" },
};
/** Avatar fills from the house blocks (dark ink on each), picked by the initials so a person keeps their colour. */
export const ROUTE_AVATARS = ["#9CC2FF", "#FFD976", "#A9DCB7", "#CDB8FF", "#E9D5B3"];
export const AVATAR_INK = "#141414";
/** A stable pick from a person's initials (weighted by position, so RK and TN differ); the route map uses the same. */
export const initialsHash = (initials: string) => [...initials].reduce((a, c, i) => a + c.charCodeAt(0) * (i + 1), 0);
export const avatarFill = (initials: string) => ROUTE_AVATARS[initialsHash(initials) % ROUTE_AVATARS.length];
/** The note under the times: secondary ink, with a clock. */
export const NOTE_COLOR = "secondary";

const VIEW = [
  "private struct RouteRow: View {",
  "    var number = \"\"",
  "    let title: String",
  "    let from: String",
  "    let departs: String",
  "    let to: String",
  "    let arrives: String",
  "    var detail = \"\"",
  "    var highlight = \"\"",
  "    /// The status value's colour; the track and the in-the-air mark always take the accent.",
  "    var state: Color = .primary",
  "    /// 0 none, 1 in the air, 2 countdown, 3 avatar",
  "    var leading = 0",
  "    var leadValue = \"\"",
  "    var leadCaption = \"\"",
  "    var avatar: Color = .gray",
  "    var note = \"\"",
  "    /// A card with the ends either side of a track; progress 0…1 places the plane on it.",
  "    var card = false",
  "    var corner: CGFloat = 20",
  "    var progress: Double? = nil",
  "    var action: () -> Void = {}",
  "",
  "    @State private var shown = false",
  "    @State private var filled = false",
  "    @State private var taps = 0",
  "    @Environment(\\.accessibilityReduceMotion) private var reduceMotion",
  "",
  "    var body: some View {",
  "        Button {",
  "            taps += 1",
  "            action()",
  "        } label: {",
  "            HStack(alignment: .top, spacing: 12) {",
  "                if leading > 0 { lead.frame(width: 52) }",
  "                VStack(alignment: .leading, spacing: card ? 8 : 4) {",
  "                    HStack {",
  "                        if !number.isEmpty {",
  "                            Label(number, systemImage: \"airplane\").font(.footnote).foregroundStyle(.secondary)",
  "                        }",
  "                        Spacer()",
  "                        if !detail.isEmpty {",
  "                            Text(\"\\(Text(detail + \" \").foregroundStyle(.secondary))\\(Text(highlight).foregroundStyle(state).fontWeight(.semibold))\").font(.footnote.weight(.medium)).monospacedDigit()",
  "                        }",
  "                    }",
  "                    Text(title).font(.headline)",
  "                    if card { track } else {",
  "                        HStack(spacing: 16) {",
  "                            stop(\"arrow.up.right.circle.fill\", from, departs)",
  "                            stop(\"arrow.down.right.circle.fill\", to, arrives)",
  "                        }",
  "                    }",
  "                    if !note.isEmpty {",
  "                        Label(note, systemImage: \"clock\").font(.caption.weight(.medium)).foregroundStyle(.secondary)",
  "                    }",
  "                }",
  "            }",
  "            .padding(.vertical, card ? 16 : 12)",
  "            .padding(.horizontal, card ? 16 : 0)",
  "            .background {",
  "                if card { RoundedRectangle(cornerRadius: corner, style: .continuous).fill(.fill.tertiary) }",
  "            }",
  "            .contentShape(RoundedRectangle(cornerRadius: card ? corner : 0, style: .continuous))",
  "        }",
  "        .buttonStyle(RouteRowPress(card: card, corner: corner))",
  "        .sensoryFeedback(.impact(weight: .light), trigger: taps)",
  "        // Entrance, once: the row settles in from 0.95 with a fade, then the track fills to the plane.",
  "        .opacity(shown ? 1 : 0)",
  "        .scaleEffect(shown || reduceMotion ? 1 : 0.95)",
  "        .onAppear {",
  "            guard !shown else { return }",
  "            if reduceMotion {",
  "                withAnimation(.easeOut(duration: 0.2)) { shown = true }",
  "                filled = true",
  "            } else {",
  "                withAnimation(.easeOut(duration: 0.28)) { shown = true }",
  "                withAnimation(.easeOut(duration: 0.3).delay(0.08)) { filled = true }",
  "            }",
  "        }",
  "    }",
  "",
  "    private var track: some View {",
  "        VStack(spacing: 4) {",
  "            HStack(spacing: 12) {",
  "                Text(from).font(.title3.weight(.bold))",
  "                GeometryReader { geo in",
  "                    let f = filled ? min(1, max(0, progress ?? 0)) : 0",
  "                    ZStack(alignment: .leading) {",
  "                        Capsule().fill(Color.primary.opacity(0.12)).frame(height: 3)",
  "                        Capsule().fill(Color.accentColor).frame(width: geo.size.width * f, height: 3)",
  "                        if progress != nil {",
  "                            Image(systemName: \"airplane\").font(.caption).foregroundStyle(.primary)",
  "                                .offset(x: geo.size.width * f - 7)",
  "                        }",
  "                    }",
  "                    .frame(maxHeight: .infinity)",
  "                }",
  "                .frame(height: 16)",
  "                Text(to).font(.title3.weight(.bold))",
  "            }",
  "            HStack {",
  "                Text(departs)",
  "                Spacer()",
  "                Text(arrives)",
  "            }",
  "            .font(.subheadline.monospacedDigit())",
  "            .foregroundStyle(.secondary)",
  "        }",
  "    }",
  "",
  "    @ViewBuilder private var lead: some View {",
  "        switch leading {",
  "        case 1:",
  "            VStack(spacing: 4) {",
  "                Image(systemName: \"airplane\").font(.footnote).foregroundStyle(Color.accentColor).frame(width: 36, height: 36).background(Color.accentColor.opacity(0.14), in: Circle())",
  "                Text(leadCaption.uppercased()).font(.caption2.weight(.medium)).foregroundStyle(.secondary)",
  "            }",
  "        case 2:",
  "            VStack(spacing: 0) {",
  "                Text(leadValue).font(.title.weight(.semibold)).monospacedDigit()",
  "                Text(leadCaption.uppercased()).font(.caption2.weight(.medium)).foregroundStyle(.secondary)",
  "            }",
  "        default:",
  "            VStack(spacing: 4) {",
  "                Text(leadValue).font(.headline).foregroundStyle(Color(red: 0.078, green: 0.078, blue: 0.078)).frame(width: 44, height: 44).background(avatar, in: Circle())",
  "                Text(leadCaption.uppercased()).font(.caption2.weight(.medium)).foregroundStyle(.secondary)",
  "            }",
  "        }",
  "    }",
  "",
  "    private func stop(_ symbol: String, _ code: String, _ time: String) -> some View {",
  "        HStack(spacing: 4) {",
  "            Image(systemName: symbol).foregroundStyle(Color.accentColor)",
  "            Text(code).foregroundStyle(.secondary)",
  "            Text(time).foregroundStyle(.primary).monospacedDigit()",
  "        }",
  "        .font(.subheadline.weight(.medium))",
  "    }",
  "}",
  "",
  "/// Press feedback: a card scales to 0.97, a list row takes a highlight; both under 150 ms.",
  "private struct RouteRowPress: ButtonStyle {",
  "    var card: Bool",
  "    var corner: CGFloat",
  "    func makeBody(configuration: Configuration) -> some View {",
  "        configuration.label",
  "            .background {",
  "                if !card && configuration.isPressed { Color.primary.opacity(0.06).padding(.horizontal, -8) }",
  "            }",
  "            .scaleEffect(card && configuration.isPressed ? 0.97 : 1)",
  "            .animation(.easeOut(duration: 0.12), value: configuration.isPressed)",
  "    }",
  "}",
];

export const routeRow: SwiftPieceDefinition = {
  id: "route-row",
  name: "Route Row",
  category: "pieces",
  description: "One trip in a list: its number, route, departure and arrival times, and the status that matters now. Tap to open it.",
  availability: "free",
  preview: { component: "route-row", chunk: "app-pieces" },
  card: (p) => (p.style === "card" ? Number(p.radius ?? 20) : null),
  // In a list it takes its list-row form (two stops instead of the track), which pads itself 12.
  list: { bare: { style: "list" }, pad: 0 },
  icon: "airplane",
  concepts: ["state"],
  anatomy: [
    { part: "Leading", props: ["leading", "leadValue", "leadCaption"] },
    { part: "Header", props: ["number", "detail", "highlight"] },
    { part: "Route", props: ["style", "radius", "title", "from", "departs", "to", "arrives", "state", "progress"] },
    { part: "Note", props: ["note"] },
    { part: "Interaction", props: ["link"] },
  ],
  interactions: ["tap", "press", "haptic"],
  variants: [
    { id: "air", label: "In the air", props: { style: "card", leading: "air", leadCaption: "In air", number: "SP 214", title: "Seattle to Atlanta", from: "SEA", departs: "7:05 AM", to: "ATL", arrives: "3:10 PM", detail: "Lands in", highlight: "2h 05m", state: "ontime", progress: 62, note: "" } },
    { id: "soon", label: "Coming up", props: { style: "card", leading: "countdown", leadValue: "6h", leadCaption: "Hours", number: "SP 380", title: "Denver to Boston", from: "DEN", departs: "1:20 PM", to: "BOS", arrives: "7:02 PM", detail: "Fri, 3 Oct", highlight: "", state: "scheduled", progress: -1 } },
    { id: "friend", label: "A friend's flight", props: { style: "card", leading: "avatar", leadValue: "RK", leadCaption: "In air", number: "SP 77", title: "Anchorage to Seattle", from: "ANC", departs: "9:15 AM", to: "SEA", arrives: "1:48 PM", detail: "Lands in", highlight: "48m", state: "early", progress: 80 } },
    { id: "list", label: "List row", props: { style: "list", leading: "air", leadCaption: "In air", number: "SP 214", title: "Seattle to Atlanta", from: "SEA", departs: "7:05 AM", to: "ATL", arrives: "3:10 PM", detail: "Lands in", highlight: "2h 05m", state: "ontime" } },
  ],
  states: [
    { id: "late", label: "Running late", props: { state: "late", detail: "Delayed", highlight: "40m" } },
    { id: "tight", label: "Tight connection", props: { note: "50 min to change planes in Atlanta" } },
  ],
  properties: [
    select("style", "Style", "card", opts(["card", "Card with track"], ["list", "List row"]), { group: "layout" }),
    select("leading", "Leading", "air", opts(["none", "None"], ["air", "In the air"], ["countdown", "Countdown"], ["avatar", "Avatar"])),
    text("leadValue", "Lead value", "4h", { maxLength: 6, hint: "The countdown (4h) or initials (JM).", when: { prop: "leading", equals: ["countdown", "avatar"] } }),
    text("leadCaption", "Lead caption", "In air", { maxLength: 12 }),
    text("number", "Number", "SP 214", { maxLength: 16 }),
    text("title", "Route", "Seattle to Atlanta", { maxLength: 60 }),
    text("from", "From", "SEA", { maxLength: 5 }),
    text("departs", "Departs", "7:05 AM", { maxLength: 10 }),
    text("to", "To", "ATL", { maxLength: 5 }),
    text("arrives", "Arrives", "3:10 PM", { maxLength: 10 }),
    text("detail", "Status", "Lands in", { maxLength: 30 }),
    text("highlight", "Status value", "2h 05m", { maxLength: 16, hint: "Set in the state colour after the status." }),
    select("state", "State", "ontime", opts(...Object.entries(ROUTE_STATES).map(([id, v]): [string, string] => [id, v.label])), { group: "state" }),
    number("progress", "Progress", 62, -1, 100, 1, { group: "state", hint: "How far along the track the plane is, in percent; -1 hides it.", when: { prop: "style", equals: ["card"] } }),
    text("note", "Note", "", { maxLength: 60, hint: "A quiet line with a clock under the times, like a tight connection." }),
    number("radius", "Corner radius", 20, 0, 40, 1, { group: "layout", hint: "The card's corners; match the app's card radius.", when: { prop: "style", equals: ["card"] } }),
    link("link", "On tap"),
  ],
  swift: {
    imports: [],
    emit(p, ctx) {
      ctx.declare("RouteRow", VIEW);
      const lead = { none: 0, air: 1, countdown: 2, avatar: 3 }[s(p, "leading")] ?? 0;
      const st = ROUTE_STATES[s(p, "state")] ?? ROUTE_STATES.ontime;
      const card = s(p, "style") !== "list";
      const progress = Number(p.progress ?? -1);
      const action = linkAction(ctx, p.link);
      const opt = (k: string) => s(p, k).trim();
      return {
        lines: call("RouteRow", [
          opt("number") && ["number", ctx.str(opt("number"))],
          ["title", ctx.str(s(p, "title"))],
          ["from", ctx.str(s(p, "from"))],
          ["departs", ctx.str(s(p, "departs"))],
          ["to", ctx.str(s(p, "to"))],
          ["arrives", ctx.str(s(p, "arrives"))],
          opt("detail") && ["detail", ctx.str(opt("detail"))],
          opt("highlight") && ["highlight", ctx.str(opt("highlight"))],
          st.color !== "primary" && ["state", st.color === "secondary" ? "Color.secondary" : swiftHex(st.color)],
          lead > 0 && ["leading", String(lead)],
          lead > 1 && opt("leadValue") && ["leadValue", ctx.str(opt("leadValue"))],
          lead > 0 && opt("leadCaption") && ["leadCaption", ctx.str(opt("leadCaption"))],
          lead === 3 && ["avatar", swiftHex(avatarFill(opt("leadValue")))],
          opt("note") && ["note", ctx.str(opt("note"))],
          card && ["card", "true"],
          card && Number(p.radius ?? 20) !== 20 && ["corner", num(Number(p.radius))],
          card && progress >= 0 && ["progress", num(Math.min(100, progress) / 100)],
          action && ["action", action],
        ]),
      };
    },
  },
};
