// Stat Grid: a grid of labelled figures where the numbers read large and their units small
// ("7h 46m"), each with an optional note under it (a check and "Normal", or last period's value).
// Plain cells sit on the screen; tiles give each figure its own coloured card, and tapping a tile
// swaps in the comparison figure with a rolling-digit transition and a selection tick. Cells ease in
// from 0.95 with a fade, 40 ms apart, and dip to 0.97 under a finger.
import type { SwiftPieceDefinition } from "../../core/schema.js";
import { call, num } from "../../core/swift.js";
import { link, number, opts, select } from "../shared.js";
import { linkAction } from "./nav-action.js";
import { data, items, records, swiftHex, swiftStrs, swiftTint, tint } from "./data-kit.js";

const s = (p: Record<string, unknown>, k: string) => String(p[k] ?? "");
const n = (p: Record<string, unknown>, k: string) => Number(p[k] ?? 0);

const ITEMS = "Distance | 4.2 km | ; Active time | 1h 12m | ; Climbed | 9 floors | ; Average pulse | 74 bpm |";

/** Pastel house fills for the contour style (the Studio family's topographic cards). */
export const CONTOUR_FILLS: Record<string, string> = {
  peach: "#F3B994", sky: "#AFCBF5", sage: "#B5DCC0", lilac: "#D3C4F5", butter: "#F7DB8C", sand: "#E9D5B3", blush: "#F6B8CE",
};
export const contourFill = (id: string) => CONTOUR_FILLS[id] ?? CONTOUR_FILLS.peach;

/** The topographic lines, in a 400 × 400 box (same curves as the Pro Studio family's contours). */
export const contourPath = (i: number) => `M-20 ${60 + i * 48} C 80 ${20 + i * 52}, 160 ${140 + i * 40}, 250 ${70 + i * 50} S 380 ${150 + i * 44}, 440 ${90 + i * 50}`;

export const STAT_GRID_SWIFT = [
  "private struct StatGrid: View {",
  "    let labels: [String]",
  "    let values: [String]",
  "    let notes: [String]",
  "    var tiles: [Color] = []",
  "    var columns = 2",
  "    var valueSize: CGFloat = 30",
  "    var noteColor: Color = .green",
  "    var noteIcon = \"checkmark.circle.fill\"",
  "    var cards = false",
  "    var radius: CGFloat = 22",
  "    var contour = false",
  "    /// Contour cards as squares: the label large in the middle, the figure and its note under it.",
  "    var squares = false",
  "    var action: (() -> Void)? = nil",
  "    @State private var flipped: Set<Int> = []",
  "    @State private var tapped = 0",
  "    @State private var appeared = false",
  "    @Environment(\\.accessibilityReduceMotion) private var reduceMotion",
  "",
  "    var body: some View {",
  "        LazyVGrid(columns: Array(repeating: GridItem(.flexible(), spacing: 12, alignment: .topLeading), count: columns), alignment: .leading, spacing: tiles.isEmpty ? 18 : 12) {",
  "            ForEach(labels.indices, id: \\.self) { i in",
  "                if contour { contourCell(i) } else { cell(i) }",
  "            }",
  "        }",
  "        .sensoryFeedback(.selection, trigger: tapped)",
  "        .onAppear { appeared = true }",
  "    }",
  "",
  "    @ViewBuilder private func cell(_ i: Int) -> some View {",
  "        let note = i < notes.count ? notes[i] : \"\"",
  "        let showsNote = flipped.contains(i) && !note.isEmpty",
  "        let tappable = action != nil || !note.isEmpty",
  "        Button {",
  "            tapped += 1",
  "            if let action { action(); return }",
  "            withAnimation(.snappy(duration: 0.25)) {",
  "                if flipped.contains(i) { flipped.remove(i) } else { flipped.insert(i) }",
  "            }",
  "        } label: {",
  "            VStack(alignment: .leading, spacing: 4) {",
  "                Text(labels[i])",
  "                    .font(.subheadline)",
  "                    .foregroundStyle(tiles.isEmpty ? AnyShapeStyle(.secondary) : AnyShapeStyle(.white.opacity(0.85)))",
  "                HStack(alignment: .firstTextBaseline, spacing: 1) {",
  "                    ForEach(Array(Self.runs(showsNote ? note : values[i]).enumerated()), id: \\.offset) { _, run in",
  "                        Text(run.text)",
  "                            .font(.system(size: run.unit ? valueSize * 0.55 : valueSize, weight: .bold))",
  "                            .monospacedDigit()",
  "                            .padding(.trailing, run.unit ? 3 : 0)",
  "                    }",
  "                }",
  "                .contentTransition(.numericText())",
  "                .foregroundStyle(tiles.isEmpty ? Color.primary : Color.white)",
  "                if !note.isEmpty && cards {",
  "                    Text(showsNote ? values[i] : note).font(.subheadline).foregroundStyle(.secondary)",
  "                        .contentTransition(.numericText())",
  "                } else if !note.isEmpty && tiles.isEmpty {",
  "                    Label(note, systemImage: noteIcon)",
  "                        .font(.subheadline)",
  "                        .foregroundStyle(noteColor)",
  "                } else if !note.isEmpty {",
  "                    Label(showsNote ? values[i] : note, systemImage: \"arrow.up\")",
  "                        .font(.footnote.weight(.semibold))",
  "                        .foregroundStyle(.white.opacity(0.8))",
  "                }",
  "            }",
  "            .frame(maxWidth: .infinity, alignment: .leading)",
  "            .padding(tiles.isEmpty && !cards ? 0 : 16)",
  "            .background {",
  "                if !tiles.isEmpty {",
  "                    RoundedRectangle(cornerRadius: radius, style: .continuous).fill(tiles[i % tiles.count].gradient)",
  "                } else if cards {",
  "                    RoundedRectangle(cornerRadius: radius, style: .continuous).fill(.fill.tertiary)",
  "                }",
  "            }",
  "            .contentShape(.rect)",
  "        }",
  "        .buttonStyle(StatGridPress())",
  "        .disabled(!tappable)",
  "        .scaleEffect(appeared || reduceMotion ? 1 : 0.95)",
  "        .opacity(appeared ? 1 : 0)",
  "        .animation(.easeOut(duration: reduceMotion ? 0.2 : 0.3).delay(reduceMotion ? 0 : Double(min(i, 7)) * 0.04), value: appeared)",
  "    }",
  "",
  "    /// A contour card: a pastel fill with topographic lines, a large light figure, the label and a quiet note.",
  "    @ViewBuilder private func contourCell(_ i: Int) -> some View {",
  "        let ink = Color(red: 0.078, green: 0.078, blue: 0.078)",
  "        let note = i < notes.count ? notes[i] : \"\"",
  "        Button {",
  "            tapped += 1",
  "            action?()",
  "        } label: {",
  "            Group {",
  "                if squares {",
  "                    Color.clear",
  "                        .aspectRatio(1, contentMode: .fit)",
  "                        .overlay {",
  "                            VStack(spacing: 6) {",
  "                                Text(labels[i]).font(.title2.weight(.bold)).multilineTextAlignment(.center)",
  "                                Text(note.isEmpty ? values[i] : \"\\(values[i]) \\(note)\").font(.subheadline).opacity(0.62)",
  "                            }",
  "                            .padding(16)",
  "                        }",
  "                } else {",
  "                    HStack(alignment: .center, spacing: 18) {",
  "                        Text(values[i])",
  "                            .font(.system(size: valueSize, weight: .light))",
  "                            .monospacedDigit()",
  "                            .lineLimit(1)",
  "                        VStack(alignment: .leading, spacing: 4) {",
  "                            Text(labels[i]).font(.title3.weight(.medium))",
  "                            if !note.isEmpty { Text(note).font(.subheadline).opacity(0.62) }",
  "                        }",
  "                    }",
  "                    .frame(maxWidth: .infinity, alignment: .leading)",
  "                    .padding(.horizontal, 24)",
  "                    .padding(.vertical, 22)",
  "                }",
  "            }",
  "            .foregroundStyle(ink)",
  "            .background {",
  "                ZStack {",
  "                    tiles.isEmpty ? Color.gray.opacity(0.3) : tiles[i % tiles.count]",
  "                    StatGridContours().stroke(ink.opacity(0.14), lineWidth: 1)",
  "                }",
  "                .clipShape(.rect(cornerRadius: radius, style: .continuous))",
  "            }",
  "            .contentShape(.rect)",
  "        }",
  "        .buttonStyle(StatGridPress())",
  "        .disabled(action == nil)",
  "        .scaleEffect(appeared || reduceMotion ? 1 : 0.95)",
  "        .opacity(appeared ? 1 : 0)",
  "        .animation(.easeOut(duration: reduceMotion ? 0.2 : 0.3).delay(reduceMotion ? 0 : Double(min(i, 7)) * 0.04), value: appeared)",
  "    }",
  "",
  "    /// \"7h 46m\" as number runs and unit runs, so the units can be set smaller.",
  "    static func runs(_ value: String) -> [(text: String, unit: Bool)] {",
  "        guard value.contains(where: { $0.isNumber }) else { return [(value, false)] }",
  "        var out: [(text: String, unit: Bool)] = []",
  "        for ch in value where ch != \" \" {",
  "            let unit = !(ch.isNumber || ch == \".\" || ch == \",\" || ch == \":\")",
  "            if let last = out.last, last.unit == unit {",
  "                out[out.count - 1].text.append(ch)",
  "            } else {",
  "                out.append((String(ch), unit))",
  "            }",
  "        }",
  "        return out",
  "    }",
  "}",
  "",
  "/// Topographic contour lines filling the card (the Studio family's motif).",
  "private struct StatGridContours: Shape {",
  "    func path(in rect: CGRect) -> Path {",
  "        let side = max(rect.width, rect.height)",
  "        let s = side / 400",
  "        let ox = rect.midX - side / 2, oy = rect.midY - side / 2",
  "        func p(_ x: CGFloat, _ y: CGFloat) -> CGPoint { CGPoint(x: ox + x * s, y: oy + y * s) }",
  "        var path = Path()",
  "        for i in 0..<7 {",
  "            let y = CGFloat(i)",
  "            path.move(to: p(-20, 60 + y * 48))",
  "            path.addCurve(to: p(250, 70 + y * 50), control1: p(80, 20 + y * 52), control2: p(160, 140 + y * 40))",
  "            path.addCurve(to: p(440, 90 + y * 50), control1: p(340, 0 + y * 60), control2: p(380, 150 + y * 44))",
  "        }",
  "        return path",
  "    }",
  "}",
  "",
  "private struct StatGridPress: ButtonStyle {",
  "    func makeBody(configuration: Configuration) -> some View {",
  "        configuration.label",
  "            .scaleEffect(configuration.isPressed ? 0.97 : 1)",
  "            .animation(.easeOut(duration: 0.12), value: configuration.isPressed)",
  "    }",
  "}",
];

export const statGrid: SwiftPieceDefinition = {
  id: "stat-grid",
  name: "Stat Grid",
  category: "pieces",
  description: "Labelled figures in a grid, numbers large and units small, each with a note (a check and \"Normal\", or last period's figure). Tiles tap to compare.",
  availability: "free",
  preview: { component: "stat-grid", chunk: "app-pieces" },
  icon: "square.grid.2x2",
  concepts: ["state", "foreach"],
  anatomy: [
    { part: "Figures", props: ["items", "valueSize"] },
    { part: "Layout", props: ["style", "columns"] },
    { part: "Notes", props: ["noteIcon", "noteTint"] },
    { part: "Tiles", props: ["tiles"] },
    { part: "Interaction", props: ["link"] },
  ],
  interactions: ["tap", "haptic"],
  variants: [
    { id: "plain", label: "Plain", props: { style: "plain", columns: 2, items: ITEMS } },
    { id: "notes", label: "With notes", props: { style: "plain", columns: 2, items: "Asleep | 7h 46m | Usual; Deep | 1h 38m | Usual; Lights out | 23:10 | Usual; Up at | 06:58 | Early" } },
    { id: "cards", label: "Cards", props: { style: "cards", columns: 1, items: "Sleep | Restful | 7h 46m; Readiness | Ease in | A short walk suits today" } },
    { id: "contour", label: "Contour cards", props: { style: "contour", columns: 1, valueSize: 64, radius: 32, tiles: "peach, sky", items: "blocks today | 5 | 2 h 50 m · ends 16:40; left this week | 12 | 3 due tomorrow" } },
    { id: "squares", label: "Contour squares", props: { style: "squares", columns: 2, radius: 28, tiles: "sage, lilac, blush, sky", items: "Reframe | 7 | ways; Be kind | 4 | drills; Reach out | 3 | people; Slow down | 6 | paces" } },
    { id: "tiles", label: "Tiles", props: { style: "tiles", columns: 2, valueSize: 26, items: "Active time | 26h 40m | 22h 15m; Workouts | 18 | 15; Distance | 148 km | 121 km; Calories | 13,420 kcal | 11,870 kcal" } },
  ],
  states: [
    { id: "one", label: "One column", props: { columns: 1 } },
    { id: "three", label: "Three columns", props: { columns: 3, valueSize: 22 } },
  ],
  properties: [
    data("items", "Figures", ITEMS, { hint: "Label | value | note, separated by semicolons. The note is optional." }),
    select("style", "Style", "plain", opts(["plain", "Plain"], ["cards", "Cards"], ["tiles", "Coloured tiles"], ["contour", "Contour cards"], ["squares", "Contour squares"])),
    number("columns", "Columns", 2, 1, 3),
    number("valueSize", "Figure size", 30, 18, 48),
    number("radius", "Corner radius", 22, 8, 32, 1, { hint: "Cards and tiles." }),
    select("noteIcon", "Note icon", "checkmark.circle.fill", opts(["checkmark.circle.fill", "Check"], ["arrow.up", "Up"], ["info.circle", "Info"])),
    tint("noteTint", "Note colour", "azure"),
    link("link", "On tap", { hint: "Where tapping a figure goes. Empty: tapping swaps in the note." }),
    data("tiles", "Tile colours", "signal, ember, blush, azure", { when: { prop: "style", equals: ["tiles", "contour", "squares"] }, hint: "Tiles: tints in order, repeated. Contour cards: peach, sky, sage, lilac, butter, sand or blush." }),
  ],
  swift: {
    imports: [],
    emit(p, ctx) {
      // In an app styled with cards, each card tile is one of the app's cards.
      ctx.declare("StatGrid", ctx.theme && ctx.theme.cards !== "flat"
        ? STAT_GRID_SWIFT.map((l) => l.replace("RoundedRectangle(cornerRadius: radius, style: .continuous).fill(.fill.tertiary)", "Color.clear.themeCard(cornerRadius: radius)"))
        : STAT_GRID_SWIFT);
      const rows = records(s(p, "items"));
      const squares = s(p, "style") === "squares";
      const contour = s(p, "style") === "contour" || squares;
      const tiles = s(p, "style") === "tiles" || contour ? items(s(p, "tiles")) : [];
      const act = linkAction(ctx, p.link);
      return {
        lines: call("StatGrid", [
          ["labels", swiftStrs(rows.map((r) => r[0] ?? ""), ctx.str)],
          ["values", swiftStrs(rows.map((r) => r[1] ?? ""), ctx.str)],
          ["notes", swiftStrs(rows.map((r) => r[2] ?? ""), ctx.str)],
          tiles.length > 0 && ["tiles", `[${tiles.map((t) => (contour ? swiftHex(contourFill(t)) : swiftTint(t))).join(", ")}]`],
          n(p, "columns") !== 2 && ["columns", num(n(p, "columns"))],
          n(p, "valueSize") !== 30 && ["valueSize", num(n(p, "valueSize"))],
          s(p, "noteTint") !== "green" && ["noteColor", swiftTint(s(p, "noteTint"))],
          s(p, "noteIcon") !== "checkmark.circle.fill" && ["noteIcon", ctx.str(s(p, "noteIcon"))],
          s(p, "style") === "cards" && ["cards", "true"],
          p.radius != null && n(p, "radius") !== 22 && ["radius", num(n(p, "radius"))],
          contour && ["contour", "true"],
          squares && ["squares", "true"],
          act && ["action", `{ ${act} }`],
        ]),
      };
    },
  },
};
