// Metadata for every free catalog entry: what lists, search, page titles and the sitemap read.
// Descriptions are the page's real content (the About panel and the meta description), so each one
// says what the thing is, how it behaves and what it is built from, in two or three sentences.
import type { CatalogEntry } from "../../core/catalog.js";

type E = Omit<CatalogEntry, "availability"> & { availability?: CatalogEntry["availability"] };
const free = (e: E): CatalogEntry => ({ availability: "free", ...e });

// ---------------------------------------------------------------- Screens

const screens: CatalogEntry[] = [
  free({
    kind: "screens", slug: "onboarding", title: "Onboarding", category: "First run", featured: true,
    summary: "Swipeable welcome pages with a springy call to action.",
    description: "A first-run screen that pages through what the app does, then asks for one clear next step. Swipe the pages, watch the dots follow, and press Get started to feel the elastic button spring. Built from a page-style TabView, text and an Elastic Button.",
    try: ["Swipe the pages left and right", "Tap a page dot to jump", "Press and hold Get started, then let go"],
    interactions: ["swipe", "press", "spring", "haptic"],
    components: ["page-carousel", "elastic-button", "text"],
    keywords: ["swiftui onboarding", "swiftui onboarding screen", "swiftui page view", "tabview page style"],
  }),
  free({
    kind: "screens", slug: "login", title: "Login", category: "Account",
    summary: "Email, password, Sign in with Apple and a reset sheet.",
    description: "A sign-in screen with real text fields, a secure password field, Sign in with Apple and a forgot-password sheet that rises over the screen. Type into the fields, open the reset sheet and drag it down to dismiss it. Every part is native SwiftUI.",
    try: ["Type an email and a password", "Tap Forgot password? to open the sheet", "Drag the sheet down to dismiss it"],
    interactions: ["type", "tap", "sheet"],
    components: ["input", "button", "apple-sign-in"],
    keywords: ["swiftui login screen", "swiftui sign in", "sign in with apple swiftui", "swiftui textfield"],
  }),
  free({
    kind: "screens", slug: "sign-up", title: "Sign Up", category: "Account",
    summary: "Floating fields, a live password meter and a button that shows progress.",
    description: "Account creation that reacts as you type: the password strength meter fills, requirements light up, and the create button runs its loading state before it lands on success. Built from Form Field, Secure Entry and Commit Button.",
    try: ["Type a password and watch the meter", "Tap Create account to see it load and succeed"],
    interactions: ["type", "loading", "haptic"],
    components: ["secure-entry", "form-field", "commit-button"],
    keywords: ["swiftui sign up", "swiftui registration form", "password strength swiftui", "swiftui loading button"],
  }),
  free({
    kind: "screens", slug: "profile", title: "Profile", category: "Account",
    summary: "An avatar, stats, and rows that push deeper.",
    description: "A profile with an avatar, a stats strip and grouped rows. Tap a row and the next screen slides in with a back button you can also swipe from the edge. Edit profile opens as a sheet. Built from native rows, cards and a NavigationStack.",
    try: ["Tap Saved to push a screen", "Swipe from the left edge to go back", "Tap Edit profile to open a sheet"],
    interactions: ["push", "sheet", "tap"],
    components: ["avatar", "row", "button"],
    keywords: ["swiftui profile screen", "swiftui navigationlink", "swiftui list rows"],
  }),
  free({
    kind: "screens", slug: "settings", title: "Settings", category: "Account",
    summary: "Grouped rows with switches, a picker and a confirm sheet.",
    description: "The settings screen people expect: grouped rows with icons, switches that flip, a menu picker, a row that pushes a detail screen, and sign out behind a confirmation sheet. Everything responds the way iOS Settings does.",
    try: ["Flip the Notifications switch", "Pick a new appearance", "Tap Sign out and confirm or cancel"],
    interactions: ["toggle", "select", "push", "sheet"],
    components: ["row", "picker", "confirm-sheet"],
    keywords: ["swiftui settings screen", "swiftui toggle", "swiftui picker menu", "swiftui form"],
  }),
  free({
    kind: "screens", slug: "home", title: "Home", category: "App", featured: true,
    summary: "A tabbed home with stories, cards and a floating tab bar.",
    description: "A home tab inside a real TabView: a greeting, a story strip, a featured card and recent items. Switch tabs and come back to find each one where you left it, the way iOS keeps tab state. Built from a TabView with three NavigationStacks.",
    try: ["Tap a story", "Switch to Search and back", "Tap the featured card to open it"],
    interactions: ["tabs", "tap", "push", "scroll"],
    components: ["story-strip", "card", "image"],
    keywords: ["swiftui home screen", "swiftui tabview", "swiftui tab bar", "swiftui feed"],
  }),
  free({
    kind: "screens", slug: "dashboard", title: "Dashboard", category: "App",
    summary: "Live figures, a bar chart and a breakdown ring.",
    description: "An at-a-glance dashboard: a headline figure that ticks, a range control, a bar chart you can scrub, and a spending ring. Tap a bar or a slice to read its value. Built from Live Stat, Swift Charts and Ring Breakdown.",
    try: ["Switch the range", "Drag across the bars", "Tap a slice of the ring"],
    interactions: ["select", "scrub", "tap"],
    components: ["live-stat", "chart", "ring-breakdown"],
    keywords: ["swiftui dashboard", "swift charts bar chart", "swiftui chart example"],
  }),
  free({
    kind: "screens", slug: "paywall", title: "Paywall", category: "Commerce", featured: true,
    summary: "Plan cards you can pick, features and a trial button.",
    description: "A subscription paywall that sells with clarity: a hero, three benefits, and plan cards where picking one moves the selection with a spring. The call to action springs when pressed. Built from Option Cards, rows and an Elastic Button.",
    try: ["Pick the Monthly plan, then Yearly", "Press Start free trial", "Tap Restore purchases"],
    interactions: ["select", "press", "spring", "haptic"],
    components: ["choice", "elastic-button", "image"],
    keywords: ["swiftui paywall", "swiftui subscription screen", "storekit paywall design", "swiftui pricing plans"],
  }),
  free({
    kind: "screens", slug: "product", title: "Product", category: "Commerce",
    summary: "A gallery, a quantity stepper and add to bag with a toast.",
    description: "A product detail page: swipe the gallery, read more of the description, choose a quantity, then add to bag and watch a toast confirm it. Built from a page carousel, Expandable Text, a Stepper and Toast.",
    try: ["Swipe the gallery", "Tap more to expand the description", "Add to bag"],
    interactions: ["swipe", "expand", "tap", "transition"],
    components: ["page-carousel", "expandable-text", "stepper", "toast"],
    keywords: ["swiftui product detail", "swiftui ecommerce", "swiftui stepper", "swiftui toast"],
  }),
  free({
    kind: "screens", slug: "send-money", title: "Send Money", category: "Commerce",
    summary: "Pick a person, type an amount, hold to send.",
    description: "A payment screen that makes sending feel deliberate: choose who, type the amount on a large field, then press and hold to send. Let go early and it rewinds. Built from Filter Rail, Amount Field and Hold To Confirm.",
    try: ["Pick a person", "Type an amount", "Hold the send button until it fills"],
    interactions: ["select", "type", "hold", "haptic"],
    components: ["hold-to-confirm", "amount-field", "filter-rail"],
    keywords: ["swiftui payment screen", "swiftui hold to confirm", "swiftui amount input"],
  }),
  free({
    kind: "screens", slug: "search", title: "Search", category: "Content",
    summary: "A search field, filters, recent searches and results.",
    description: "Search the way iOS does it: a field with a clear button and a Cancel that slides in while you type, filter chips, recent searches and results that open. Built from a search field, Filter Rail and native rows.",
    try: ["Tap the field and type", "Pick a filter", "Tap a result to open it"],
    interactions: ["type", "select", "push"],
    components: ["search-field", "filter-rail", "row"],
    keywords: ["swiftui search screen", "swiftui searchable", "swiftui search bar"],
  }),
  free({
    kind: "screens", slug: "now-playing", title: "Now Playing", category: "Media",
    summary: "Artwork, a scrubber, transport controls and volume.",
    description: "A music player you can actually play with: scrub the timeline, press the transport buttons, and drag the volume. Built from native sliders, buttons and an image, with haptics where the system gives them.",
    try: ["Drag the timeline", "Press play", "Drag the volume slider"],
    interactions: ["scrub", "drag", "press"],
    components: ["image", "slider", "button"],
    keywords: ["swiftui music player", "swiftui slider", "swiftui media player ui"],
  }),
  free({
    kind: "screens", slug: "discover", title: "Discover", category: "Media",
    summary: "A deck of cards you swipe to keep or skip.",
    description: "Swipe through a deck: cards follow your finger, tilt as they go, and fly off once you pass the threshold, or spring home if you don't. Built from Swipe Deck and Reaction Toggle.",
    try: ["Drag a card slowly, then let go", "Flick a card off the screen", "Tap the heart"],
    interactions: ["swipe", "spring", "haptic"],
    components: ["swipe-deck", "reaction-toggle"],
    keywords: ["swiftui swipe cards", "swiftui tinder cards", "swiftui drag gesture"],
  }),
  free({
    kind: "screens", slug: "notifications", title: "Notifications", category: "Content",
    summary: "A list you swipe to reveal actions.",
    description: "A notification list where each row slides to reveal its actions, snaps open or closed, and acts when you tap one. A menu in the corner offers mark all as read. Built from Swipe Action Row and a native Menu.",
    try: ["Swipe a row to the left", "Tap an action", "Open the menu in the top corner"],
    interactions: ["swipe", "menu", "tap"],
    components: ["swipe-action-row", "menu"],
    keywords: ["swiftui swipe actions", "swiftui notifications list", "swiftui context menu"],
  }),
  free({
    kind: "screens", slug: "tasks", title: "Tasks", category: "Productivity",
    summary: "Tasks you check off, filters and a new-task sheet.",
    description: "A task list where checking a task off springs and strikes it through, filters narrow the list, and New task opens a half-height sheet you can drag to full. Built from Task Row, Filter Rail and a sheet with detents.",
    try: ["Check off a task", "Tap New task", "Drag the sheet up to full height"],
    interactions: ["toggle", "sheet", "select"],
    components: ["task-row", "filter-rail", "progress"],
    keywords: ["swiftui todo list", "swiftui checklist", "swiftui presentation detents"],
  }),
  free({
    kind: "screens", slug: "assistant", title: "Assistant", category: "AI",
    summary: "Suggestions, a thinking state and a reply that streams in.",
    description: "An AI chat screen: suggestion chips to start, a thinking state while it works, and a reply that streams in word by word. Built from Prompt Chips, Thinking State and Streaming Reply.",
    try: ["Tap a suggestion", "Watch the reply stream in", "Tap the reply to stream it again"],
    interactions: ["stream", "tap", "loading"],
    components: ["streaming-reply", "prompt-chips", "thinking-state"],
    keywords: ["swiftui chat ui", "swiftui ai chat", "swiftui streaming text"],
  }),
  free({
    kind: "screens", slug: "booking", title: "Booking", category: "Productivity",
    summary: "Pick dates, guests and a budget, then book.",
    description: "A booking screen that turns choices into gestures: select a date range, step the guest count, drag a price range, then book with a button that shows its progress. Built from Date Range Picker, Stepper, Range Slider and Commit Button.",
    try: ["Pick a start and an end date", "Add a guest", "Drag both ends of the price range"],
    interactions: ["select", "drag", "loading"],
    components: ["date-range-picker", "range-slider", "stepper", "commit-button"],
    keywords: ["swiftui date picker range", "swiftui booking screen", "swiftui range slider"],
  }),
  free({
    kind: "screens", slug: "empty-state", title: "Empty State", category: "States",
    summary: "What people see first, with one way forward.",
    description: "An empty state that explains and invites: a friendly illustration, one sentence, and a button that takes you to create the first item. Built from Outcome Screen.",
    try: ["Tap New invoice"],
    interactions: ["tap", "push"],
    components: ["outcome-screen"],
    keywords: ["swiftui empty state", "contentunavailableview design"],
  }),
  free({
    kind: "screens", slug: "loading", title: "Loading", category: "States",
    summary: "Skeletons, progress and a result that resolves.",
    description: "Every way to wait well in one place: shimmering skeletons, a progress bar, a thinking line and a status that morphs from working to done. Tap Reload to run it again. Built from Skeleton Loader, Progress and Status Morph.",
    try: ["Tap the status to morph it", "Tap Reload"],
    interactions: ["loading", "transition"],
    components: ["skeleton-loader", "progress", "status-morph"],
    keywords: ["swiftui skeleton loading", "swiftui progressview", "swiftui loading state"],
  }),
];

// ---------------------------------------------------------------- Flows

const flows: CatalogEntry[] = [
  free({
    kind: "flows", slug: "onboarding", title: "Onboarding to Home", category: "First run", featured: true,
    summary: "Welcome, permissions, personalization, paywall, home.",
    description: "A complete first run, the way real apps do it: a welcome that pages, a notification permission, a quick personalization, a paywall presented as a sheet, and the home screen as the new root. Play it start to finish, or jump to any step.",
    try: ["Tap Get started and keep going", "Pick a few interests", "Start the trial to land on Home"],
    interactions: ["push", "sheet", "select", "transition"],
    components: ["page-carousel", "permission-sheet", "filter-rail", "choice"],
    steps: [
      { title: "Welcome", transition: "start" },
      { title: "Permissions", transition: "push", note: "NavigationLink pushes the next screen" },
      { title: "Personalize", transition: "push" },
      { title: "Paywall", transition: "sheet", note: ".sheet(isPresented:) presents the paywall" },
      { title: "Home", transition: "replace", note: "@AppStorage flag switches the app's root" },
    ],
    keywords: ["swiftui onboarding flow", "swiftui first run", "swiftui appstorage onboarding"],
  }),
  free({
    kind: "flows", slug: "sign-in", title: "Sign In", category: "Account",
    summary: "Welcome, sign in, reset password, home.",
    description: "Authentication end to end: a welcome, a sign-in form, a reset-password sheet, and the home screen once you're in. The reset sheet dismisses with a swipe; signing in replaces the whole stack, so there's no way back to the form.",
    try: ["Tap Sign in", "Open Forgot password? and swipe it away", "Sign in to reach Home"],
    interactions: ["push", "sheet", "type", "transition"],
    components: ["input", "apple-sign-in", "button"],
    steps: [
      { title: "Welcome", transition: "start" },
      { title: "Sign in", transition: "push" },
      { title: "Reset", transition: "sheet" },
      { title: "Home", transition: "replace", note: "Signing in sets @AppStorage(\"isSignedIn\")" },
    ],
    keywords: ["swiftui login flow", "swiftui authentication flow", "swiftui sign in navigation"],
  }),
  free({
    kind: "flows", slug: "checkout", title: "Checkout", category: "Commerce",
    summary: "Product, bag, pay, confirmation.",
    description: "A purchase from product to receipt: add to bag, review the bag, pay with a hold to confirm, and land on a confirmation. Each step pushes onto the stack; Done returns to the start.",
    try: ["Add to bag", "Go to the bag and continue", "Hold to pay"],
    interactions: ["push", "hold", "haptic"],
    components: ["hold-to-confirm", "stepper", "outcome-screen"],
    steps: [
      { title: "Product", transition: "start" },
      { title: "Bag", transition: "push" },
      { title: "Pay", transition: "push" },
      { title: "Done", transition: "push" },
    ],
    keywords: ["swiftui checkout flow", "swiftui shopping cart", "swiftui purchase flow"],
  }),
  free({
    kind: "flows", slug: "tab-app", title: "Tab App", category: "Navigation",
    summary: "Three tabs, each with its own stack.",
    description: "How a TabView app hangs together: three tabs, each its own NavigationStack. Push a detail in one tab, switch away and back, and it's still there. Tap the current tab again to pop to its root.",
    try: ["Open a detail in Home", "Switch to Library and back", "Tap Home again to pop to the root"],
    interactions: ["tabs", "push"],
    components: ["card", "row"],
    steps: [
      { title: "Home", transition: "start" },
      { title: "Detail", transition: "push" },
      { title: "Library", transition: "tab" },
      { title: "Account", transition: "tab" },
    ],
    keywords: ["swiftui tabview navigation", "swiftui tab bar app", "navigationstack in tabview"],
  }),
  free({
    kind: "flows", slug: "settings", title: "Settings", category: "Account",
    summary: "Settings, notifications, appearance, delete account.",
    description: "Settings three levels deep: rows push detail screens, switches and pickers keep their state as you go back, and deleting the account asks first with a confirmation sheet.",
    try: ["Open Notifications and flip a switch", "Go back and open Appearance", "Try Delete account"],
    interactions: ["push", "toggle", "select", "sheet"],
    components: ["row", "toggle", "picker", "confirm-sheet"],
    steps: [
      { title: "Settings", transition: "start" },
      { title: "Notifications", transition: "push" },
      { title: "Appearance", transition: "push" },
    ],
    keywords: ["swiftui settings navigation", "swiftui settings app"],
  }),
  free({
    kind: "flows", slug: "subscription-app", title: "Subscription App", category: "App starters",
    summary: "A welcome, a plan picker with a free trial, and home.",
    description: "Three linked screens for a subscription app, in the Candy look: a welcome, a plan picker with a free trial, and a home with today's habits. Remix the look and take it to Xcode.",
    try: ["Start the free trial", "Pick a plan", "Check off a habit"],
    interactions: ["push", "select", "toggle"],
    components: ["choice", "task-row", "text-reveal"],
    steps: [
      { title: "Welcome", transition: "start" },
      { title: "Plans", transition: "push" },
      { title: "Home", transition: "replace" },
    ],
    keywords: ["swiftui subscription app template", "swiftui app starter"],
  }),
  free({
    kind: "flows", slug: "finance-app", title: "Finance App", category: "App starters",
    summary: "A welcome, a wallet with spending, and send money.",
    description: "A finance app starter in the Studio look: a welcome, a wallet with a live balance and spending ring, and send money with hold to confirm.",
    try: ["Open the wallet", "Tap Send money", "Hold to send"],
    interactions: ["push", "hold", "select"],
    components: ["live-stat", "ring-breakdown", "hold-to-confirm"],
    steps: [
      { title: "Welcome", transition: "start" },
      { title: "Wallet", transition: "replace" },
      { title: "Send", transition: "push" },
    ],
    keywords: ["swiftui finance app template", "swiftui banking app ui"],
  }),
  free({
    kind: "flows", slug: "ai-app", title: "AI Assistant App", category: "App starters",
    summary: "A welcome, a chat that streams, and settings.",
    description: "An AI assistant starter in the Neon look: a welcome, a chat with suggestions and a streaming reply, and settings presented as a sheet.",
    try: ["Start chatting", "Tap a suggestion", "Open settings"],
    interactions: ["stream", "sheet", "toggle"],
    components: ["streaming-reply", "prompt-chips", "thinking-state"],
    steps: [
      { title: "Welcome", transition: "start" },
      { title: "Chat", transition: "replace" },
      { title: "Settings", transition: "sheet" },
    ],
    keywords: ["swiftui ai app template", "swiftui chatbot app"],
  }),
  free({
    kind: "flows", slug: "travel-app", title: "Travel App", category: "App starters",
    summary: "A welcome, destinations to explore, and a trip to book.",
    description: "A travel app starter in the Sol look: a welcome, destinations with filters, and a trip with its booking steps and a book button.",
    try: ["Plan a trip", "Filter destinations", "Open Lisbon and book"],
    interactions: ["push", "select", "loading"],
    components: ["filter-rail", "image", "status-timeline", "commit-button"],
    steps: [
      { title: "Welcome", transition: "start" },
      { title: "Explore", transition: "replace" },
      { title: "Trip", transition: "push" },
    ],
    keywords: ["swiftui travel app template", "swiftui booking app"],
  }),
];

// ---------------------------------------------------------------- UI elements

const elements: CatalogEntry[] = [
  free({
    kind: "elements", slug: "buttons", title: "Buttons", category: "Controls", featured: true,
    summary: "System and Liquid Glass buttons, a glass top bar, springy buttons and hold to confirm.",
    description: "Every kind of button an app needs, side by side: filled, tinted and plain system buttons, iOS 26 Liquid Glass buttons and a Glass Bar that keeps its title centred, an Elastic Button that squashes and springs, a Commit Button that shows loading and success, and Hold To Confirm for actions that deserve a pause.",
    try: ["Press each button", "Tap Save changes", "Hold to delete"],
    interactions: ["tap", "press", "spring", "loading", "hold"],
    components: ["button", "glass-bar", "elastic-button", "commit-button", "hold-to-confirm", "apple-sign-in"],
    keywords: ["swiftui button styles", "swiftui custom button", "swiftui button animation"],
  }),
  free({
    kind: "elements", slug: "cards", title: "Cards", category: "Content",
    summary: "Content cards, image cards, flip cards and tilt.",
    description: "Cards for every job: a native card with an action, an image card, a card that flips to its back, and a Motion Card that tilts toward your finger.",
    try: ["Tap the flip card", "Move over the motion card", "Tap Open on the card"],
    interactions: ["tap", "expand", "drag"],
    components: ["card", "image", "flip-card", "motion-card", "parallax-card"],
    keywords: ["swiftui card view", "swiftui flip card", "swiftui 3d card"],
  }),
  free({
    kind: "elements", slug: "text-fields", title: "Text Fields", category: "Inputs",
    summary: "Fields, secure entry, search, tokens, addresses, map pins and signatures.",
    description: "Every way to type into an app: a labelled text field, a floating-label form field, a password field with a strength meter, a search field with Cancel, a token field that turns words into chips, a big amount field, an address field that suggests as you type, a map you drag under a pin to set a spot, and a signature pad.",
    try: ["Type in each field", "Type a password", "Type a word and a comma in the token field", "Drag the map under the pin", "Sign the pad"],
    interactions: ["type", "drag"],
    components: ["input", "form-field", "secure-entry", "search-field", "token-field", "amount-field", "address-field", "signature-pad", "location-picker"],
    keywords: ["swiftui textfield", "swiftui securefield", "swiftui text input styles"],
  }),
  free({
    kind: "elements", slug: "toggles", title: "Toggles and Selection", category: "Controls",
    summary: "Switches, segmented controls and selectable cards.",
    description: "The controls that pick one thing: switches, a segmented control, glass segments, option cards that share a selection, and a reaction toggle that pops.",
    try: ["Flip the switches", "Move the segments", "Pick an option card"],
    interactions: ["toggle", "select", "spring"],
    components: ["toggle", "segmented", "glass-segments", "choice", "reaction-toggle"],
    keywords: ["swiftui toggle style", "swiftui segmented control", "swiftui picker segmented"],
  }),
  free({
    kind: "elements", slug: "sliders", title: "Sliders and Steppers", category: "Controls",
    summary: "Sliders, a range, steppers and a track that grows.",
    description: "Controls for amounts: the system slider, an Expanding Track that grows as you drag it, a two-thumb range, a stepper and a Scrub Stepper you drag to change.",
    try: ["Drag each slider", "Drag both ends of the range", "Scrub the stepper"],
    interactions: ["drag", "scrub", "haptic"],
    components: ["slider", "expanding-track", "range-slider", "stepper", "scrub-stepper"],
    keywords: ["swiftui slider", "swiftui range slider", "swiftui stepper"],
  }),
  free({
    kind: "elements", slug: "menus", title: "Menus and Pickers", category: "Controls",
    summary: "Menus, menu pickers and a glass action menu.",
    description: "Choices that open in place: a menu picker, a context menu with a destructive action, and a Glass Action Menu that blooms from a button.",
    try: ["Open the picker and choose", "Open the menu", "Tap the glass button"],
    interactions: ["menu", "select", "spring"],
    components: ["picker", "menu", "glass-action-menu"],
    keywords: ["swiftui menu", "swiftui context menu", "swiftui picker menu style"],
  }),
  free({
    kind: "elements", slug: "lists", title: "Lists and Rows", category: "Content",
    summary: "Rows, swipe actions, timelines, paging, a chat feed, drag-select and an A to Z index.",
    description: "The rows lists are made of: settings rows, a task row, a row with swipe actions, a status timeline and a list that loads more as you reach the end. Three whole-screen lists sit one tap away: a chat feed that follows new messages, a photo grid you select by dragging, and contacts with an A to Z index.",
    try: ["Swipe the row", "Check off the task", "Open the chat and scroll up", "Drag across the photos"],
    interactions: ["swipe", "toggle", "scroll", "drag"],
    components: ["row", "task-row", "swipe-action-row", "status-timeline", "paged-list", "follow-scroll", "drag-select-grid", "index-scrubber"],
    keywords: ["swiftui list row", "swiftui swipe actions", "swiftui infinite scroll"],
  }),
  free({
    kind: "elements", slug: "tabs", title: "Tabs and Docks", category: "Navigation",
    summary: "Tracking tabs, a floating dock and segments.",
    description: "Ways to switch views: tabs with an indicator that tracks between them, a floating dock, and a segmented control.",
    try: ["Tap each tab", "Pick a dock item"],
    interactions: ["tabs", "select", "spring"],
    components: ["tracking-tabs", "floating-dock", "segmented"],
    keywords: ["swiftui custom tab bar", "swiftui tabs indicator", "swiftui floating tab bar"],
  }),
  free({
    kind: "elements", slug: "sheets", title: "Sheets and Alerts", category: "Presentation",
    summary: "Sheets with detents, confirmations, permissions, toasts and a guided tour.",
    description: "Everything that rises over a screen: a half-height sheet you can drag to full, a confirmation sheet, a permission request, a toast, and a spotlight tour that dims the screen around each control it introduces.",
    try: ["Open the sheet and drag it up", "Tap Delete account", "Tap Save changes for a toast", "Take the tour"],
    interactions: ["sheet", "transition", "haptic"],
    components: ["confirm-sheet", "permission-sheet", "toast", "spotlight-tour", "button"],
    keywords: ["swiftui sheet", "swiftui presentationdetents", "swiftui toast", "swiftui confirmation dialog"],
  }),
  free({
    kind: "elements", slug: "charts", title: "Charts and Numbers", category: "Data",
    summary: "Bar charts, scrubbable lines, rings, a streak heatmap and rolling figures.",
    description: "Numbers that move: a Swift Charts bar chart, a line you scrub for exact values, a breakdown ring, a live figure, an odometer that rolls, and a streak heatmap you scrub day by day.",
    try: ["Drag across the line chart", "Tap a bar", "Tap a slice", "Scrub across the heatmap"],
    interactions: ["scrub", "tap", "transition"],
    components: ["chart", "scrub-chart", "ring-breakdown", "live-stat", "odometer", "activity-heatmap"],
    keywords: ["swift charts", "swiftui line chart", "swiftui animated number"],
  }),
  free({
    kind: "elements", slug: "feedback", title: "Loading and Feedback", category: "States",
    summary: "Progress, skeletons, status morphs and ratings.",
    description: "How an app says what's happening: progress bars and spinners, skeletons, a status that morphs between states, a thinking line and a rating you scrub.",
    try: ["Tap the status icon", "Scrub the rating"],
    interactions: ["loading", "transition", "scrub"],
    components: ["progress", "skeleton-loader", "status-morph", "thinking-state", "rating-scrub"],
    keywords: ["swiftui progressview", "swiftui skeleton view", "swiftui rating view"],
  }),
  free({
    kind: "elements", slug: "text", title: "Text and Type", category: "Content",
    summary: "Type styles, reveals, picture headlines, expanding text, tags and symbols.",
    description: "Type that does more than sit there: the system text styles, a headline that reveals word by word, a headline with living pictures between its words, text that expands with more, a streaming reply, tags and SF Symbols.",
    try: ["Tap the headline to replay it", "Tap the picture headline to watch its pictures open", "Tap more"],
    interactions: ["transition", "expand", "stream"],
    components: ["text", "text-reveal", "picture-headline", "expandable-text", "streaming-reply", "tag", "symbol"],
    keywords: ["swiftui text styles", "swiftui text animation", "swiftui read more text"],
  }),
  free({
    kind: "elements", slug: "media", title: "Media", category: "Content",
    summary: "Images, carousels, stories, link previews, attachments, a cropper and avatars.",
    description: "Visual content: image tiles, a paging carousel, a depth carousel, a story player, a link preview card, a tray of photo attachments, a photo cropper with aspect presets, a stack of avatars that fans out, and avatars with status.",
    try: ["Swipe the carousels", "Tap the story to skip ahead", "Add a photo to the tray", "Pinch the photo in the cropper", "Tap the avatar stack"],
    interactions: ["swipe", "tap"],
    components: ["image", "page-carousel", "depth-carousel", "story-strip", "link-preview", "attachment-tray", "photo-cropper", "fan-stack", "avatar"],
    keywords: ["swiftui carousel", "swiftui image gallery", "swiftui stories"],
  }),
];

// ---------------------------------------------------------------- Interactions

const interactionEntries: CatalogEntry[] = [
  free({
    kind: "interactions", slug: "swipe-cards", title: "Swipe Cards", category: "Gestures", featured: true,
    summary: "Drag a card; past the threshold it flies, short of it it springs back.",
    description: "The swipe deck, on its own. A DragGesture moves the card and rotates it with the offset; on release, distance and velocity decide whether it commits or springs home. Try it slow, then flick it.",
    try: ["Drag a card slowly and let go early", "Flick it hard", "Watch the next card rise"],
    interactions: ["swipe", "spring", "haptic"],
    components: ["swipe-deck"],
    keywords: ["swiftui swipe gesture", "swiftui drag gesture card", "swiftui card swipe animation"],
  }),
  free({
    kind: "interactions", slug: "swipe-actions", title: "Swipe Actions", category: "Gestures",
    summary: "Slide a row to reveal what you can do with it.",
    description: "Rows that slide to reveal actions and snap open or closed depending on how far and how fast you drag. Tap an action to run it.",
    try: ["Swipe a row left", "Swipe it back", "Tap an action"],
    interactions: ["swipe", "spring"],
    components: ["swipe-action-row"],
    keywords: ["swiftui swipeactions", "swiftui swipe to delete"],
  }),
  free({
    kind: "interactions", slug: "hold-to-confirm", title: "Hold to Confirm", category: "Gestures",
    summary: "Progress fills while you hold; let go early and it rewinds.",
    description: "A long press with visible progress, for actions that deserve a pause. Hold until it fills to commit with a success haptic; release early and it rewinds.",
    try: ["Hold until it fills", "Let go halfway"],
    interactions: ["hold", "haptic"],
    components: ["hold-to-confirm"],
    keywords: ["swiftui long press gesture", "swiftui hold button"],
  }),
  free({
    kind: "interactions", slug: "pull-to-refresh", title: "Pull to Refresh", category: "Gestures",
    summary: "Pull the list down past the top to reload it.",
    description: "The system refresh gesture: pull past the top, see the spinner, and the content settles back when it's done. In SwiftUI it is one modifier, refreshable, on a scrolling view.",
    try: ["Scroll to the top, then pull down"],
    interactions: ["pull", "loading"],
    components: ["row"],
    keywords: ["swiftui refreshable", "swiftui pull to refresh"],
  }),
  free({
    kind: "interactions", slug: "sheets", title: "Sheets and Detents", category: "Presentation", featured: true,
    summary: "Present a sheet at half height, drag it full, swipe it away.",
    description: "Sheets as iOS draws them: presented over the screen, resting at a detent, following your drag between half and full height, and dismissed with a swipe down. The screen behind recedes for a full-height sheet.",
    try: ["Open the half-height sheet", "Drag it up to full", "Swipe it down to dismiss"],
    interactions: ["sheet", "drag", "spring"],
    components: ["button"],
    keywords: ["swiftui presentationdetents", "swiftui bottom sheet", "swiftui half sheet"],
  }),
  free({
    kind: "interactions", slug: "push-navigation", title: "Push and Swipe Back", category: "Navigation",
    summary: "Go deeper with a push; come back with the edge swipe.",
    description: "A NavigationStack three screens deep. Each tap pushes the next screen from the trailing edge; the back button, or a swipe from the leading edge, takes you back, following your finger.",
    try: ["Tap through to the third screen", "Swipe back from the left edge, slowly"],
    interactions: ["push", "drag"],
    components: ["row"],
    keywords: ["swiftui navigationstack", "swiftui navigationlink", "swiftui swipe back"],
  }),
  free({
    kind: "interactions", slug: "spring-press", title: "Springy Press", category: "Motion",
    summary: "Buttons that dip, squash and spring back.",
    description: "Press feedback, compared: a system button, an Elastic Button that squashes and springs, and a press that scales. The spring's response and damping decide how it feels.",
    try: ["Press and hold each button", "Release quickly, then slowly"],
    interactions: ["press", "spring", "haptic"],
    components: ["elastic-button", "button"],
    keywords: ["swiftui spring animation", "swiftui button press animation", "swiftui buttonstyle scale"],
  }),
  free({
    kind: "interactions", slug: "drag-dial", title: "Drag a Dial", category: "Gestures",
    summary: "Turn a dial with your finger, feel each tick.",
    description: "A circular control you drag around to set a time, with a tick of haptic feedback at each step. The angle of your finger becomes the value.",
    try: ["Drag around the dial", "Go slowly to feel the ticks"],
    interactions: ["drag", "haptic"],
    components: ["timer-dial"],
    keywords: ["swiftui circular slider", "swiftui dial control", "swiftui rotation gesture"],
  }),
  free({
    kind: "interactions", slug: "scrub", title: "Scrub to Set", category: "Gestures",
    summary: "Slide across a control to change its value.",
    description: "Scrubbing: slide a finger across a value to change it continuously, with a selection tick at each step. A stepper, a rating and a chart that all answer to a drag.",
    try: ["Scrub the stepper", "Scrub the stars", "Scrub across the chart"],
    interactions: ["scrub", "haptic"],
    components: ["scrub-stepper", "rating-scrub", "scrub-chart"],
    keywords: ["swiftui scrubbing gesture", "swiftui chart selection"],
  }),
  free({
    kind: "interactions", slug: "expand", title: "Expand in Place", category: "Motion",
    summary: "Content that opens where it is.",
    description: "Things that grow without leaving the screen: a disclosure group, text with a more button, and a card that flips to show its back. The layout around each moves out of the way.",
    try: ["Open the disclosure group", "Tap more", "Flip the card"],
    interactions: ["expand", "spring"],
    components: ["disclosure", "expandable-text", "flip-card"],
    keywords: ["swiftui disclosuregroup", "swiftui expand collapse animation"],
  }),
  free({
    kind: "interactions", slug: "loading-to-success", title: "Loading to Success", category: "Motion",
    summary: "A button that shows it's working, then that it worked.",
    description: "The whole arc of an action in one control: tap, it becomes a spinner, then it lands on success with a haptic. Next to it, a status that morphs between working, done and failed.",
    try: ["Tap Save changes", "Tap the status icon"],
    interactions: ["loading", "transition", "haptic"],
    components: ["commit-button", "status-morph"],
    keywords: ["swiftui loading button", "swiftui success animation"],
  }),
  free({
    kind: "interactions", slug: "haptics", title: "Haptics", category: "Feedback",
    summary: "What each kind of sensory feedback is for.",
    description: "SwiftUI's sensoryFeedback gives each moment its own tap: selection for ticks, impact for presses, success and warning for outcomes. The playground shows where each fires and its name.",
    try: ["Flip the switch", "Scrub the stepper", "Hold to confirm"],
    interactions: ["haptic", "toggle", "scrub"],
    components: ["toggle", "scrub-stepper", "hold-to-confirm"],
    keywords: ["swiftui sensoryfeedback", "swiftui haptic feedback"],
  }),
  free({
    kind: "interactions", slug: "menus", title: "Menus", category: "Presentation",
    summary: "Menus that open from a control and close when you choose.",
    description: "A context menu, a menu picker and a glass action menu. Each opens from its control, dims nothing it doesn't need to, and dismisses on choice or on a tap outside.",
    try: ["Open the menu", "Choose from the picker", "Open the glass menu"],
    interactions: ["menu", "select"],
    components: ["menu", "picker", "glass-action-menu"],
    keywords: ["swiftui menu button", "swiftui contextmenu"],
  }),
  free({
    kind: "interactions", slug: "streaming-text", title: "Streaming Text", category: "Motion",
    summary: "A reply that arrives as it's written.",
    description: "Text that streams in word by word, so waiting reads as progress, with a thinking state before it starts. Tap to stream it again.",
    try: ["Watch it stream", "Tap to replay"],
    interactions: ["stream", "loading"],
    components: ["streaming-reply", "thinking-state"],
    keywords: ["swiftui streaming text", "swiftui typewriter effect"],
  }),
  free({
    kind: "interactions", slug: "paging", title: "Paging Carousels", category: "Gestures",
    summary: "Swipe pages that snap, with depth.",
    description: "Two ways to page: a page-style TabView that snaps a page at a time with dots, and a carousel where items scale with depth as they pass the center.",
    try: ["Swipe the pages", "Scroll the depth carousel"],
    interactions: ["swipe", "scroll", "spring"],
    components: ["page-carousel", "depth-carousel"],
    keywords: ["swiftui carousel", "swiftui paging scrollview", "scrolltransition swiftui"],
  }),
  free({
    kind: "interactions", slug: "tab-switching", title: "Tab Bar", category: "Navigation",
    summary: "Switch tabs; each keeps its place.",
    description: "A TabView with a floating tab bar. Each tab is its own NavigationStack, so switching away and back returns you to exactly where you were.",
    try: ["Switch tabs", "Open a detail, switch away, come back"],
    interactions: ["tabs", "push"],
    components: ["row"],
    keywords: ["swiftui tabview", "swiftui tab bar"],
  }),
  free({
    kind: "interactions", slug: "stretchy-header", title: "Stretchy Header", category: "Gestures",
    summary: "A hero that stretches when you pull and tucks away as you scroll.",
    description: "Pull down at the top and the header stretches with you; scroll and the title shrinks into a bar that pins to the top. The header reads the scroll offset, so it moves with your finger rather than on a timer.",
    try: ["Pull down at the top", "Scroll up to collapse the title"],
    interactions: ["pull", "scroll", "transition"],
    components: ["stretch-header"],
    keywords: ["swiftui stretchy header", "swiftui parallax header", "swiftui collapsing header"],
  }),
  free({
    kind: "interactions", slug: "toasts", title: "Toasts", category: "Feedback",
    summary: "A short confirmation that arrives and leaves on its own.",
    description: "A toast confirms something happened without stopping you. It slides in, waits a moment and leaves, or you swipe it away.",
    try: ["Tap Save changes", "Swipe the toast away"],
    interactions: ["transition", "swipe"],
    components: ["toast"],
    keywords: ["swiftui toast", "swiftui snackbar", "swiftui banner notification"],
  }),
];

export const entries: CatalogEntry[] = [...screens, ...flows, ...elements, ...interactionEntries];
